eBay/skin

browser.json
dist/less/ds4/variables.less
dist/less/ds6/mixins.less
dist/less/ds6/variables.less
dist/less/variables-common.less
dist/typography/ds6/typography.css
docs/_includes/ds6/less.html
docs/_includes/ds6/typography.html
docs/ds6/index.html
docs/src/less/ds6/index.less
docs/static/ds6/docs.css
docs/static/ds6/skin.css
less.browser.json
src/less/bundles/skin/ds6/skin.less
src/less/button/ds6/button-base.less
src/less/global/ds6/global.less
src/less/less/ds4/variables.less
src/less/less/ds6/mixins.less
src/less/less/ds6/variables.less
src/less/less/variables-common.less
src/less/notice/ds6/notice-base.less
src/less/typography/ds6/typography.less
typography.browser.json

First of all, my apologies for combining two separate issues in one PR (#6 and #18). They are however very closely related.
Notes to reviewer:
* `Caption 4` has been removed from type ramp until further notice (it still exists in screenshot for now)
* Some variables and mixins were moved out of "common-variables.less" into "ds4/variables.less"
* Some existing DS6 variables and mixins were renamed. Because ds6 is not yet ready for use (and not officially announced) we do not consider this a breaking change (v3.1.0 will be the first release that people can start using DS6)
* `less.browser.json` contains access to DS4 and DS6 variables and mixins without any conditional dependency. I think this should work okay, but we can review again in future if need be.
* No test page is created. I think …

New variables, mixins and classes for DS6 typography #6 #18

---

dist/marketsans/marketsans.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/fonts/marketsans/MarketSans-Regular-WebS.css
src/fonts/marketsans/MarketSans-SemiBold-WebS.css

Text on the page is blocked from displaying with default font placeholder till custom font file is downloaded unless its [reaches timeout](https://developers.google.com/web/updates/2016/02/font-display). `Font-display: optional` does not block the text from showing it
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
https://github.com/eBay/skin/pull/21

Adding font-display to unblock rendering of texts

---

dist/global/ds6/global.css
dist/less/ds6/mixins.less
dist/less/ds6/variables.less
dist/marketsans/marketsans.css
dist/typography/ds6/typography.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/bundles/skin/ds6/skin.less
src/less/global/ds6/global-static.less
src/less/global/ds6/global.less
src/less/less/ds6/mixins.less
src/less/less/ds6/variables.less
src/less/marketsans/marketsans.less

See #8 for details.
Notes about PR:
* Two LESS variables were renamed (@ds6-font-family-primary & @ds6-font-family-secondary)
* CSS Lint ignore was added for `font-display` property
* Default font-family was expanded from `"Helvetica Neue", Arial, sans-serif;` to `"Helvetica Neue", Helvetica, Arial, Roboto, sans-serif;`
* New global-static.less file was created
* `src/less/bundles/skin` was updated to use `global-static.less`. This bundle generates a css file in `_cdn` (skin.min.css) and `docs` (skin.css)
* the generated css files contain a slightly inefficient ungrouped selector, but I'm willing to let that slide to keep the build and project structure simple

Global: support font loading mechanism #8

---

README.md
docs/_includes/install.html

Remove the installation instruction for eBay internal NPM repository. This is not necessary anymore since eBay NPM repository now supports scoped package properly.
I've tested with npm or yarn install & it works without the `ebay:registry` workaround.

Remove instruction on scoped package workaround

---

dist/checkbox/ds4/checkbox.css
dist/radio/ds4/radio.css
docs/_includes/checkbox.html
docs/_includes/radio.html
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/test/checkbox/ds4/index.html
docs/test/radio/ds4/index.html
src/less/checkbox/ds4/checkbox-base.less
src/less/radio/ds4/radio-base.less

Issue: #41
Just baking in a little more flexibility, without changing the API too much. Might change the modifier from `checkbox__icon--inherit` to something else before it goes live. Maybe `checkbox__icon--custom`.

Checkbox and Radio: Enhancement for custom colour variant #41

---

dist/less/ds6/mixins.less
dist/less/ds6/variables.less
dist/typography/ds6/typography.css
docs/_includes/ds6/less.html
docs/_includes/ds6/typography.html
docs/ds6/index.html
docs/static/ds6/skin.css
src/less/bundles/skin/ds6/skin.less
src/less/less/ds6/mixins.less
src/less/less/ds6/variables.less
src/less/typography/ds6/typography-base.less
src/less/typography/ds6/typography.less

See issue #39 for spec.
Still awaiting clarification on what font-weight `secondary` is, and whether Market Sans even supports font weight other than regular or bold.
**Question**: are we okay with the classnames `medium`, `regular`, `small` etc. Or are they too generic? I'm kind of okay with them them, but maybe `medium-text`, `regular-text`, `small-text` is another alternative.

LESS: add new DS6 classes, mixins and variables for typography #39

---

dist/dropdown/ds6/dropdown.css
docs/static/ds6/skin.css
src/less/dropdown/ds6/dropdown-base.less

- remove `font-weight: bold` on `:active` menu items
From recent discussions with the design team, it was clarified that the bold treatment is meant for selected items, but not for `:active` items. This is an improvement for issues of reflow due to sizing changes on bold text vs regular text on click.
https://github.com/eBay/skin/issues/86 (partial fix)

Menu: remove bold styling on :active item

---

dist/pagination/ds6/pagination.css
docs/static/ds6/skin.css
src/less/pagination/ds6/pagination-base.less

Changes to use `hidden` attribute without adding more specificity
The `display: inline-block` was overriding the `display: none` in the `hidden` attribute.

Minor fixes

---

dist/notice/ds4/notice.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
src/less/notice/ds4/notice-base.less

- updated the SVG to be base64 encoded
When the SVG is URL encoded it can possibly be double-encoded by the browser. This causes it not to work properly. As we saw when working with the dialog close icon, we need to use base64 as it does not use any characters that need to be URL encoded, avoiding the issue.
Closes #88 
/cc @tcorley

Moving to base64 encoded, to avoid double-encoding;

---

dist/dropdown/ds6/dropdown.css
docs/_includes/ds6/menu.html
docs/static/ds6/skin.css
src/less/dropdown/ds6/dropdown-base.less

The current menu is limited to the width of the parent button, but this change makes the menu grow by default. This change switches the rules, if the menu should have the options match the width of the parent button, then the modifier named `match-width` would be used.
- renamed the `grow` modifiers to `match-width`
- changed `grow-reverse` to simply `reverse`
Per design specs, menus should grow automatically.
Closes #129

129 menu grow by default

---

dist/dialog/ds6/dialog.css
docs/static/ds6/skin.css
src/less/dialog/ds6/dialog-base.less

I noticed that the last-child and first-child rules were being applied to *every* first and last child in components inside the dialog. I'm not sure if this was the intended behavior but I checked how other components do similar things and they don't intend to modify every div they contain.
Before:
```
.dialog__body :last-child // rules would be applied to every subtree inside the dialog
```
```
.dialog__body:last-child // rules only applied to last-child of `.dialog__body`
```

Fix last-child and first-child with space in dialog

---

dist/button/ds6/button.css
docs/_includes/ds6/button.html
docs/static/ds6/skin.css
src/less/button/ds6/button-base.less

The current CTA button does not wrap properly when long text is applied to it.
**Note: this fixes overflow of all buttons that use the `__cell` container BEM modifier.**
```html
<p>
<button class="btn btn--secondary">
<span class="btn__cell">
<span>long text on a button</span>
</span>
</button>
<p>
<p>
<a class="cta-btn" href="http://www.ebay.com">
<span class="cta-btn__cell">
<span>long text on a button</span>
<svg aria-hidden="true" class="cta-btn__icon" focusable="false" height="8" width="8">
<use xlink:href="#icon-arrow-right-bold"></use>
</svg>
</span>
</a>
</p>
```
Some experimentation I did to find the solution: https://codepen.io/seangates/pen/LmZKgj
Closes #122

Fix overflow of all buttons

---

dist/dialog/ds6/dialog.css
docs/static/ds6/skin.css
src/less/dialog/ds6/dialog-base.less

In this PR the margin at the bottom of the `fill` and `default` dialog's has been fixed.
This was done by changing the `margin-bottom` on the `dialog__window` to use `padding-bottom` and having the actual `background-color` applied to a pseudo element which accounts for this padding.
It is kind of tacky to be sure, but the best solution I have found.
Closes #162

Dialog margin fix

---

dist/button/ds6/button.css
docs/_includes/ds6/button.html
docs/static/ds6/skin.css
src/less/button/ds6/button-base.less

When the label is empty (or missing altogether) it will apply the correct margins to the icon.
Closes #128

Fix for empty label on expand button

---

dist/pagination/ds6/pagination.css
docs/static/ds6/skin.css
src/less/pagination/ds6/pagination-base.less

The changes fix the issue that an unvisited link (page number) was showing up with DS4 color because of the global header.
Added the pseudo selectors `:link` and `:active` 
Fixes issue #188

Adding the pseudo selectors that was causing the color issue

---

dist/radio/ds6/radio.css
docs/_includes/ds6/radio.html
docs/_includes/radio.html
docs/static/ds6/skin.css
src/less/radio/ds6/radio-base.less

So, when we first moved over to SVG in DS4, we used inline SVG for everything (i.e. no background SVG). In an effort back then to simply the default radio/checkbox use case, to use a single SVG symbol instead of two (for checked and unchecked states), I created special merged versions of the inline checkbox and radio symbols, like so:
```svg
<symbol id="svg-icon-radio" viewBox="0 0 32 32">
<path class="unchecked" fill="currentColor" d="M16 31.6c-8.667 0-15.719-6.999-15.719-15.6s7.052-15.6 15.719-15.6 15.719 6.999 15.719 15.6c0 8.604-7.052 15.6-15.719 15.6zM16 2.178c-7.687 0-13.941 6.201-13.941 13.822s6.254 13.822 13.941 13.822 13.941-6.201 13.941-13.822-6.254-13.822-13.941-13.822z"></path>
<path class="checked-outer" d="M16 31.6c-8.667 0-15.719-6.997-15.719-15.6 0-8.601 7.052-15.6 …
```

Radio: refactor the custom icon and colour use cases

---

dist/dialog/ds6/dialog.css
docs/_includes/ds6/dialog.html
docs/static/ds6/skin.css
src/less/dialog/ds6/dialog-base.less

This PR adds a new modifier for the dialog element `dialog--no-mask` to allow users to remove the default background-color from the dialog.
In some cases (full screen dialogs) the animation looks a bit odd with the mask enabled.

Add dialog--no-mask modifier.

---

dist/checkbox/ds6/checkbox.css
dist/radio/ds6/radio.css
docs/static/ds6/skin.css
src/less/checkbox/ds6/checkbox-base.less
src/less/radio/ds6/radio-base.less

This reduces the clickable area for radio & checkbox. 
Browsers adds default margin to the above controls, hence resetting that. 
Fixes coreui issue [#200](https://github.com/eBay/ebayui-core/issues/200)
**Before:**
**After:**

reset default browser styles for radio & checkbox

---

dist/pagination/ds4/pagination.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
src/less/pagination/ds4/pagination.less

This PR adds `align-items: center;` to the `.pagination` parent class in the ds4 css. It also adds `display: inherit;` to the previous & next anchor links to better line up the spacing with the chevron svg icons inside them.
**Note:** I'm not sure if all of these static documentation files should be included, but they aren't in the .gitignore so I'm thinking yes. Let me know if I should build the project any differently, but I can tell the documentation is updated with my changes.
The ds4 style for pagination uses display: flex, but does not use flex centering. This works until any extra padding is added to the child items. In the ds6 styles some extra padding is added to the previous & next buttons and this problem becomes obvious. Adding `align-items: center;` seems to be a natural …

Issue 213: Adding vertical align-items to pagination parent

---

dist/link/ds6/link.css
docs/_includes/ds6/link.html
docs/_layouts/ds6/default.html
docs/ds6/index.html
docs/static/ds6/skin.css
link.browser.json
src/less/bundles/skin/ds6/skin.less
src/less/link/ds6/link-base.less
src/less/link/ds6/link-mixin.less
src/less/link/ds6/link.less

Addresses Nav Link and Action Link parts of issue #66.
Closes #66 
I think it's still a little unclear whether we are going with black text & blue underline for inline links, so I have left that part out for now (not a big fan of it personally, whatever the implementation).
I am on PTO this week and so may not be able to address comments until I get back. Just wanted to clear this off my plate :-)

Text Links: New DS6 Pattern #66

---

combobox.browser.json
select.browser.json

Select and combobox did not have the proper `*.browser.json` files in order to be available to projects via Lasso. This was found as part of splitting the select and combobox for mWeb-capable forms.

Adding missing select and combobox imports;

---

dist/select/ds6/select.css
docs/_includes/ds6/select.html
docs/static/ds6/skin.css
src/less/select/ds6/select-base.less

This fixes some styles related to the inline view of the select component. <strike>It also adds a `--small` modifier for when the select needs to match the default font size.</strike>
When placed inline with text, spans, or other inline content the select would position itself incorrectly.
Fixes #194

Fixing alignment and font; add another example;

---

dist/button/ds6/button.css
docs/_includes/ds6/menu.html
docs/static/ds6/skin.css
src/less/button/ds6/button-base.less

Added `svg.expand-btn__icon` style to DS 6, sharing from the existing style `svg.cta-btn__icon`.
Made `svg.expand-btn__icon` height/width the same as `span.expand-btn__icon`. Otherwise the icons will be larger than non SVG ones.
[EBAYUI-102](https://jirap.corp.ebay.com/browse/EBAYUI-102)

Issue 231: Support inline SVG for expand button in DS6

---

dist/button/ds6/button.css
docs/_includes/ds6/menu.html
docs/static/ds6/skin.css
src/less/button/ds6/button-base.less

Fixes #235 
Menu button / expand button now supports primary and secondary modifiers (and all disabled/hover/etc states)
Note that I had to change the source order of the `.expand-btn` block class for cascade reasons.
Please pull and test locally.

Menu: Add primary modifier #235

---

docs/_includes/ds4/checkbox-custom.html
docs/_includes/ds6/checkbox-custom.html

Quick fix, removes invalid markup that was destroying the ds6 docs (though it wasn't problematic in the ds4 docs).
Accidentally caused by https://github.com/eBay/skin/pull/253
Issue:

Docs: fix custom checkbox inclusion

---

docs/_layouts/ds6/test.html
docs/test/checkbox/ds4/index.html
docs/test/checkbox/ds6/index.html
docs/test/radio/ds4/index.html
docs/test/radio/ds6/index.html

A small PR that adds a DS6 test page for checkbox and radio that matches DS4 cases. We can cleanup and maybe reduce some duplication between the DS4 and DS6 test pages later, but for now this is a stop gap. 
Note: I intentionally removed the `ds4/test.css` in order to create a completely unstyled test page. The ds4 black/grey test pages were intended to make it easy to view the margin around an element, but they look a bit awful, so we will also remove those for ds4 at some point.
Also, we should update both ds4 and ds6 page to have test cases for checked state when non-disabled (I missed this, but we can add it later).

Checkbox & Radio: added DS6 test pages

---

dist/textbox/ds6/textbox.css
docs/_includes/ds6/label.html
docs/static/ds6/skin.css
src/less/textbox/ds6/textbox-base.less

- removes rounded corners on textboxes
- fixes the docs page IDs
When Safari on iPhone X shows the text boxes it adds a default rounded corner, which is not desirable. This fix removes that rounded corner.
Also, the docs were broken a little bit because several textboxes were using the same IDs.
Fixes #270 
**Before:**
**After:**

Removing rounded corners on input textboxes

---

dist/checkbox/ds4/checkbox.css
dist/checkbox/ds6/checkbox.css
dist/radio/ds4/radio.css
dist/radio/ds6/radio.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/checkbox/base/checkbox.less
src/less/checkbox/ds4/checkbox.less
src/less/checkbox/ds6/checkbox.less
src/less/radio/base/radio.less
src/less/radio/ds4/radio.less
src/less/radio/ds6/radio.less

As part of cleanup of LESS files I temporarily removed the "no-descending-specificity" stylelint rule and fixed all violations for checkbox and radio. I then put the rule back in place (until we've fixed all modules).
I tested this locally and nothing seems to break.
No properties are changed. Only certain rules are re-orderded to achieve an ascending specificity.
Trying to match the default, out of the box settings of stylelint where it makes sense.
#180.
We cannot currently disable this rule for CSS, due to the way the delta CSS is appended to the base CSS. But maybe in future we could use something like PostCSS/CSSComb to reorder the compiled CSS.
The LESS violations:

Checkbox: fixed "no-descending-specificity" LESS violations

---

dist/select/ds4/select.css
dist/select/ds6/select.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/select/base/select.less
src/less/select/ds4/select.less
src/less/select/ds6/select.less

As part of cleanup of LESS files I temporarily removed the "no-descending-specificity" stylelint rule and fixed all violations for **select**. I then put the rule back in place (until we've fixed all modules).
I tested this locally and nothing seems to break.
Trying to match the default, out of the box settings of stylelint where it makes sense.
#180.
We cannot currently disable this rule for CSS, due to the way the delta CSS is appended to the base CSS. But maybe in future we could use something like PostCSS/CSSComb to reorder the compiled CSS.
The LESS violations:

Select: fixed "no-descending-specificity" LESS violations

---

dist/dialog/ds4/dialog.css
dist/dialog/ds6/dialog.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/dialog/base/dialog.less

Change media query breakpoint for dialog
Design approved making the dialog larger at 767 rather than 600
Fixes https://github.com/eBay/skin/issues/316 and https://github.com/eBay/ebayui-core/issues/235

make dialog wider at 767px or lower

---

dist/pagination/ds6/pagination.css
docs/static/ds6/skin.css
src/less/pagination/ds6/pagination.less

Gave more room for the pagination focus for fluid pagination
Found that it was only happening in the fluid pagination due to the `overflow:hidden`.  But it was happening in other browsers (Chrome), not just safari.
Added padding to the `<ol>` to make sure it was visible, but used negative margins to keep the original height.
Fixes https://github.com/eBay/skin/issues/153

fixing pagination link focus

---

dist/switch/ds4/switch.css
dist/switch/ds6/switch.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/switch/base/switch.less

- adds `margin: 0` to switch `input`
Margin causes offset issues which can lead to event bugs.
Fixes https://github.com/eBay/ebayui-core/issues/359
Follow up to https://github.com/eBay/skin/pull/208
Before:
After:

Switch: clear default margin

---

dist/button/ds4/button.css
dist/button/ds6/button.css
docs/_includes/common/button.html
docs/_includes/ds4/button-expand.html
docs/_includes/ds6/button-expand.html
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/button/ds4/button-sizes.less
src/less/button/ds6/button-legacy.less

Added different padding for expand buttons, with a variation when there is not text using the "expand-btn--no-text" class.
It only added one extra CSS declaration to support the no-text case.  It was better than trying to restructure the html.
Fixes https://github.com/eBay/skin/issues/244

supporting expand button for small buttons

---

.gitignore
dist/select/ds4/select.css
dist/select/ds6/select.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/select/base/select.less
src/less/select/ds4/select.less

1. removed border onFocus for borderless select in Ds4 & Ds6 (similar to borderless listbox)
2. Removed background-color for borderless-disabled select & made it transparent in Ds4 & Ds6
3. updated .gitignore file to ignore history 
Since we have set padding-left: 0 and onFocus we have set the border, content seems to be overlapping with the border.  For eg:
#272 
Before:
--Borderless select DS4--
--Borderless Disabled select DS4 --
--Boderless select DS6--
After:
--Borderless select DS4--
--Borderless Disabled select DS4--
--Borderless select DS6--

Fix for Borderless select in DS4 #272

---

dist/dialog/ds4/dialog.css
docs/_includes/ds4/card.html
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
src/less/dialog/ds4/dialog.less

- fixes the dialog HTML in the cards example
- adds some (albeit, tightly coupled) CSS because the dialog body now has default margins
- minor fix for the heading margin in DS4 (since it's a fake heading using the first H2, it needs 4px more)
Fixing the example for the docs.
Fixes #320 
**Before**
**After**

Card dialog fixes;

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/dropdown/ds4/dropdown.css
dist/dropdown/ds6/dropdown.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/combobox/base/combobox.less
src/less/dropdown/base/dropdown.less
src/less/dropdown/ds4/dropdown.less

- updates CSS to align borderless modifiers for menu and combobox with the recent changes to select
- removes a dupe selector in the DS4 version
The current borderless versions were incorrect, given that they were all slightly different. This PR aligns them all together.
Fixes #343 
Fixes #344 
>**These screenshots are generalized for both menu and combobox.**
**Before:**
_Closed with focus_
_Open_
**After:**
_Closed with focus_
_Open_
**Before:**
_Closed with focus_
_Open_
**After**
_Closed with focus_
_Open_

Aligns all the borderless versions of select, menu and combobox;

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/dropdown/ds4/dropdown.css
dist/dropdown/ds6/dropdown.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
dist/pagination/ds4/pagination.css
dist/pagination/ds6/pagination.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/dropdown/base/dropdown.less
src/less/pagination/base/pagination.less
src/less/pagination/ds4/pagination.less
src/less/pagination/ds6/pagination.less

added flex-shrink: 0 to next previous buttons in pagination--fluid.
added a max-width: 100% to the container to prevent pushing over content.
removed flex-wrap: wrap from pagination/base.less and into ds4 as it was not needed for ds6.
fixes to make the ebayui-core pagination component work as expected.
it was for this issue
https://github.com/eBay/skin/issues/347
which appears the widths issue was already fixed. But this PR contains the rest of the fixes for ebayui-core pagination to work as expected.

updated some pagination styles regarding flex and max-width

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/dropdown/ds4/dropdown.css
dist/dropdown/ds6/dropdown.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
dist/tab/ds4/tab.css
docs/_includes/ds4/tab.html
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/dropdown/base/dropdown.less
src/less/tab/ds4/tab-mixins.less

- adjusts `tab` to allow wrapping
Tab is still DS4-only in Skin, but I did add padding and wrapping as designated in the DS6 design specs. Wrapping is achieved by making the children themselves `flex`. Verified across Chrome, Firefox, Safari, IE11.
Note: the Skin DS4 demo page has `break-all`, which might make the wrapping look funny at various sizes.
DS6 Design: https://ebay.invisionapp.com/share/CWN9X1JF6MA#/screens/278353515_Tabs
Closes #302 
Fixes #329

Tabs: support wrapping

---

dist/breadcrumb/ds4/breadcrumb.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
src/less/breadcrumb/ds4/breadcrumb.less

Added text-decoration and color to active and visited states.
Fixes https://github.com/eBay/skin/issues/355
There was no official design in skin DS4 so I used the browse use case, as the DS6 design docs suggested.
https://ebay.invisionapp.com/share/CWN9X1JF6MA#/screens/274338884

fix ds4 breadcrumb style

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/dropdown/ds4/dropdown.css
dist/dropdown/ds6/dropdown.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/dropdown/base/dropdown.less

Set background color on DS4 borderless menu to transparent.
Fixes https://github.com/eBay/ebayui-core/issues/388
There was no padding between the left edge and the menu text.  That matches the DS6 and old Skin design, but it looks crowded when there is a background color.

remove background color on borderless dropdown

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/combobox/base/combobox.less
src/less/combobox/ds4/combobox.less
src/less/combobox/ds6/combobox.less

- removes CSS for when combobox was a text input
- adds a fluid class since we took away the fluid nature of the combobox
We need to support combobox on mWeb. This is a short term fix while we look more holistically at the menu, select, combobox components as a whole.
Is in conjunction with the [eBayUI Core fix](https://github.com/eBay/ebayui-core/pull/393).
**Before**
**After**

Combobox mWeb fix

---

dist/combobox/ds6/combobox.css
dist/dropdown/ds6/dropdown.css
dist/menu/ds6/menu.css
docs/static/ds6/skin.css
src/less/dropdown/ds6/dropdown.less

- adds left margin for check mark
When the menu or combobox have small widths it can cause the check mark to be too close to the text.
None
**Before**
**After**

Fixing left margin for checkmark when in tight spaces;

---

dist/icon/ds6/icon.css
docs/static/ds6/skin.css
src/less/icon/ds6/icon.less

Currently when you click on an inline svg in IE it does not propagate click events for the `<use>` tag. This adds `pointer-events: none` to all inline svgs so that we skip the click event for the svg entirely.
Fixes https://github.com/eBay/ebayui-core/issues/396
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15727705/

Add pointer events none for icons to allow click events to work.

---

dist/pagination/ds4/pagination.css
dist/pagination/ds6/pagination.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/pagination/base/pagination.less
src/less/pagination/ds6/pagination.less

Moved `display: inline-flex` in pagination from DS6 to base so it will effect DS4 also.
Fixes: 
It looks like this isn't strictly needed for skin, but it fixes a DS4 pagination issue for ebayui-core.
https://github.com/eBay/skin/issues/369

moving display:inline-flex from ds6 to base

---

dist/icon/ds4/icon.css
docs/_includes/ds4/icon.html
docs/_includes/ds6/icon.html
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
src/less/icon/ds4/icon.less

Added change from DS6 icon style to DS4 icon style to remove mouse and touch events.
Added documentation.
Fixes https://github.com/eBay/skin/issues/373
Same fix as https://github.com/eBay/skin/pull/366 made for DS6

SVG click event fix for DS4

---

dist/select/ds6/select.css
docs/static/ds6/skin.css
src/less/select/ds6/select.less

Changing select icon height from 100% to a fixed height.
Firefox and IE had UI issues when the background image was sized to 100% height.

hotfix for select dropdown icon in IE

---

src/less/combobox/ds6/combobox-mixin.less

Reported bug that the combobox mixin was missing for the `gh.browser.json` LESS import.
Fixes #393

Adding missing combobox file;

---

package.json

- adds a `version` hook which runs the build before making the actual version commit
_Brilliant._ This helps us make sure the correct build files are in the same commit as the version bump, but without having to do any extra-special steps before or after the version commit.

Build: Adding npm version hook to pick up generated files;

---

dist/button/ds4/button.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
src/less/button/ds4/button-primary.less
yarn.lock

Override to the style for DS4 primary button hover/focus state. Changing the opacity to 0.8 from 0.7 for better color contrast.
Fixes https://github.com/eBay/skin/issues/421
Minimal change to meet a11y requirements.

Fix primary button a11y issue

---

dist/actionable/ds4/actionable.css
dist/actionable/ds6/actionable.css
dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
docs/_includes/common/badge.html
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
docs/test/badge/ds4/index.html
docs/test/badge/ds6/index.html
src/less/actionable/ds4/actionable-base.less
src/less/actionable/ds6/actionable.less
src/less/badge/base/badge.less
src/less/badge/ds4/badge.less
src/less/badge/ds6/badge.less
src/less/bundles/skin/ds6/skin.less
src/less/menu/base/menu.less

Refactored the badge classnames.
1. `menu-badge` renamed to just `badge` (margin left is now applied via menu module)
1. `icon-badge` renamed to just `badge` (positioning properties now applied via actionable module)
1. `icon-badge-container` renamed to `icon-btn--badged` (as above)
1. Missing `actionable` module added to DS6 less bundle
Changes are based on sprint review feedback.
The badge module now essentially just contains the base properties for a badge. Any instance specific styles have been moved out to the respective module (e.g. menu and actionable).
1. Existing alignment issue
1. Un-normalized folder structure of actionable module
#80

Badge: some refactoring of classes based on feedback

---

CONTRIBUTING.md

The release instructions have now been simplified thanks to the new npm version hook added by Sean.

Docs: updates based on our new npm version hook

---

dist/actionable/ds4/actionable.css
dist/actionable/ds6/actionable.css
dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
docs/static/ds4/skin-full.css
docs/static/ds4/skin.css
docs/static/ds6/skin.css
src/less/actionable/ds4/actionable-base.less
src/less/actionable/ds6/actionable.less
src/less/badge/base/badge.less

- base `.badge` class now has a `1px` top padding
- actionable `.badge` resets the line height to `1rem;`
The font looked misaligned across all the browsers. This creates a pixel-perfect version they all appear to like.
Fixes #441.
>Yay 400% zoom.

Updates to get pixel perfect font alignment in the badge;

---

docs/_includes/ds6/install.html
docs/archive/v5.0/ds6/index.html
docs/archive/v5.1.2/ds6/index.html
docs/archive/v5.1/ds6/index.html

lasso-page flags attribute should take actual array rather than array enclosed in double quotes.
@seangates

Fixed docs: Unwanted double quotes in lasso-page flags for DS6

---

combo.browser.json

#460 
Adding a flag `icon-opt-out` in `combo.browser.json` to not include `icon`, `iconfont` and `spinner` modules. 
**Note:** The DS4 [combo documentation](https://ebay.github.io/skin/#bundles_combo) is not updated to reflect this. This is anyway going to be changed in 7.0.0 with `skin-ds6` flag, hence the update would be redundant.

Allow an flag in combo.browser.json to opt out of icon modules

---

gh.browser.json
src/less/icon/common/ds6/icon-mixin.less
src/less/icon/icon-mixin.less

1. Fix error thrown when importing `gh.browser.json` due to invalid path.
1. Updated `gh.browser.json` with correct path to `icon-mixin.less`
1. Updated `icon-mixin.less` with the 3 paths to common, background and foreground css

Fix gh.browser.json and icon-mixin #482

---

combo.browser.json
docs/_includes/common/bundles.html

As previously discussed, this small PR simply removes the `@ebay/skin/icon` module from the combo bundle (used by inception), thus giving the app the choice of whether to use background or foreground icons (or both).
Fixes #457

Combo: removed @ebay/skin/icon from this bundle (#457)

---

docs/_includes/common/breadcrumb.html

Breadcrumbs has anchor instead of button closing tag in Docs
Breadcrumbs has anchor instead of button closing tag in Docs
https://ebay.github.io/skin/#breadcrumb

Breadcrumbs has anchor instead of button closing tag in Docs

---

icon/background.browser.json
icon/foreground.browser.json

This addresses the issue we noticed on coreui with small foreground icons due to incorrect css cascade order.

Icon: changed module dependency order to fix css cascade

---

gulpfile.js
package.json
yarn.lock

v4 is sooo much nicer than v3!
Couple of notes:
1. Was able to drop the `run-sequence` plugin as this is now built into v4
1. Gulp tasks just become functions now. Nice.
I'm probably not using all the whizzy new features of v4 (I've not delved into the new abilities of the watch function, for example), but this is a start.
Might aswell merge this straight into master. No point waiting for 7.1.0.

Upgraded Gulp from v3 to v4 (#480)

---

docs/_includes/common/checkbox.html
docs/_includes/common/radio.html

Issue #592
This PR is intended for master branch. Documentation change only.
It appears that there are some redundant icon classes on the checkbox and radio examples that can cause specificity issues in the cascade. See #592 for details.
I also changed the HTML width and height attributes to 18x18 (these are the non-CSS fallback dimensions).

Website: remove redundant classes from checkbox (#592)

---

icon/browser.json

Fixes #676 Remaps DS6 files when DS6 flag is passed
Added a browser.json remap to the icon directory in order to remap ds6 files.
If the user would reference files from icon directory they will not be remapped properly since it looks for the nearest browser.json in the directory it's currently in.
#676

Added browser.json into icons directory

---

docs/_includes/common/notice.html

Closes #675 
Simple change to remove flyout-notice section from website. I'm pretty sure we wont see a return of this pattern in DS6.5 review, but I've left it commented out for now (rather than deleted) just in case.

Website: removed flyout-notice (#675)

---

icon.browser.json
icon/browser.json

Changed browser.json in icon directory to load dependencies. Since a reference of `@ebay/skin/icon` would actually load this browser.json with no depdendencies. 
We also tested that the remaps would work properly but not load the given dependencies (so loading just foreground icons would still work as before).
Changed the base icon.browser.json to load the ./icon/browser.json in order to not prevent any breaking changes. 
ebay/ebayui-core#779

Changed browser.json to load icons correctly

---

docs/_includes/common/cdn.html
docs/ds6/index.html
docs/index.html
package.json
scripts/cdn-version.js

- add a script to version the `cdn.html` file
- adds a new `version` variable for Jekyll
This is an automation so we don't have to update the CDN file manually after versioning.

Process to version cdn.html file;

---

docs/_includes/common/filter-button.html
docs/_includes/common/filter-menu-button.html
docs/_includes/common/filter-menu.html

I went through the filter, filter-button and filter-menu-button docs and cleaned up a few things. Most of the noise in the diff here comes from switching all examples to use background svg (to be consistent with other modules) instead of foreground svg.
Btw, I noticed the filter menu button supports a background icon, but it is not done in a way consistent with other modules. We have to specify the name of the icon, `icon icon--chevron-down`, instead of just supplying `filter-menu-button__icon`. The benefit of the latter approach is that we can abstract away the differences between ds4 & ds6 if neeeded, plus there is no dependency on the icon module (the base64 for the icon can be bundled in with the module's own css).
* Changed all examples to use background svg
* Remove `filter-group` …

Docs: cleanup & fixes related to new filtering features

---

dist/tooltip/ds4/tooltip.css
dist/tooltip/ds6/tooltip.css
docs/_includes/common/tooltip.html
src/less/tooltip/base/tooltip.less
src/less/tooltip/ds4/tooltip.less
src/less/tooltip/ds6/tooltip.less

* Changed infotip to have proper accessibility fixes (i.e. role=heading on span)
* Added top/left alignment for infotip when shown (and added the same to the examples, were not there before). This should align properly with both ds4/6
* Made infotip icon size to 16px. The svg was 16px but the icon was 32. This was creating a large padding around the 16px icon. I also added a margin 2px to align from bottom
#595 
#695 
DS6
DS4

Infotip bugfixes

---

docs/_includes/common/icon.html

Created documentation for inline icons on non node applications
I included the link to the rawgithub context for the ds4/6 icons, because the normal link does not show a source page, but tries to display the `svg`. 
If there's a way around this, I think the normal github link is better.
https://github.com/eBay/skin/blob/master/src/svg/ds6/icons.svg
#796

Updated documentation for inline icons

---

.npmignore

Removed `_cdn` from `.npmignore`.
Fixes #650

Removed _cdn from npm ignore

---

menu-button.less
menu-button[skin-ds6].less

Currently the top level less file for the `menu-button` is pointing to a non-existing file. The top level less files are used when skin is consumed via webpack, and this causes that to break.

Fix typo with top level less files

---

docs/_includes/common/button.html
docs/_includes/common/combobox.html
docs/_includes/common/cta-button.html
docs/_includes/common/details.html
docs/_includes/common/dialog.html
docs/_includes/common/expand-button.html
docs/_includes/common/filter-button.html
docs/_includes/common/filter-menu-button.html
docs/_includes/common/filter-menu.html
docs/_includes/common/link.html
docs/_includes/common/listbox-button.html
docs/_includes/common/listbox.html
docs/_includes/common/menu-button.html
docs/_includes/common/menu.html
docs/_includes/common/select.html

Demo `div` elements were sometimes being closed before the code sample, and sometimes closed after the sample. This PR makes all sections consistent and closes the div *before* the code sample. This helps us get a clearer idea of the widget boundaries.
Before changes:
After changes:

Website: formatting fixes for broken code example sections

---

docs/_includes/tests/notice.html

Had a typo in guidance test page. Named the guidance class incorrectly. 
Renmaed `page-notice--guided` to `page-notice-guidance`.
Also removed some misc whitespace and changed a text from Link to button to match the other ones.

Fixed typo in guidance test

---

src/less/dialog/ds4/dialog.less

- change padding calculation to use 14px;
Helps better align body content with the dialog header.
n/a

Patch dialog ds4 padding

---

dist/variables/ds4/color-variables.less
dist/variables/ds6/color-variables.less
src/less/checkbox/base/checkbox.less
src/less/radio/base/radio.less
src/less/switch/base/switch.less
src/less/variables/ds4/color-variables.less
src/less/variables/ds6/color-variables.less

Replace color numbers with a variable
Because magic numbers are hard to maintain
Not sure if I've put the variables in the correct places...

Remove magic number in outline color (9.5.0)

---

gh.browser.json

Fixes #961 
Updates paths to variables and mixins (they were split up, into different locations, a few releases back)

GH: fix missing browser.json paths

---

scripts/generate-base64.js
scripts/generate-helper.js

Split up image script to have two versions of the script, one for SVG and one for Background SVG parsing
For fixing the aliases there needs to be a bit more investigation. If we use `<use>` tag within the `<symbols>` tag, it does not work. So most likely the fix will be to create an alias list and then create those new SVGs in the dist folder. 
#930

Split up image script to have base64 and normal image optimization

---

.stylelintrc-less
package.json
yarn.lock

I've been going through [stylelint plugins](https://stylelint.io/user-guide/plugins) and seeing if there's anything we can utilize. This one seems interesting. It hooks into our ebay browserlist config (@seangates) which is cool. I think I'll leave it at warning level for a while and see how it goes:

Add stylelint-no-unsupported-browser-features

---

docs/_includes/common/dialog.html
docs/_includes/tests/dialog-full.html
docs/_includes/tests/dialog-lightbox.html
docs/_includes/tests/dialog-multistep.html
docs/_includes/tests/dialog-panel-left.html
docs/_includes/tests/dialog-panel-right.html
docs/_includes/tests/dialog-subpage.html

Been meaning to do this for a while. Bones, MIND Patterns and now Skin are updated to:
* add `aria-modal`
* remove `role=document`
* no longer needed in ARIA 1.1. See: https://a11ysupport.io/tests/aria_dialog_document_mode
```html
<div aria-labelledby="dialog-title" aria-modal="true" class="dialog" hidden role="dialog">
<div class="dialog__window">
<button aria-label="Close dialog" class="dialog__close" type="button">
<svg aria-hidden="true" class="icon icon--close" focusable="false" height="16" width="16">
<use xlink:href="#icon-close"></use>
</svg>
</button>
<div class="dialog__body">
<h2 id="dialog-title" class="large-text-1 bold-text">Heading</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua. Ut enim ad …
```

Dialog: added aria-modal & removed nested role=document

---

dist/textbox/ds4/textbox.css
dist/textbox/ds6/textbox.css
docs/_includes/common/textbox.html
src/less/textbox/base/textbox.less

Textbox icons can now be actionable/clickable in certain use cases
As an example, a textbox can represent a calendar component where
a user can click on the calendar icon and then a calendar dropdown
shows up.
https://github.com/eBay/skin/issues/977

feat: Add actionable textbox icon

---

dist/textbox/ds4/textbox.css
dist/textbox/ds6/textbox.css
docs/_includes/common/textbox.html
docs/_includes/tests/textbox.html
src/less/textbox/base/textbox.less
src/less/textbox/ds4/textbox.less
src/less/textbox/ds6/textbox.less

- Add a test for actionable icon for a textbox
- Also fix styles to achieve 14w x 40h icon measurements which is in compliance with the existing icons for a text-box 
977

Add textbox actionable icon test

---

dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
dist/variables/ds4/dropdown-variables.less
docs/_includes/common/menu-button.html
docs/_includes/tests/menu-button.html
src/less/menu-button/base/menu-button.less
src/less/variables/ds4/dropdown-variables.less

Fixes issue (ticket coming soon) found in QA of 10.0.0 re-release.
Also adds missing test case.
Before fix:
After fix:

Menu Button: fix font-size and colour of fake-items

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
src/less/combobox/base/combobox.less
src/less/menu-button/base/menu-button.less
src/less/menu/base/menu.less

* For combobox added a dropdown status mixin to the svg icon, this fixes that issue
* For the menu badge, this was a problem caused by flex. Since badge was nested inside of the span menu option it would not have a flex center align (the center align would have to be put on items inside the menu item). So in order to fix it, in ebayui I had to put the badge in the same level as the tick and text
So makeup is:
```
<div menu__item>
<span> Text</span>
<span badge>
<svg tick>
</div>
```
This way when the badge is there it picks up the parent alignment.  However the flex throws it off since the flex is set to 1 from the `menu__item > span` which forces the badge to fill the rest of the content. So I make it initial so it does not have any flex
#1014
eBay/ebayui-core#1039

Fixed combobox readonly and badge width on menu

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
docs/_includes/common/combobox.html
src/less/combobox/base/combobox.less

For #1014
~~Seems like my previous fix was not working as intended. I had some problems in my local which I fixed~~
~~The fix for this one is just making the containers position relative. I removed that previous code from the https://github.com/eBay/skin/pull/1016 which was causing some other issues with opacity~~
So combobox readonly did not have the code changed to support background icons. This fix does that. Basically reverted the last fix and added opacity to the checkbox. I also left in position relative to position the tick correctly. 
Updated skin docs. 
#1014 
Skin docs side:

Fixed position of tick element and removed dropdown status

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/listbox-button/ds4/listbox-button.css
dist/listbox-button/ds6/listbox-button.css
dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
dist/mixins/dropdown/base/dropdown-mixins.less
src/less/mixins/dropdown/base/dropdown-mixins.less

In the case where a similar z-index of 1 item is below menu, it overlaps because of the placement is after. 
I changed the menu z-index by 1 in order to prevent that. 
eBay/ebayui-core#1039

Fixed z-index for menu

---

dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
docs/_includes/common/menu-button.html
docs/_includes/common/menu.html
src/less/menu-button/base/menu-button.less
src/less/menu-button/menu-button.stories.js
src/less/menu/base/menu.less
src/less/menu/menu.stories.js

Issue #1006 
Adds a horizontal divider/separator to menu and menu button. The line looks a little chunky and heavy to me, although it is following the spec. We may want to check in with design before releasing. I might need to reduce the vertical margins a little bit.

Menu: add divider #1006

---

docs/_config.yml
docs/ds4/index.html
docs/index.html
package.json
scripts/jekyll-config.js

The test pages are currently broken due to the CDN path missing the `version` configuration variable. I have moved this variable to the Jekyll default config from where all pages will inherit it. I also updated the script & renamed it to be more in line with its purpose.

Website: update script to add skin version to jekyll defaults

---

dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
src/less/menu-button/base/menu-button.less

Fixes: #1043 
Spacing looks better now.

Menu: too much spacing between separators #1043

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
src/less/combobox/base/combobox.less

User agent stylesheets for safari adds margin left and right by default
Or make input width: 100%
combobox did not align with dropdown
https://github.com/eBay/skin/issues/936

Combobox: overlay position not aligned correctly (Safari) #936

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
docs/_includes/common/combobox.html
docs/_includes/tests/combobox.html
src/less/combobox/base/combobox.less
src/less/combobox/combobox.stories.js

PLEASE SQUASH.
Fixes #1045
Because combobox uses absolute positioning for dropdown icon, RTL feature is broken. This PR adds CSS to RTL direction combobox that adjusts the placement of icon and text box.

Fix RTL for combobox

---

dist/wizard-stepper/ds4/wizard-stepper.css
dist/wizard-stepper/ds6/wizard-stepper.css
docs/_includes/common/wizard-stepper.html
src/less/wizard-stepper/base/wizard-stepper.less
src/less/wizard-stepper/wizard-stepper.stories.js

So I was playing around with the wizard stepper, and I couldn't get it to behave like I wanted to with the existing markup that I originally was hoping for. So I tried adding an additional separator element for the lines between the steps and it now seems to behave. It also much simplified the CSS for the vertical stepper, as that can now use block level layout instead of flex.
With this new approach I would expect the app to add a constrained width and/or `margin: 0 auto` to center (I guess we could add a modifier to do that centering too).
If we are good with this new approach, before we can release, I recommend another follow-up PR with some further cleanup:
* refactor LESS to remove concatenated class names. All class names should be fully searchable.
* remove all instances of …

Refactor wizard-stepper markup #191

---

dist/label/ds4/label.css
dist/label/ds6/label.css
dist/textbox/ds4/textbox.css
dist/textbox/ds6/textbox.css
src/less/label/base/label.less
src/less/label/ds4/label.less
src/less/label/ds6/label.less
src/less/textbox/base/textbox.less
src/less/textbox/ds6/textbox.less

Fixes #1075 
After updates new distances are 12px and 25px (increased from 10px and 21px). It is a little dependent on how the measurement is done. We could potentially increase the space by another pixel, but it currently looks pretty good to me.
If I were to refactor I would try and create some kind of distance variables or mixins, as it currently does require a bit of head scratching to figure out what is going.
Also:
* Label font size decreased to 14px
* Underline textbox font weight changed to bold
* Underline colour changed to #767676.

Fix Textbox and Label discrepancies with Playbook #1075

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less

There was a bug where the non carousel autoplay would take precedence in styles and override the transition property. This seems to be only an edge case in some places where the styles aren't being loaded the normal way. So a fix would be to add the translate property together with border-color in transition.

Added carousel transition to non autoplay carousel

---

dist/toast/ds4/toast.css
dist/toast/ds6/toast.css
src/less/toast/base/toast.less

When doing ebayui I ran into two issues
* Anchor tag was colored the same as background
* Leaving transitions were not working
This pr fixes that. 
* Made `show-init` and `hide` do the same as well as `hide-init` and `show`. (This is in line with dialog)
* Removed the `.toast[type=dialog]:not(:hidden)`. This was overriding styles and taking precedence in styles over the hide. (and it's not needed). 
* Added outline to anchor focus (and made a mixin for it)
Tested in ebayui also with the toast branch and was working fine.

Fixed toast transitions and anchor tag color

---

dist/variables/ds6/color-variables.less
src/less/root/ds6/root.less
src/less/variables/ds6/color-variables.less

PLEASE SQUASH
Just a small, quick PR to show how the dark mode color variables will be named. In my initial commit I went with pre-fixing the `dark-mode-`, but then realised that not every light mode color will have a dark mode equal, and therefore postfixing makes more sense, so I made another commit to change that.

Root: convert hex values to LESS variables

---

dist/actionable/ds4/actionable.css
dist/actionable/ds6/actionable.css
dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
dist/variables/ds6/color-variables.less
src/less/actionable/base/actionable.less
src/less/actionable/ds4/actionable.less
src/less/actionable/ds6/actionable.less
src/less/badge/base/badge.less
src/less/badge/ds4/badge.less
src/less/badge/ds6/badge.less
src/less/switch/ds6/switch.less
src/less/variables/ds6/color-variables.less

PLEASE SQUASH
ISSUE #1098
This PR adds custom properties to the actionable and badge modules. However, I would first like some discussion on the potential bloat impact of the custom variables in the dist CSS (pasted below).  Should we include these var declarations by default for every module, or setup our build in such a way so they are opt-in only? I'm feeling like it should be optional, but on the flip-side the gzip impact could be negligible...
```css
a.icon-link,
button.icon-btn {
--actionable-icon-foreground-color: #111820;
--actionable-icon-foreground-color-active: #111820;
--actionable-icon-foreground-color-visited: #111820;
--actionable-icon-foreground-color-hover: #3665f3;
--actionable-badge-border-color: #fff;
--actionable-image-border-color-hover: #767676;
}
a.img-link, …
```

Actionable: custom properties

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less

Seems like something changed and caused `opacity:0` to have lower specificity than `:hover` opacity. Then paddles were being shown.
Changed to do display none so they are hidden.

Fixed carousel-controls-disabled to do display:none

---

dist/radio/ds4/radio.css
dist/radio/ds6/radio.css
dist/variables/ds6/radio-variables.less
docs/archive/v9.5/index.html
src/less/radio/base/radio.less
src/less/radio/ds6/radio.less
src/less/variables/ds6/radio-variables.less

Hey Skins Team, 
Basically what I have done was switch out some of the CSS code for Radio for the CustomColor mixin utility that we introduced. I also added the corresponding light mode colors to dark mode for radio as well when they would be switched. 
I can remove the commented out CSS once you guys think it's good. It's just there for my reference when I do diff. 
Screenshots of the Dark Mode: 
I think we are gonna need to figure out what should be the dark mode equal to `@color-control-outline: @color-grey5;` since `color-grey-5` doesn't have a dark mode equal.

Refactor radio to use Custom Mixin and added Dark Mode Colors as needed

---

dist/actionable/ds4/actionable.css
dist/actionable/ds6/actionable.css
dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
dist/breadcrumbs/ds4/breadcrumbs.css
dist/mixins/utility/utility-mixins.less
dist/switch/ds4/switch.css
dist/switch/ds6/switch.css
src/less/actionable/base/actionable.less
src/less/actionable/ds4/actionable.less
src/less/actionable/ds6/actionable.less
src/less/badge/base/badge.less
src/less/badge/ds4/badge.less
src/less/badge/ds6/badge.less
src/less/breadcrumbs/base/breadcrumbs.less
src/less/breadcrumbs/ds4/breadcrumbs.less
src/less/breadcrumbs/ds6/breadcrumbs.less
src/less/mixins/utility/utility-mixins.less
src/less/switch/base/switch.less
src/less/switch/ds4/switch.less
src/less/switch/ds6/switch.less

Issue #1098
I have decided to add support for custom properties to DS4. This allows us to move towards a new much simplified build and delivery system that can leverage the power of CSS Custom Properties.
(I also did a bit of alphabetical reordering of property names, not out of OCD, but because we are trying to do a global cleanup of all "design tokens" across all 3 platforms and so this helps visualise them)
--
I've not yet totally committed to this new system, but to have any possibility of it, we need to define the DS4 custom properties values, as I've done in this PR.
We have already, over time, normalised the DS4 and DS6 markup so that it is identical. With custom properties we could now abolish the ds4 and ds6 dist directories and just build a single dist css file.
Essentially DS4, …

Custom Properties for DS4 for potential new build & delivery system

---

dist/checkbox/ds4/checkbox.css
dist/checkbox/ds6/checkbox.css
dist/variables/ds6/checkbox-variables.less
src/less/checkbox/base/checkbox.less
src/less/checkbox/ds6/checkbox.less
src/less/variables/ds6/checkbox-variables.less

Hey everyone, 
So I have refactored the checkbox component that uses the customColors mixin (basically exposes the color properties) and I have added the corresponding dark mode colors, though they might change. 
Screenshots: 
With the `skins-experiment-1` class in the <body> tag of `docs/_layouts/default.html`

Refactor Checkbox Component to use CustomColor and Dark Mode

---

dist/toast/ds4/toast.css
dist/toast/ds6/toast.css
src/less/toast/base/toast.less

In ebayui we need to add `toast__title` class to h2 in order for this to work. However this is not possible with the current API. Added an h2 in order to support this (however this can be removed after api change in ebayui)

Updated toast__title to also include h2

---

docs/_includes/common/bundling.html

Update documentation for webpack support.
The webpack is no longer use LESS files as its top-level entries but it's still mentioned on the readme.
- Outdated Webpack doc: https://github.com/eBay/skin/issues/1125
- Top level entries no longer LESS: https://github.com/eBay/skin/pull/1095

Documentation update for webpack support

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/textbox/ds4/textbox.css
dist/textbox/ds6/textbox.css
docs/_includes/common/textbox.html
src/less/combobox/base/combobox.less
src/less/textbox/base/textbox.less
src/less/textbox/textbox.stories.js

* Fixed combobox actionable svg position by making the non actionable styles ignored in actionable (added adjacent rules)
* Added example for textbox dual icons
#1129

Actionable button fixes

---

dist/dialog/ds4/dialog.css
dist/dialog/ds6/dialog.css
dist/drawer/ds4/drawer.css
docs/_includes/common/dialog.html
src/less/dialog/base/dialog.less
src/less/drawer/ds4/drawer.less

* Updated dialog to support end text and center header. Added for ds6 only because DS4 close button is always on right. 
* Also fixed DS4 drawer to show handle
* For dialog end text, added example to show it. 
#1115
#1105

Updated dialog to support end text and DS4 drawer handle

---

dist/breadcrumbs/ds4/breadcrumbs.css
dist/breadcrumbs/ds6/breadcrumbs.css
src/less/breadcrumbs/base/breadcrumbs.less

Fixes #1112
Just a simple cascade fix so that visited links get the correct colour (blue) on hover & focus. I could have made it more specific with `a:visited:hover`, but I prefer to use the natural cascade wherever possible, so it required the stylelint disable.

Breadcrumbs: fix hover colour #1112

---

dist/notice/ds4/notice.css
dist/notice/ds6/notice.css
src/less/notice/base/notice.less

Chrome adds extra margins to headings in notices. They should remain 16px regardless of the a11y tag passed to notice.
https://github.com/eBay/skin/issues/1143

Reset vendor margins for headings in notice

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less

Controls are centered according to the main content. However the carousel__list has a padding-bottom of 10 in order to support the scrollbar. This makes the controls offcenter. I removed 5px margin in order to center align (1/2 of the offset)
I tried to remove the padding but it looks off with the scrollbar. 
Alignment shown with tools:

Added a -5px margin for controls

---

dist/expand-button/ds4/expand-button.css
dist/expand-button/ds6/expand-button.css
src/less/expand-button/base/expand-button.less
src/less/expand-button/expand-button.stories.js

Added a modifier to center expand button
I used position relative in order to not lose the hight but be able to center the text. 
Added some padding so buttons do not overlap in case the button is small.
Also added RTL styles

Added center modifier for expand button

---

dist/dialog/ds4/dialog.css
src/less/dialog/ds4/dialog.less

Removed a margin in DS4 dialog header which was causing some extra lines appearing. 
https://github.com/eBay/ebayui-core/issues/1168

Removed extra margin for ds4 dialog

---

dist/combobox/ds4/combobox.css
dist/variables/ds4/combobox-variables.less
src/less/variables/ds4/combobox-variables.less

Fixes #1212
Changes combobox text color from #333 to #555. This matches textbox and select.
in v11, DS4 is normalised to match DS6, and will use page default text colour (i.e. dark grey, almost black) for all 3 of those modules.

Combobox: match DS4 color with textbox & select #1212

---

dist/fullscreen-dialog/ds4/fullscreen-dialog.css
dist/fullscreen-dialog/ds6/fullscreen-dialog.css
src/less/fullscreen-dialog/base/fullscreen-dialog.less

There is a build failure on ebayui `6.0.0` branch. This PR should fix that. 
Animations were build displayed as block instead of flex for fullscreen dialog.

Dialog fixed fullscreen dialog animations

---

docs/_includes/common/dialog.html

This PR syncronizes the website examples with playbook.
Moved lightbox close button from left to right.
Moved right panel close button from right to left.
Plus some other misc fixes and updates.
I notice the storybook for dialog needs updating too. It's quite a bit out of date. Once these changes are approved, one of us can take care of that.

Website: sync dialog close button with playbook

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/cta-button/ds6/cta-button.css
dist/expand-button/ds4/expand-button.css
dist/expand-button/ds6/expand-button.css
dist/variables/ds4/button-variables.less
dist/variables/ds6/button-variables.less
src/less/button/base/button.less
src/less/expand-button/base/expand-button.less
src/less/expand-button/ds4/expand-button.less
src/less/expand-button/ds6/expand-button.less
src/less/properties/base/expand-button-properties.less
src/less/properties/ds4/expand-button-properties.less
src/less/properties/ds6/cta-button-properties.less
src/less/properties/ds6/expand-button-properties.less
src/less/variables/ds4/button-variables.less
src/less/variables/ds6/button-variables.less

PLEASE SQUASH
Updates button, cta-button and expand buttons with latest dark mode colours.
I started working on expand-button, but didn't fully finish all of its disabled states because I started to see this code smell: #1233 So, even though I'm most likely to do some refactoring, I'd like to get this PR in before I do so.
Note also that I haven't added the "inverted" button variant. That too can be part of the thinking for #1233.

Button: component-level updates #1157

---

dist/drawer-dialog/ds4/drawer-dialog.css
dist/drawer-dialog/ds6/drawer-dialog.css
dist/fullscreen-dialog/ds4/fullscreen-dialog.css
dist/fullscreen-dialog/ds6/fullscreen-dialog.css
dist/lightbox-dialog/ds4/lightbox-dialog.css
dist/lightbox-dialog/ds6/lightbox-dialog.css
dist/panel-dialog/ds4/panel-dialog.css
dist/panel-dialog/ds6/panel-dialog.css
dist/toast-dialog/ds4/toast-dialog.css
dist/toast-dialog/ds6/toast-dialog.css
src/less/drawer-dialog/base/drawer-dialog.less
src/less/fullscreen-dialog/base/fullscreen-dialog.less
src/less/lightbox-dialog/base/lightbox-dialog.less
src/less/panel-dialog/base/panel-dialog.less
src/less/toast-dialog/base/toast-dialog.less

Changed offset to be negative 8px. This way icons are `40px` and the selector box is now small
Also updated toast button
(I looked at mini dialog button and it looks fine imo, but let me know if I missed something)
For these I was on another browser which made them render differently than chome does.

Added negative offset and fixed toast dialog button

---

dist/icon-button/ds4/icon-button.css
dist/icon-button/ds6/icon-button.css
dist/pagination/ds4/pagination.css
dist/pagination/ds6/pagination.css
docs/_includes/common/pagination.html
pagination.browser.json
pagination.js
pagination[ds-4].js
src/less/icon-button/base/icon-button.less
src/less/pagination/base/pagination.less
src/less/pagination/stories/button-cascade.stories.js
src/less/pagination/stories/buttons.stories.js
src/less/pagination/stories/link-cascade.stories.js
src/less/pagination/stories/links.stories.js
src/less/properties/base/pagination-properties.less
src/less/properties/ds6/pagination-properties.less
src/less/variables/ds4/pagination-variables.less
src/less/variables/ds6/pagination-variables.less

Similar to the changes in dialog close button, I have updated pagination paddle buttons to directly use the icon button classes. This means they inherit all of the light & dark mode properties of icon button, and we get a reduction in duplicated css and properties sent to the client.
CoreUI will need its markup updating accordingly.

Pagination: use icon-button classes on paddles

---

.storybook/main.js
package.json
yarn.lock

So in the storybook config we are not running autoprefixer on our less files. This makes it so some browser specific styles are not being generated. One of these is `--webkit-appearance` which safari uses for select. 
This is actually an existing issue and is present in production for safari. 
The good news is this only affects the storybook since the other bundles have the autoprefixer properly run.
This changes changes webpack loader to also run autoprefixer on all `less` files, so storybook should work properly now.
#1259

Added autoprefixer for storybook (fixes select on safari)

---

dist/lightbox-dialog/ds4/lightbox-dialog.css
dist/lightbox-dialog/ds6/lightbox-dialog.css
docs/_includes/common/lightbox-dialog.html
src/less/lightbox-dialog/base/lightbox-dialog.less

Added header class again but changed dialog-mini flex to be `row-reverse`. This is so header comes first in dom (as well as close button), and then content even though it's on the right side of the dialog.
Also added padding-top: 8px to align the close button to the top. This will be picked up in mweb (but not dweb).

Added header class with flex direction of row-reverse for dialog-mini

---

dist/icon/ds4/icon.css
dist/variables/ds4/icon-variables.less
src/less/variables/ds4/icon-variables.less

Changed the carousel next/prev icons to have the same dimensions as the small chevrons. This fits them nicer in the field.
We could also change the icon, but this icon still is the DS4 chevron.

Changed ds4 carousel icons to use DS4 dimensions

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/cta-button/ds4/cta-button.css
dist/cta-button/ds6/cta-button.css
dist/expand-button/ds4/expand-button.css
dist/expand-button/ds6/expand-button.css
dist/mixins/utility/utility-mixins.less
dist/variables/ds4/button-variables.less
dist/variables/ds6/button-variables.less
docs/_includes/common/button.html
src/less/button/base/button.less
src/less/button/stories/button/base/base.stories.js
src/less/cta-button/base/cta-button.less
src/less/cta-button/stories/cta-button.stories.js
src/less/expand-button/base/expand-button.less
src/less/expand-button/stories/expand-button.stories.js
src/less/mixins/utility/utility-mixins.less
src/less/variables/ds4/button-variables.less
src/less/variables/ds6/button-variables.less

Fixes #1272
This provides a couple of ways for legacy pages to opt into the old, wider button style when they upgrade to v11:
1. Via a new `.btn--wide` modifier
2. Via a new `--button-padding-horizontal` custom property

Button: added backwards compatibility for DS4 button width

---

docs/_includes/common/flags.html
docs/_includes/common/section-header.html
docs/index.html

Quick PR to update version numbers to new system. For rounded modules that are still hidden behind a flag, I have set the semantic version as one minor version lower than displayed in playbook.
I would like to display these numbers on the old legacy (ds4) page too, but that would require some shuffling around of things in Jekyll (because the variables currently live in the ds6 page only).
This can be squashed and merged directly to master.

Website: updated design system version numbers

---

browser.json
dist/legacy-textbox/ds4/legacy-textbox.css
dist/legacy-textbox/ds6/legacy-textbox.css
legacy-textbox.browser.json
legacy-textbox.js
legacy-textbox[ds-4].js
scripts/develop-module_proper/code-generators/style-generator.js
src/less/legacy-textbox/base/legacy-textbox.less
src/less/legacy-textbox/ds4/legacy-textbox.less
src/less/legacy-textbox/ds6/legacy-textbox.less
src/less/legacy-textbox/legacy-textbox.stories.js

Added a legacy module, this will basically provide the old styles for floating label and textbox.
* Added all variables in the module itself so it's easy to remove.
* These should override the other styles as long as it's loaded last
* Also fixed the generator module to apply the correct paths and modules.

Added legacy textbox module with underline and old floating label

---

dist/legacy-textbox/ds4/legacy-textbox.css
dist/legacy-textbox/ds6/legacy-textbox.css
src/less/legacy-textbox/base/legacy-textbox.less

After loading the floating label on ebayui I noticed two issues which are fixed here.
* Removed all padding to align textbox to the center not to the bottom as in the new floating way
* Forced focus background to be transparent on legacy

Fixed padding and backgorund overrides for legacy underline textbox

---

dist/legacy-textbox/ds4/legacy-textbox.css
dist/legacy-textbox/ds6/legacy-textbox.css
package-lock.json
src/less/legacy-textbox/base/legacy-textbox.less
src/less/legacy-textbox/legacy-textbox.stories.js

While testing on ebayui I found a couple more issues.
Fixed transparent background to be white like it was in the previous version.
Also removed a generated storybook file.

Cleaned up background color overrides for legacy-textbox

---

dist/infotip/ds4/infotip.css
dist/infotip/ds6/infotip.css
src/less/infotip/base/infotip.less

Added `flex-shrink` to infotip close button
We can add it to `icon-btn` next major version
#1306

Added flex-shrink to infotip close button

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/cta-button/ds4/cta-button.css
dist/cta-button/ds6/cta-button.css
dist/variables/ds4/button-variables.less
dist/variables/ds4/cta-button-variables.less
dist/variables/ds6/button-variables.less
dist/variables/ds6/cta-button-variables.less
docs/_includes/common/button.html
src/less/button/base/button.less
src/less/cta-button/base/cta-button.less
src/less/variables/ds4/button-variables.less
src/less/variables/ds4/cta-button-variables.less
src/less/variables/ds6/button-variables.less
src/less/variables/ds6/cta-button-variables.less

Design system updates:
* min-width changed from auto to 128px for rounded buttons.
* for icon-only buttons, sets min-width to auto
* horizontal padding changed from 16px to 20px for cta buttons
I haven't changed legacy buttons to have a min-width because I'm not sure it makes sense for non-rounded buttons (plus, we would be reverting the breaking changes we made in v11, which might be kind of annoying for teams!). Legacy pages can make use of the `btn--wide` modifier.
Closes #1324
Button spec
DS6
DS4 (no changes)

Button: set min-width #1324

---

docs/_includes/common/pagination.html
src/less/pagination/stories/dots.stories.js

* Simply added pagination with dots examples.
For dots I used ascii keycode for three dots. Screen reader read it as `ellipsis` which is good.
I also added `aria-disabled` since the button is not active or does anything.
#1337

Added pagination stories and examples for dots

---

dist/breadcrumbs/ds4/breadcrumbs.css
dist/breadcrumbs/ds6/breadcrumbs.css
src/less/breadcrumbs/base/breadcrumbs.less

In ebayui for some reason there is 0 space between `<a>` tag and `<svg>` tag. In skin there is 2px spacing, but no styles to justify that spacing. There is probably something loaded on skin that isn't loaded on ebayui to make that change. In inspector there's no difference even in computed styles.
Either way, by making the `li` container flex in skin this makes both skin and ebayui in sync and forces there to be 0 spacing like in ebayui. In order to counteract that spacing, I made margin-left to be 2 more px which should look like before. 
https://github.com/eBay/ebayui-core/issues/1319

Added flex li container for breadcrumbs to align correctly on all pages

---

dist/svg/ds6/icons.svg
docs/_includes/ds6/symbols.html
docs/static/ds6/icons.svg
src/svg/ds6/icons.svg

Changed `breadcrumb` viewport to be in line with `chevron-right-small`
https://github.com/eBay/skin/issues/1352

Changed breadcrumb icon to use 8 width viewport

---

dist/checkbox/ds4/checkbox.css
dist/checkbox/ds6/checkbox.css
dist/radio/ds4/radio.css
dist/radio/ds6/radio.css
src/less/checkbox/base/checkbox.less
src/less/checkbox/stories/checked.stories.js
src/less/radio/base/radio.less
src/less/radio/stories/checked.stories.js

Fixed height on span container for svg to match height of svg.
This was applied in radio and in checkbox.
Closes #1318

Focus outline was too tall for radio and checkbox with multi line label

---

dist/progress-stepper/ds4/progress-stepper.css
dist/progress-stepper/ds6/progress-stepper.css
dist/variables/ds4/progress-stepper-variables.less
dist/variables/ds6/progress-stepper-variables.less
docs/_includes/common/progress-stepper.html
src/less/progress-stepper/base/progress-stepper.less
src/less/variables/ds4/progress-stepper-variables.less
src/less/variables/ds6/progress-stepper-variables.less

Fixed issues with progress-stepper by adding mweb and dweb styles as well as making circle bolded
https://github.com/eBay/skin/issues/1358

Added mobile/desktop styles for progress stepper

---

scripts/generate-imports/index.js

Some issues with prepublish script
* Was adding `.css` twice. 
* Was not adding `.js`
Basically cleaned up some of the extension adding, so it will add `css` by default for root module which should be looking up in `dist` and other ones it will pull based on the file extension.

Fixed prepublish script to correctly add extensions

---

dist/toast-dialog/ds4/toast-dialog.css
dist/toast-dialog/ds6/toast-dialog.css
docs/_includes/common/lightbox-dialog.html
docs/_includes/common/snackbar-dialog.html
docs/_includes/common/toast-dialog.html
src/less/toast-dialog/base/toast-dialog.less

Fixes #1375
Secondary button was missing a background-colour for focus/hover state.
I also took the opportunity to rejig some of the documentation for toast & snackbar, and added an example of toast with secondary action.
I also noticed that snackbar transitions don't appear to be working. So that can be investigated separately.
Before
After

style(toast-dialog): fix hover/focus color #1375

---

package-lock.json
package.json

Adds [commitlint](https://github.com/conventional-changelog/commitlint) to the [husky](https://typicode.github.io/husky/#/) commit-msg hook.
NOTE: I am following the Husky v4 syntax which was added with the recent Prettier related changes & lint-staged. @austingardner Was there a reason for not using v5 and its syntax? Concerns over open source license perhaps?
Sample error when I tried to commit this change with message of "foo":

build: add commitlint

---

dist/lightbox-dialog/ds4/lightbox-dialog.css
dist/lightbox-dialog/ds6/lightbox-dialog.css
src/less/lightbox-dialog/base/lightbox-dialog.less

There was a case where shrinking the browser caused the mini lightbox window to lose responsiveness and its edges.
Cutting out max-width solves the problem. Closes #1301. 
#1301

Mini Lightbox Spacing Fix

---

dist/infotip/ds4/infotip.css
dist/infotip/ds6/infotip.css
src/less/infotip/base/infotip.less

Adds margin to infotip__content class. Fixes #1385

Infotip Spacing Fix

---

dist/infotip/ds4/infotip.css
dist/infotip/ds6/infotip.css
src/less/infotip/base/infotip.less

Applies the margin-left to `button.infotip__close` and `infotip__close` instead of the previous class, `.infotip .icon-btn`
Previous infotip changed the spacing of the icon... this will be more specific to just the icon close. 
closes #1390

Infotip Spacing Patch

---

scripts/generate-imports/index.js

Changed a small section in the generate-imports script to correct the svg file which had an incorrect file extension. 
closes #1394

1394 SVG File incorrect file extension

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less
src/less/carousel/stories/carousel.stories.js

Added `carousel--hidden-scrollbar` option.
Did not add documentation, but did add a story for it
Copied code from: https://github.com/eBay/skin/pull/1000/files#diff-b09805b2dadcb72d0f450bf2288ad80da20645f864bd78375090bd2838232130L188-L199 which was the same code we had to hide the scrollbar initially.
https://github.com/eBay/skin/issues/1431

feat(carousel): added option to hide scrollbar

---

docs/_includes/common/checkbox.html
docs/_includes/common/field.html
docs/_includes/common/radio.html

This is a documentation change only. It adds instructions on how to use `field__group` wrapper to ensure vertical alignment of fields and their label when none-default font-sizes or radio/checkbox sizes are used. 
In future we can revisit the field module to see if it makes sense to make this the default behaviour of field without requiring an additional element. I know we can't do it now as it breaks the way a couple of the field variations work.

docs(field): add instructions for field__group #1399

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
dist/mixins/utility/utility-mixins.less
dist/utility/ds4/utility.css
dist/utility/ds6/utility.css
src/less/mixins/utility/utility-mixins.less

So our old image layering would only add a background color. However for non transparent images this would not work.
As per playbook, there is a layer placed ontop of the image with a slight grey. This change basically makes it to add a layer on top of the whole image.
https://github.com/eBay/ebayui-core/issues/1362
Before:
After:

fix(imageTreatment): added ::after element to cover whole image

---

dist/page-notice/ds4/page-notice.css
dist/page-notice/ds6/page-notice.css
dist/section-notice/ds4/section-notice.css
dist/section-notice/ds6/section-notice.css
src/less/page-notice/base/page-notice.less
src/less/section-notice/base/section-notice.less

There was a `padding-left: 0` already there, replaced that with `padding-left: 16px` for large screens to add spacing.
Also added it to page notice
https://github.com/eBay/skin/issues/1438
Old:
New:

fix(notice): added 16px padding-left for button spacing

---

dist/fullscreen-dialog/ds4/fullscreen-dialog.css
dist/fullscreen-dialog/ds6/fullscreen-dialog.css
dist/lightbox-dialog/ds4/lightbox-dialog.css
dist/lightbox-dialog/ds6/lightbox-dialog.css
dist/panel-dialog/ds4/panel-dialog.css
dist/panel-dialog/ds6/panel-dialog.css
src/less/mixins/dialog/base/dialog-mixins.less

Added the 24px padding to dialog footer on large override. This overrides the 16px margin already there.
https://github.com/eBay/skin/issues/1442
Before:
After:

fix: added large-gutter size to dialog footer

---

dist/button/ds4/button.css
dist/button/ds6/button.css
src/less/button/base/button.less

Fixes #1322 
Adds a max height to SVG icon to avoid HUGE buttons in IE11.
We can probably refactor and simplify this aspect of the button code in next major version when we drop IE completely.

fix(button): add max-height to svg icon #1322

---

dist/panel-dialog/ds4/panel-dialog.css
dist/panel-dialog/ds6/panel-dialog.css
src/less/panel-dialog/base/panel-dialog.less

Looks like this padding came from dialog refactor. It doesn't seem needed on panel dialog. 
https://github.com/eBay/skin/issues/1455

fix: removed padding-bottom: 15vh from panel-dialog

---

less.browser.json
less.less
less[ds-4].less

There was a refactor which removed border-radius-variables from typography. However less-imports do not have border-radius-variables so this was causing an issue.

fix(imports): added border-radius-variables to less imports

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less

There's a weird bug where the overflow on the horizontal is shown and the scrollbar shows up. This fix is supposed to resolve that.
Before
After

fix(carousel): hide vertical scrollbar

---

scripts/generate-bundle.js

In some cases this css would be executed in autoprefixer and strip out some needed lines. 
Changed this in order to skip all autoprefixing by adding a snippet to the beginning of the file and end to ignore running autuoprefixer since it was already run on less compilation.

fix(generate-bundle): added skip autoprefixer for file

---

dist/floating-label/ds4/floating-label.css
dist/floating-label/ds6/floating-label.css
src/less/floating-label/base/floating-label.less

Removed margin from floating label.
closes #1481

fix(floating-label): dropped margin

---

dist/textbox/ds4/textbox.css
dist/textbox/ds6/textbox.css
src/less/textbox/base/textbox.less
src/less/textbox/stories/icon.stories.js

Vertically centered icon button in large textbox scenario. Added stories.

fix(textbox): vertically centered icon button with large textbox

---

dist/video/ds4/video.css
dist/video/ds6/video.css
src/less/video/base/video.less

* Added play icon css changes so that both the icon in the shaka player and on our overlay do not jump
* Fixed overlay to have a background color with opacity (should be good for color contrast hopefully)

fix(video): changed play icon size and fixed error container

---

dist/video/ds4/video.css
dist/video/ds6/video.css
src/less/video/base/video.less

* Fixed size of video to be 100% of container. Container will resize in ebayui (https://github.com/eBay/ebayui-core/issues/1447)
* Fixed shaka controls to have a transparent grey background with opacity of `0.7` (https://github.com/eBay/ebayui-core/issues/1437)
* Fixed issue with padding on report icon shrinking. Changed to margin

fix(video): fixed icon size, controls color contrast, and container size

---

src/less/progress-bar/stories/progress-bar.stories.js

Removed `min` from `progress-bar` examples, as it is not a valid HTML attribute for the `<progress/>` tag.
https://github.com/eBay/skin/issues/1514

fix(progress-bar): remove min attribute from stories #1514

---

dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
dist/icon-button/ds4/icon-button.css
dist/icon-button/ds6/icon-button.css
dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
dist/mixins/utility/utility-mixins.less
docs/_includes/common/badge.html
docs/_includes/common/icon-button.html
docs/_includes/common/menu.html
src/less/badge/base/badge.less
src/less/icon-button/base/icon-button.less
src/less/menu-button/base/menu-button.less
src/less/menu-button/stories/menu-button.stories.js
src/less/menu/base/menu.less
src/less/menu/stories/menu/misc.stories.js
src/less/mixins/utility/utility-mixins.less

Close #1493 
Updates badge, icon-button, menu & menu-button with latest badge styles from evo.
There's a little bit of hackery with padding to get the text lining up right. Some numbers can look a little uncentered across different browsers. The outer padding when number grows to 2 digit isn't exactly in line with the designs either. I think this is about the most precision we can get though without going and adding a new flex element inside the badge (i.e. a nested span). I'm not opposed to doing that if we have to.
Also, I'll probably come back and fine tune the position of the badge on the icon button. The `top` and `left` might need a little adjustment.
I also had to add a new `menu__item--badged` modifier.  This will need adding in coreui.

feat(badge): evo updates #1493

---

dist/icon-button/ds4/icon-button.css
dist/icon-button/ds6/icon-button.css
dist/pagination/ds4/pagination.css
dist/pagination/ds6/pagination.css
docs/_includes/common/pagination.html
src/less/icon-button/base/icon-button.less
src/less/pagination/base/pagination.less
src/less/pagination/ds4/pagination.less
src/less/pagination/ds6/pagination.less
src/less/pagination/stories/dots.stories.js

This PR updates the colors, and changes the current item from having a full border to a bottom border only.
There is one hover color not quite right in dark mode. I will address it in Part 2. Also, I may need to reduce the spacing between the digits and the bottom-border.
DS4 is now normalized with DS6 (i.e. the only difference now being the color palette/primitives).

feat(pagination): evo updates part 1 (#1435)

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less

Just needed to add `scrollbar-color` in a couple places to fix. 
closes #1517

fix(carousel): scrollbar on windows firefox shows only on hover

---

scripts/develop-module_proper/code-generators/style-generator.js
scripts/generate-imports/index.js

This PR updates the build script to output esm imports for all of the top level javascript files, and has the `browser.json` files point to the top level `css` instead of js.
This change is done specifically to improve support for [`vite`](https://vitejs.dev/) which has issue with commonjs imports for styles.
The purpose of the top level js files was to improve webpack support which already supports esm, so this shouldn't necessarily be a breaking change.

Use esm for js entries

---

dist/signal/ds4/signal.css
dist/signal/ds6/signal.css
src/less/signal/base/signal.less

Centers the text in the signal, which was off in Chrome 92 and Firefox, at least in Mac. This isn't a 100% solution but gets us 90% there.
closes #1525

fix(signal): used flex and inner span to center text

---

scripts/generate-imports/index.js

Adds a missing lasso `requireRemap` for the top level `less.less`.
Resolves #1535

fix: add less.less to requireRemaps in browser.json

---

scripts/generate-imports/config.json
scripts/generate-imports/index.js

There was an issue with imports when linking to ebayui that lasso cannot resolve `css` imports from a js file. 
Changed the code to basically revert back to the old way of doing things (while keeping the new changes we added, like mjs)

fix(generate-imports): reverted css imports

---

dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
dist/filter-button/ds4/filter-button.css
dist/filter-button/ds6/filter-button.css
dist/filter-menu-button/ds4/filter-menu-button.css
dist/filter-menu-button/ds6/filter-menu-button.css
dist/mixins/filter-button/base/filter-button-mixins.less
dist/mixins/typography/base/typography-mixins.less
dist/primitives/base/primitives.less
dist/section-title/ds4/section-title.css
dist/section-title/ds6/section-title.css
dist/signal/ds4/signal.css
dist/signal/ds6/signal.css
dist/typography/ds4/typography.css
dist/typography/ds6/typography.css
src/less/badge/base/badge.less
src/less/eek/base/eek.less
src/less/global/base/global.less
src/less/mixins/filter-button/base/filter-button-mixins.less
src/less/mixins/typography/base/typography-mixins.less
src/less/primitives/base/primitives.less
src/less/section-title/base/section-title.less
src/less/signal/base/signal.less

Just removes a bunch of redundant font-family styles that we no longer need now that Market Sans is the default for the entire page.

chore: remove redundant font-family styles

---

dist/infotip/ds4/infotip.css
dist/infotip/ds6/infotip.css
dist/mixins/bubble/base/bubble-mixins.less
dist/tooltip/ds4/tooltip.css
dist/tooltip/ds6/tooltip.css
dist/tourtip/ds4/tourtip.css
dist/tourtip/ds6/tourtip.css
src/less/mixins/bubble/base/bubble-mixins.less

* Had `min-width` which was taking prescedence in width of infotip/tooltip. By removing that and adding `width: max-content` it will stretch out correctly. Browser support is good (no ie)
https://github.com/eBay/skin/issues/1559

feat(bubble): added width: max-content to shink correctly

---

dist/floating-label/ds4/floating-label.css
dist/floating-label/ds6/floating-label.css
docs/_includes/common/floating-label.html
src/less/floating-label/base/floating-label.less

* Added support for select floating-label. 
* Added docs for select floating label
https://github.com/eBay/skin/issues/1561
Required change: https://github.com/makeup/makeup-js/pull/40

feat(floating-label): added support for select

---

dist/badge/ds4/badge.css
dist/badge/ds6/badge.css
dist/icon-button/ds4/icon-button.css
dist/icon-button/ds6/icon-button.css
dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
src/less/badge/base/badge.less
src/less/icon-button/base/icon-button.less
src/less/menu-button/base/menu-button.less

Changed some styles in badge (added flex, removed box-border, changed padding to be equal)
On the large one the text is very close to the sides, but this can only be fixed by adding an unequal padding, causing the badge to not be a circle. If that's fine I can change it.

fix(badge): changed styles to align correctly

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
src/less/carousel/base/carousel.less

Fixes carousel issue on Firefox where the carousel wouldn't scroll to the end. 
I have one question on this - how do I turn off the prefixer for webkit and ms? (We could probably drop the ms prefixes as well because we no longer support IE.) The prefixer added the webkit-scroll and ms-scroll which I don't want here.
UPDATE: tested on Edge, so works with chromium
closes #1593 , [Core UI 1513](https://github.com/eBay/ebayui-core/issues/1513)

fix: carousel firefox now scrolls to last slide

---

dist/carousel/ds4/carousel.css
dist/carousel/ds6/carousel.css
dist/mixins/utility/utility-mixins.less
dist/utility/ds4/utility.css
dist/utility/ds6/utility.css
docs/custom-styles.html
src/less/carousel/base/carousel.less
src/less/carousel/stories/carousel.stories.js
src/less/mixins/utility/utility-mixins.less
src/less/utility/base/utility.less

Adds Image Treatment Large mixin for images larger than 40px; adds border-radius 16px to them; adds border-radius 8px to the image treatment class; dropped border radius from demo classes.
closes #1451

feat(image-treatment): ds evo updates #1451

---

dist/section-title/ds4/section-title.css
dist/section-title/ds6/section-title.css
docs/_includes/section-title.html
src/less/section-title/base/section-title.less
src/less/section-title/stories/deprecated.stories.js
src/less/section-title/stories/rtl.stories.js
src/less/section-title/stories/section-title.stories.js

Adjusted font size for evo.
One issue I have is with the icons - they don't want to show up in a new example I made. See screenshot. @ianmcburnie do you know why I wouldn't be able to use the icon like that? These SVGs are giving me all kinds of trouble. HTML from example I was attempting looks like this: 
```
<div class="demo">
<div class="demo__inner">
<div class="section-title">
<div class="section-title__title-container">
<h2 class="section-title__title">Today’s Deals – All With Free Shipping</h2>
</div>
<button class="icon-btn" type="button" aria-label="go to deals">
<svg class="icon icon--arrow-right" focusable="false" width="24" height="24">
<use xlink:href="icons.svg#icon-arrow-right"></use>
</svg>
</button>
</div>
</div>
</div>
```    
closes #1454

feat(section-title): adjusted font size

---

dist/progress-stepper/ds4/progress-stepper.css
dist/progress-stepper/ds6/progress-stepper.css
docs/_includes/progress-stepper.html
src/less/progress-stepper/base/progress-stepper.less

Fixed heading structure for html code. Left it intact for examples
Structure should be: 
`h2` -> stepper section title
`h3` -> each stepper type title
`h4` -> stepper example title
`h5` -> each step title
Added styles to force font sizes for headers so it matches design
Also found a spacing problem with some width that was fixed
https://github.com/eBay/skin/issues/1618

fix(progress-stepper): fixed heading strcture

---

dist/icon-button/ds4/icon-button.css
dist/icon-button/ds6/icon-button.css
docs/_includes/textbox.html
src/less/icon-button/base/icon-button.less

added the outline offset and updated the skin website with the `icon-btn--transparent` class
closes #1625

fix(textbox): icon button outline no longer goes past textbox border

---

dist/progress-stepper/ds4/progress-stepper.css
dist/progress-stepper/ds6/progress-stepper.css
src/less/progress-stepper/base/progress-stepper.less

By changing all SVGs to have `role=img` this caused a selector to trigger which is only intended to `span[role="img"]` Changed the selector to only target spans
https://github.com/eBay/skin/issues/1630

fix(progress-stepper): added span to [role=img] selector

---

dist/lightbox-dialog/ds4/lightbox-dialog.css
dist/lightbox-dialog/ds6/lightbox-dialog.css
src/less/lightbox-dialog/base/lightbox-dialog.less

Initially when we had a non outlined button we had a negative outline-offset to make the focus ring closer to the icon. Now since we have a background it's not needed anymore. 
#1636

fix(lightbox-dialog): removed outline-offset from button 

---

dist/button/ds4/button.css
dist/button/ds6/button.css
src/less/button/base/button.less

Since partially disabled relies on `aria-disabled` to disable hover, this code was picking up hover together with `aria-live`. Changed it so they're separate checks.
https://github.com/eBay/skin/issues/1637

fix(button): changed aria-live to be separate form aria-disabled hover

---

dist/legacy-theme/ds4/legacy-theme.css
dist/legacy-theme/ds6/legacy-theme.css
src/less/legacy-theme/base/legacy-theme.less

When theme on ds4 switches to dark-mode, styles are not being applied. The issue was due to the `prefers-color-scheme: light`.
Removed that query and have styles apply at all times.
https://github.com/eBay/skin/issues/1661

fix(legacy-theme): removed perfers-color-scheme light

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/cta-button/ds4/cta-button.css
dist/cta-button/ds6/cta-button.css
dist/expand-button/ds4/expand-button.css
dist/expand-button/ds6/expand-button.css
dist/mixins/button/base/button-mixins.less
dist/progress-spinner/ds4/progress-spinner.css
dist/progress-spinner/ds6/progress-spinner.css
docs/_includes/button.html
src/less/mixins/button/base/button-mixins.less
src/less/progress-spinner/base/progress-spinner.less

When we changed the progress spinner syntax last minor version, we forgot to check loading button. Seems like there was a major wobble with that.
* Thanks to @ArtBlue , added the CSS styles for SVG to force the width to make it not wobble.
* I had to change some margin on the button mixin when it's an `only-child` (so the negative margins don't get applied)
* Also updated docs 
https://github.com/eBay/skin/issues/1665

fix(progress-spinner): made progress spinner work in loading button

---

dist/icon-button/ds4/icon-button.css
dist/icon-button/ds6/icon-button.css
src/less/icon-button/base/icon-button.less

* Added `min-width` to icon-button
https://github.com/eBay/skin/issues/1632

fix(icon-button): added min-width so it does not shrink

---

dist/combobox/ds4/combobox.css
dist/combobox/ds6/combobox.css
dist/select/ds4/select.css
dist/select/ds6/select.css
dist/textbox/ds4/textbox.css
dist/textbox/ds6/textbox.css
dist/tokens/base/tokens.less
src/less/combobox/base/combobox.less
src/less/select/base/select.less
src/less/textbox/base/textbox.less
src/less/tokens/base/tokens.less

* Fixed textbox, select, and combobox to all have black focus borders
https://github.com/eBay/skin/issues/1655

fix(textbox): changed border-color to be black on all inputs

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/tokens/base/tokens.less
src/less/button/base/button.less
src/less/tokens/base/tokens.less

Changed secondary button to be transparent color by default
Changed it also for DS4. If they use legacy build, it will replace this color with grey
https://github.com/eBay/skin/issues/1657

fix(button): changed secondary to be transparent

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/mixins/utility/utility-mixins.less
docs/_includes/main.html
docs/_includes/module-list.html
docs/_includes/split-button.html
docs/index.html
scripts/generate-imports/config.json
src/less/button/base/button.less
src/less/mixins/utility/utility-mixins.less

Adds the split button module to skin - it is a squashed together button with a menu button. 
Followed design spec as closely as possible
closes #1567

feat(split-button): added new split-button to skin

---

dist/button/ds4/button.css
dist/button/ds6/button.css
dist/mixins/utility/utility-mixins.less
src/less/button/base/button.less
src/less/mixins/utility/utility-mixins.less
src/less/split-button/stories/base.stories.js
src/less/split-button/stories/rtl.stories.js
src/less/split-button/stories/size.stories.js

* Added stories for split button
* Had to rework some split button to get it to work for RTL

chore: added stories for split button

---

dist/infotip/ds4/infotip.css
dist/infotip/ds6/infotip.css
src/less/infotip/base/infotip.less

Fixes #1693
Fixed infotip min-width to be 20px

fix(infotip): added min-width of 20px to button

---

dist/drawer-dialog/ds4/drawer-dialog.css
dist/drawer-dialog/ds6/drawer-dialog.css
src/less/drawer-dialog/base/drawer-dialog.less

Fixes [url redacted]PIEACC-547
Fixes the color contrast issue for PIEACC-547
- [* ] I verify the build is in a non-broken state
- [ *] I verify all changes are within scope of the linked issue
- [* ] I tested the UI in all supported browsers
- [ *] I tested the UI in dark mode and RTL mode
- [ *] I added/updated/removed Storybook coverage as appropriate

fix(drawer-dialog): color contrast on handle

---

dist/snackbar-dialog/ds4/snackbar-dialog.css
dist/snackbar-dialog/ds6/snackbar-dialog.css
src/less/snackbar-dialog/base/snackbar-dialog.less

Fixes #1710 
According to figma the border radius for snackbar on mobile should be none. Changed it to be 0 for mobile (but kept it as curved for desktop)
_FYI_ The dot on the bottom left is due to the screenshot on mac. You can see it's also present on the desktop one too.

fix(snackbar): changed mobile border radius to 0

---

dist/menu-button/ds4/menu-button.css
dist/menu-button/ds6/menu-button.css
dist/menu/ds4/menu.css
dist/menu/ds6/menu.css
src/less/menu-button/base/menu-button.less
src/less/menu-button/stories/menu-button.stories.js
src/less/menu/base/menu.less

Fixes #1717
Fixed selector for menu/fake-menu/menu-button/fake-menu-button to target svg with tick-small so that other SVGs do not get overriden
Added a storybook example for icons

fix: made menu button status to only target tick-small

---

docs/_includes/checkbox.html
docs/_includes/radio.html
docs/_includes/star-rating-select.html
docs/_includes/star-rating.html
docs/_includes/textbox.html
src/less/star-rating-select/star-rating-select.stories.js

Fixes #1730
Somewhere along the line, `aria-hidden` attribute got lost from the checkbox and radio SVG tags. This PR reinstates those and adds them for star rating and star-rating-select too.
I also added a default width and height for star-rating and star-rating-select so that we don't get giant SVGs while in an unstyled state. See screenshots below.
While making these changes I notice that stars SVGs are showing up alongside browser native radio button while in an unstyled state. Not a huge deal, but we should probably use the same trick we do on checkbox and radio to avoid that. Can be done as a separate PR.

fix(docs): add aria-hidden to checkbox & radio SVG #1730

---

dist/checkbox/ds4/checkbox.css
dist/checkbox/ds6/checkbox.css
dist/radio/ds4/radio.css
dist/radio/ds6/radio.css
src/less/checkbox/checkbox.less
src/less/radio/radio.less

Fixes #1709 
Changes the fill color or radios and checkboxes.
The screenshot and Figma included hover state colors but we don't have those tokens/colors and they are handled by opacity changes. I've kept that out of this PR for now until we have more clarity and defined tokens/colors and/or opacity direction.
**Before**
**After**

feat(checkbox|radio): updated fill color

---

dist/legacy-tokens/ds4-light.css
dist/tokens/evo-light.css
docs/static/evo-core.css
docs/static/evo-light.css
src/tokens/evo-core.css
src/tokens/evo-light.css

Changed color neutral 7 for light mode and use the token instead of custom color.

fix(token): changed color neutral 7

---

scripts/generate-imports/config.json

Fixes #1788
Added variables to ignore list in gen imports.
Please verify there are no other modules to ignore in import and that index.js works fine.

fix: added variables to ignore list in gen imports

---

scripts/generate-imports/config.json
scripts/generate-imports/module-builder.js

Fixes #1793
When someone would require `@ebay/skin/tokens` in webpack, they would need to add the `.css` extension. That does not work currently, so I added top level token files as well. (This might need some minor cleanup next major version though).

fix: added top level css files for nested modules

---

dist/infotip/infotip.css
dist/tooltip/tooltip.css
dist/tourtip/tourtip.css
src/less/mixins/private/bubble-mixins.less

Fixes #1792 
Fixes the missing pointer tip arrows for infotip, tooltip, and tourtip. 
The issue was filed specifically for infotip but tooltip and tourtip were also impacted. The same fix proliferates to fix those as well.

fix(infotip): fixed the missing tip arrows

---

dist/link/link.css
src/less/link/link.less

Fixes #1799 
Buttons with the `fake-link` class and the `disabled` attribute were still changing color when hovered.
I did not add an example to the Skin site for this specific case, as it did not seem necessary.

fix: consistent hover color for disabled fake button

---

dist/select/select.css
src/less/select/select.less

Fixes #1787 
Updated the colors for the disabled select component to add differentiation.
Right now, Safari and Chrome are displaying different colors even though they share CSS variables in developer view. This may be worth looking into. Screenshots of each (in dark mode) are attached. 
Chrome: 
Safari:

fix(select): updated colors for disabled

---

dist/textbox/textbox.css
src/less/textbox/textbox.less

Fixes #1775
* Fixed typo of  `color-foreground-secondary`, which should be `color-foreground-on-secondary`
* Set readonly text as the same color, instead of ghost color.

fix(textbox): changed variables to be the correct naming

---

dist/floating-label/floating-label.css
src/less/floating-label/floating-label.less
src/less/floating-label/stories/floating-label.stories.js

Fixes #1722 #1698
* Removed negative margin. Added a smaller size to floating label. This makes it so that it doesn't overlap with any icons (this also affects normal textbox, but in case there's an icon it won't overlap). We might need to revisit floating label to see if we can add a "with-icon" modifier. But that should be for future 
* Added a background-color to match textbox background for floating-label. This is so that textarea's text does not overlap with label when scrolling

fix(floating-label): added mask and spacing changes

---

dist/drawer-dialog/drawer-dialog.css
dist/fullscreen-dialog/fullscreen-dialog.css
dist/lightbox-dialog/lightbox-dialog.css
dist/panel-dialog/panel-dialog.css
docs/_includes/fullscreen-dialog.html
docs/_includes/lightbox-dialog.html
docs/_includes/panel-dialog.html
src/less/fullscreen-dialog/fullscreen-dialog.less
src/less/fullscreen-dialog/stories/fullscreen-dialog.stories.js
src/less/lightbox-dialog/lightbox-dialog.less
src/less/lightbox-dialog/stories/lightbox-dialog.stories.js
src/less/mixins/private/dialog-mixins.less
src/less/panel-dialog/panel-dialog.less
src/less/panel-dialog/stories/panel-dialog.stories.js

Fixes #1734 and #1708
* Updated panel-dialog to have a max-width. Made fullscreen panel dialog to take up the whole space.
* Updated full-screen dialog to have an animation from right to left. 
* Updated all dialogs (lightbox, fullscreen, and panel) to be 16px padding. Fixed spacing for all headings. All close buttons are now on right side. (kept backwards compatibility)
* Fixed close button to be 32x32 as per spec. Switched out icon to be close-small
* Added footer support to all dialogs and cleaned up footer code.
* A lot of old code is deprecated and unused. We should remove next major

feat(dialogs): updated panel, fullscreen, and lightbox with new spec

---

dist/filter-button/filter-button.css
dist/filter-menu-button/filter-menu-button.css
src/less/mixins/private/filter-button-mixins.less

Fixes #1813 
* Added `font-family: inherit` to filter mixins

fix(filter): added font-family:inherit to mixin

---

dist/legacy-tokens/ds4-light.css
dist/tokens/evo-light.css
src/tokens/evo-light.css

Fixes #1818
* Changed page notice color to be green 6

fix(page-notice): changed confirm color to green 6

---

dist/floating-label/floating-label.css
dist/select/select.css
src/less/floating-label/floating-label.less
src/less/select/select.less
src/less/select/stories/floating-label.stories.js

Fixes #1819
* Select did not have a white background when focused. I changed that focus color background. This fixes the issue with floating label changing color on focus
* I also remove the padding from the top. This caused the focus ring to be off. This will make a bit of the text bleed through on textarea on the top a bit, but it is better to fix this and have the textarea bleed text through the top (it isn't as bad as before though)
* Added floating label test cases to select. Unfortunately there is no JS on storybook, so won't simulate it correctly on focus/unfocus.

fix(floating-label): changed select background to white on focus

---

dist/textbox/textbox.css
src/less/textbox/textbox.less

Fixes #1820 
Removed the padding from textbox
So the focus rings were looking odd without padding. I changed it to be underline text like we have for select borderless.

fix(textbox): removed padding from readonly

---

dist/floating-label/floating-label.css
src/less/floating-label/floating-label.less

Reverts #1698
* We added a background color to floating label to obscure text behind it. However this is causing a lot of issues especially in the case where chrome adds autocomplete to a field. There is no way to resolve that issue on our end since it's a browser problem. To resolve this, this reverts the background color and makes it transparent again.
* Next minor we should add a feature which obscures the background which can be used on textarea (although if textarea has autocomplete on it too it could cause the same issue).

fix: reverted floating-label to be transparent again

---

dist/button/button.css
src/less/button/button.less
src/less/button/stories/button/borderless.stories.js

Fixes #1834
* Disabled styles were taking precedence over the  borderless styles. I added stronger styles for disabled borderless
* Also added storybook examples for borderless and it's variants

fix(button): added styles for diabled borderless

---

dist/infotip/infotip.css
dist/tooltip/tooltip.css
dist/tourtip/tourtip.css
docs/_includes/infotip.html
docs/_includes/lightbox-dialog.html
docs/_includes/tooltip.html
docs/_includes/tourtip.html
src/less/infotip/infotip.less
src/less/lightbox-dialog/lightbox-dialog.less
src/less/mixins/private/bubble-mixins.less
src/less/tooltip/stories/pointer.stories.js
src/less/tooltip/stories/tooltip.stories.js
src/less/tooltip/tooltip.less
src/less/tourtip/tourtip.less

Fixes #1745
* Changed tooltip to match new designs (this includes, tooltip tourtip and infotip)
* Added stories for these

feat(notice): updated notice to use new styles

---

dist/filter-button/filter-button.css
dist/filter-menu-button/filter-menu-button.css
src/less/filter-button/filter-button.less
src/less/filter-menu-button/filter-menu-button.less
src/less/mixins/private/filter-button-mixins.less

Fixes #1737
Updated selected state to reflect changes in the design system
- My `Gemfile.lock` updated automatically so I kept it in this PR, but it may not belong here. I will remove it if necessary.
- I am not totally happy with my solution for reducing padding as I added borders, let me know if you are aware of a cleaner method.

feat: updated filter button select state

---

dist/icon/icon.css
dist/inline-notice/inline-notice.css
dist/page-notice/page-notice.css
dist/section-notice/section-notice.css
dist/variables/variables.less
docs/_includes/inline-notice.html
docs/_includes/page-notice.html
docs/_includes/section-notice.html
src/less/icon/icon.less
src/less/inline-notice/inline-notice.less
src/less/inline-notice/stories/inline.stories.js
src/less/page-notice/page-notice.less
src/less/page-notice/stories/page-notice.stories.js
src/less/page-notice/stories/test.stories.js
src/less/section-notice/section-notice.less
src/less/section-notice/stories/section-notice.stories.js
src/less/section-notice/stories/test.stories.js
src/less/variables/variables.less

Fixes #1806 
Reduced icon dimensions and made spacing adjustments.
* Inline notice and Section notice components were modified as well to match the icon sizes and spacing.
* Percy's still on the blink. Even though I ran the snapshots, the diffs are missing for now. 
Before:
After:
Before:
After:
Before:
After:

feat(page-notice): updated icon sizes, adjusted spacing

---

src/fonts/marketsans/MarketSans-Regular-WebS.css
src/fonts/marketsans/MarketSans-SemiBold-WebS.css

Fixes #1699 
Switching to using swap font loading strategy to ensure font consistency.
Before:
After:

fix(font): use swap loading strategy for font consistency

---

dist/marketsans/marketsans.css
src/fonts/marketsans/MarketSans-Regular-WebS.css
src/fonts/marketsans/MarketSans-SemiBold-WebS.css
src/less/marketsans/marketsans.less

Fixes #1699 
Switching to using swap font loading strategy to ensure font consistency.
Adding on to the missing changes in PR #1845 . See more details in that PR.

fix(font): change swap loading strategy for fonts

---

dist/filter-menu-button/filter-menu-button.css
src/less/filter-menu-button/filter-menu-button.less

Fixes #1848 
This fixes the mismatched color/pseudo padding visual issue.
Before:
After:

fix(filter-menu-button): fixed color issue

---

dist/combobox/combobox.css
dist/listbox-button/listbox-button.css
dist/menu-button/menu-button.css
src/less/combobox/combobox.less
src/less/menu-button/menu-button.less
src/less/mixins/private/dropdown-mixins.less

- Fixes #1827 
- Dropdown menu spanned whole set of buttons when multiple were placed next to each other.
- I modified `dropdown-base` instead of just `menu-button` for expandability, it did not break anything as far as my testing is concerned, so I think it is preferable.

1827 multiple menu buttons

---

dist/button/button.css
src/less/button/button.less
src/less/button/stories/button/borderless.stories.js

- Fixes #1824 
[eBay Figma design system](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=37272%3A40019) states:
> Borderless dropdowns do not have a minimum width since they hug their contents.
Changes have been made to satisfy this statement.

fix(button): removed min-width on borderless variant

---

dist/icon/icon.css
dist/program-badge/program-badge.css
dist/progress-stepper/progress-stepper.css
dist/svg/icon/icon-stepper-current.svg
dist/svg/icons.svg
docs/static/icon/icon-stepper-current.svg
docs/static/icons.svg
src/less/combobox/combobox.less
src/less/icon/generated/icon.less
src/less/menu-button/menu-button.less
src/less/progress-stepper/progress-stepper.less
src/less/progress-stepper/stories/progress-stepper.stories.js
src/svg/icon/icon-stepper-current.svg
src/svg/icons.svg

Fixes #1862
__NOTE__
This PR also includes a fix to storybook. There is an issue where there was an argument passed to a mixin in listbox/combobox which was breaking on storybook start
* As some teams saw the new progress stepper changes, they needed a larger change to support the new syntax. This PR adds the old syntax as an option. We can pass `progress-stepper__items--current` to show the old syntax. This would also be updated in ebayui to add a new `defaultState` as `current` which would show the current item as a bubble and remove the line. 
* Added the old current icon
* I only added storybook examples. I did not show this on docs because we don't want to support this more than a couple of versions
* There was some issue with descending specificity which would require a complete …

feat: added old dot syntax to progress-stepper

---

dist/menu-button/menu-button.css
src/less/menu-button/menu-button.less

Fixes #1864
* Disabled styles were being overriden by base styles since those are nested under `fake-menu-button__items`. I added a stronger selector for disabled styles to override.
* We should probably flatten all the styles, but that should be a later PR.

fix: added stronger selectors to disbled fake-menu-button

---

docs/_includes/field.html

- Fixes #1843 
Modifier already exists to dim disabled field labels, I added it to the labels of disabled components in documentation.

docs: added class to labels of disabled fields

---

dist/section-title/section-title.css
dist/tokens/evo-dark.css
docs/_includes/section-title.html
src/less/section-title/section-title.less
src/less/section-title/stories/rtl.stories.js
src/less/section-title/stories/section-title.stories.js
src/tokens/evo-dark.css

Fixes #1728 
Updates to the section title component to match new specs.
* `<div class="section-title__cta">` that contained an anchor `<a href="https://www.ebay.com" tabindex="-1" aria-hidden="true"><span class="section-title__cta-text">See All</span>` has been simplified to this:
`<a class="section-title__cta" href="https://www.ebay.com">Link</a>`
The link is now an element promoted to a first-level child in the component.
*Token Reference Changes*
* `--color-foreground-secondary` > `--color-neutral-4` > #8f8f8f
* `--color-background-primary` > `--color-neutral-8` > #000
*Dark Mode Background Change*
* As a result of `--color-background-primary` change, dark mode page background color has now been changed to pure black (`#000`).
There are many changes across the board on all the …

feat(section-title): updated section titles to match new specs

---

dist/menu-button/menu-button.css
src/less/cta-button/stories/cta-button.stories.js
src/less/menu-button/menu-button.less

Fixes issues found through Percy on September 20, 2022
- Wide buttons were deprecated but the story was not removed from CTA buttons
- The selector for disabled items in `menu-button` was incorrect

fix: remove deprecated story and modify CSS selector

---

dist/button/button.css
dist/lightbox-dialog/lightbox-dialog.css
src/less/button/button.less
src/less/global/stories/global.stories.js
src/less/lightbox-dialog/lightbox-dialog.less
src/less/lightbox-dialog/stories/lightbox-dialog.stories.js

A couple of fixes found during visual regression.
* removed `Lightbox Dialog: Mini` from storybook as it's no longer needed.
* fixed remaining expanded button issues in `Global`, adding some missing styles that had been left void during removal.

fix(lightbox,global): fixed visual regression issues found by Percy

---

dist/inline-notice/inline-notice.css
dist/page-notice/page-notice.css
dist/section-notice/section-notice.css
src/less/inline-notice/inline-notice.less
src/less/page-notice/page-notice.less
src/less/page-notice/stories/page-notice.stories.js
src/less/section-notice/section-notice.less
src/less/section-notice/stories/section-notice.stories.js

Fixes #1868 
I fixed notices which only had a `<p>` and no `<h2>`.
Before:
After:

fix(page-notice): fixed paragraph-only positioning

---

dist/drawer-dialog/drawer-dialog.css
docs/_includes/drawer-dialog.html
src/less/drawer-dialog/drawer-dialog.less
src/less/drawer-dialog/stories/drawer-dialog.stories.js

Fixes #1743
* Added support for fake-link button in drawer dialog. (As a close button)
* Changed handle CSS to match new designs
* Removed some unused stories which were using the old `drawer` component.

feat(drawer-dialog): added support for text close and updated handle

---

dist/floating-label/floating-label.css
docs/_includes/floating-label.html
src/less/floating-label/floating-label.less
src/less/floating-label/stories/floating-label.stories.js

Fixes #1698
See https://github.com/eBay/skin/pull/1804
We had this fix initially but it caused some issues with the base floating label. This time I added a modifier to use the "opaque" version of the floating label which will correctly obscure text behind it. The intended use of this is for textarea.

feat(floating-label): added floating-label--opaque modifier

---

dist/drawer-dialog/drawer-dialog.css
dist/fullscreen-dialog/fullscreen-dialog.css
dist/lightbox-dialog/lightbox-dialog.css
dist/panel-dialog/panel-dialog.css
src/less/lightbox-dialog/stories/lightbox-dialog.stories.js
src/less/mixins/private/dialog-mixins.less

Fixes #1878
* Added truncation to dialog headers. Added no overflow, whitespace no wrap and text-overflow ellipsis.

feat(dialog): added truncation to dialog headers

---

dist/tourtip/tourtip.css
docs/_includes/tourtip.html
src/less/tourtip/stories/tourtip.stories.js
src/less/tourtip/tourtip.less

Fixes #1744
* Added `tourtip__footer` selector to show tourtip footer.
* Had to modify a bit of the flex code to allow the footer to properly flex to the bottom
* Added an `tourtip__index` container which holds the index. It should flex to the beginning
* If there are only buttons and no index, should flex to the end (there wasn't a case for this, but this is supported)
* The usecase showed a black link for back. I used fake link for now, but it was blue. I believe we will have an upcoming change to change links to be black and allow non-inline links to not have an underline. But for now, I added a selector to support that case in tourtip.

feat(tourtip): added footer

---

dist/listbox-button/listbox-button.css
docs/_includes/listbox-button.html
src/less/listbox-button/listbox-button.less
src/less/listbox-button/stories/base.stories.js
src/less/listbox-button/stories/cascade.stories.js
src/less/listbox-button/stories/dimensions.stories.js

Fixes #1880 
I updated the label color to match new design specs and bolded the values.
To achieve the styling adjustment to labels and values individually, I had to update the DOM and separate the label and text value. While the previous structure had the two inside the same element (`<span class="btn__text">Color: Blue</span>`), the new structure looks like this:
`````html
<span class="btn__contents">
<span class="btn__label">Color: </span>
<span class="btn__text">Blue</span>
</span>
`````
**Before**:
**After**:

feat(listbox-button): separate styling for label and value bolding

---

dist/section-notice/section-notice.css
docs/_includes/section-notice.html
src/less/section-notice/section-notice.less
src/less/section-notice/stories/rtl.stories.js
src/less/section-notice/stories/section-notice.stories.js
src/less/section-notice/stories/test.stories.js

Fixes #1883 
Added new dismiss variation to section notice similar to the one applied to page notice a few weeks back.
I also top-aligned the icons and action elements similar to the implementation for page notice.
The approach I took followed the pattern for page notice since shifting placement of this kind is more easily achieved with a `grid` layout.
New variation with dismiss:

feat(section-notice): added dismiss layout variation and top aligned icons and links

---

dist/drawer-dialog/drawer-dialog.css
dist/tourtip/tourtip.css
dist/variables/variables.less
src/less/drawer-dialog/drawer-dialog.less
src/less/mixins/private/bubble-mixins.less
src/less/mixins/private/dialog-mixins.less
src/less/tourtip/tourtip.less
src/less/variables/variables.less

Based on demo, we updated some spacing.
* Changed tourtip: padding to be 16px all around. Header will be 20px font-size with an 8px bottom margin. Changed border-radius to be 16px. I changed bubble to allow us to pass in those variables since its different from tooltip/infotip (might require refactor)
* Changed drawer dialog to have a top margin of 20px. Also changed dialog mixins to support this.

fix: updated spacing for tourtip and drawer-dialog

---

dist/breadcrumbs/breadcrumbs.css
docs/_includes/breadcrumbs.html
src/less/breadcrumbs/breadcrumbs.less
src/less/breadcrumbs/stories/button-overflow.stories.js
src/less/breadcrumbs/stories/link-overflow.stories.js

Fixes #1896 
Updated breadcrumbs...
1. Added overflow menu based on rules specified in Playbook
2. Removed the scroll-based longer breadcrumbs in lieu of the overflow
3. Changed breadcrumb colors per new specs
Things not completed in this PR:
1. The overflow called for a menu box with a shadow, but since the shadow is part of menu button, we will be completing that in a future issue for proper feature scoping.
Before:
After:

feat(breadcrumbs): added overflow and changed colors

---

dist/cta-button/cta-button.css
src/less/cta-button/cta-button.less
src/less/cta-button/stories/dimensions.stories.js

Fixes #1890 
- Added padding to the CTA large button (also in truncated and fixed-height state) to center align the content.
Large Button
Large Button Truncated
Large Button Fixed height
Large Button
Large Button Truncated
Large Button Fixed height

fix(cta-button): added content padding to center align for large btn

---

dist/snackbar-dialog/snackbar-dialog.css
src/less/snackbar-dialog/snackbar-dialog.less

Fixes #1924 
Fixes the action link styling.
Hover states have not been defined yet for these but the lack of hover indication feels a bit broken so I added a full underline on hover just to create differentiation for now. Once the hover color has been defined we can adjust these.
Before:
After:

fix(snackbar-dialog): action link colors

---

dist/icon-button/icon-button.css
docs/_includes/icon-button.html
src/less/icon-button/icon-button.less

- Fixes #1884 
Add size modifiers to icon button and icon link
- SUBJECTIVE CHANGE: Icons typically filled most of the button when a small modifier was applied, so I reduced `max-width` from `100%` to `75%`. Other values may be better (i.e. if we want to be mathematically precise and fill the circle with square icons it should be `70.71%`)

feat(icon-button): add size modifiers

---

dist/panel-dialog/panel-dialog.css
src/less/panel-dialog/panel-dialog.less
src/less/panel-dialog/stories/panel-dialog.stories.js

Fixes #1905 
Per spec, the panel dialog gets an enhancement in scrolling from the entire contents of the dialog to only the body, leaving the header and footer fixed.
Before:
After:

feat(panel-dialog): added scolling to panel body only

---

dist/link/link.css
src/less/link/link.less

- Addresses #1934
Remove color change on hover -- this may be an accessiblity affordance since there also aren't any style changes on active, I'd like to know your thoughts on this @ianmcburnie

fix(fake-link): remove color change on hover

---

dist/icon-button/icon-button.css
src/less/icon-button/icon-button.less

Isolates icon sizing to non-transparent buttons/links since icons in transparent buttons/links should encapsulate the entire button/link.
This story included both versions of icon buttons making the difference very prevalent. Infotip icon is inside transparent button; the infotip close icon is inside non-transparent button.
Before:
After:

fix(icon-button): Isolated icon resizing inside non-transparent buttons/links

---

dist/global/global.css
dist/link/link.css
src/less/global/global.less
src/less/link/link.less

Fixes #1950 
* Removed purple hover color. Changed it to be opacity of 0.7
* Removed visited on standlone link
* Added disabled state

feat(links): removed hover state and visited from standalone link

---

dist/button/button.css
src/less/button/button.less
src/less/button/stories/button/base.stories.js

Fixes #1940 
Fixes the center alignment of loading button.
BEFORE
AFTER

fix(button): fixed loading button form variant alignment

---

dist/carousel/carousel.css
src/less/carousel/carousel.less

Fixes #1961
* There are two attributes preventing any fixed items from going outside of carousel, `will-change` and `transform`. Both do not seem like they are needed. Removing them makes carousel work as before.

fix(carousel): removed will-change and transform to allow fixed passthrough

---

dist/button/button.css
dist/combobox/combobox.css
dist/floating-label/floating-label.css
src/less/button/button.less
src/less/combobox/combobox.less
src/less/floating-label/floating-label.less
src/less/star-rating-select/stories/star-rating-select.stories.js
src/less/star-rating/stories/star-rating.stories.js

Fixes #1943 
* Fixed various style issues previously introduced or uncaught.
* Added missing stories for `star-rating` and `star-rating-select`.
Here are some of the issues fixed:

fix(various-modules): fixed various prod issues, added missing stories

---

dist/legacy-tokens/ds4-light.css
dist/tokens/evo-light.css
src/tokens/evo-light.css

Fixes #1965 
This simply updates the visited link color globally. See issue for details.

feat(links): changed visited link color

---

dist/filter-menu-button/filter-menu-button.css
src/less/filter-menu-button/filter-menu-button.less

Fixes #1967
* Fixed issue by adding a `transform: translateZ(0);`. What is happening is the parent element has overflow hidden. In safari, the child will have the outline cutoff and hidden because of that. If we pop the child element on higher z index (but using translate), it shows correctly.

fix(filter-menu-button): outline on safari

---

dist/page-notice/page-notice.css
dist/section-notice/section-notice.css
src/less/page-notice/page-notice.less
src/less/section-notice/section-notice.less

Fixes #1945 
I made a few very minor spacing adjustments to `page-notice` and `section-notice` to make them look properly balanced according to design specs. 
* Unless you inspect the screenshot images in an image editor, you may not notice the changes.
* I also removed some old flex styles that were no longer doing anything.
Before:
After:

fix(page notice, section-notice): text alignment

---

dist/listbox-button/listbox-button.css
src/less/listbox-button/listbox-button.less
src/less/listbox-button/stories/form.stories.js

Fixes #1981
Added an aria-invalid style to listbox-button form styling. This was not being picked up since the selector is too strong
I could have added another style selector in the invalid part, but I kept it separate because we are planning on cleaning this up next tech debt. 
Also added a story.

fix(listbox-button): added invalid state to form

---

dist/button/button.css
src/less/button/button.less
src/less/button/stories/button/primary.stories.js
src/less/button/stories/destructive-button/primary.stories.js

Fixes #2010 
1. Fixed the main a11y issue with spinners in primary disabled buttons, for both regular primary buttons as well as destructive primary buttons.
2. I also fixed the wrong colors in progress spinners for primary buttons per Figma specs. The colors were wrong and inverted.
3. I also fixed the primary destructive button spinner colors. They were incorrectly inverted.
**Before**
**After**

fix(buttons): progress spinners in disabled buttons

---

dist/button/button.css
src/less/button/button.less
src/less/button/stories/button/primary.stories.js
src/less/button/stories/destructive-button/primary.stories.js

Reverts button disabled state handling #2010 
This reverts the disabled primary button spinner use case because of various visual and a11y complications.
Loading buttons should not be disabled in markup. More information from the team to follow.

fix(buttons): reverted primary disabled state handling

---

dist/calendar/calendar.css
docs/_includes/calendar-month.html
docs/_includes/calendar.html
src/less/calendar/calendar.less
src/less/calendar/stories/calendar.stories.js

A few minor clean-up changes that were noticed during review of the date input on eBayUI:
- `span` should now have full support for `aria-disabled` so there is no need for the `calendar__cell--disabled` class
- In the static calendar, `aria-label` is replaced with an additional clipped span
- There is now indication that a button is active (I opted for bolded text, this may be debated in the comments)

feat(calendar): clipped text for static calendars

---

dist/button/button.css
dist/combobox/combobox.css
dist/listbox-button/listbox-button.css
dist/listbox/listbox.css
dist/menu-button/menu-button.css
dist/menu/menu.css
src/less/button/button.less
src/less/mixins/private/selection-list-mixins.less

Fixes #2031 
I removed various sizing adjustments and overrides to allow the new icons to display properly. 
I also ran a targeted Percy build on the impacted components: https://percy.io/79bdc98e/eBay-Skin/builds/26489814
**Before**
**After**

fix(icons): adjusted/removed sizing overrides for icons

---

dist/alert-dialog/alert-dialog.css
dist/confirm-dialog/confirm-dialog.css
dist/drawer-dialog/drawer-dialog.css
dist/fullscreen-dialog/fullscreen-dialog.css
dist/lightbox-dialog/lightbox-dialog.css
dist/panel-dialog/panel-dialog.css
docs/_includes/lightbox-dialog.html
src/less/lightbox-dialog/lightbox-dialog.less
src/less/lightbox-dialog/stories/lightbox-dialog.stories.js
src/less/mixins/private/dialog-mixins.less

Fixes #1937
* Updated lightbox dialog min-width
* Removed the 50vh margin. Dialog should be centered
* Added `max-height` of 90%
* Added a `wide` size for lightbox dialog
* Added a scrolling body only

feat: updated dialog to new sizes and constraints

---

src/less/button/stories/button/base.stories.js
src/less/button/stories/button/cascade.stories.js
src/less/button/stories/button/dimensions.stories.js
src/less/button/stories/fake-button/base.stories.js
src/less/button/stories/fake-button/cascade.stories.js
src/less/button/stories/fake-button/dimensions.stories.js
src/less/icon-button/stories/alignment.stories.js

This is fixing the icon usage issues found in visual regression (https://percy.io/f1364dca/eBay-Skin/builds/26768330). I also fixed a missing icon of an `Icon Button` story.
I reran another Percy build after the fixes to verify the updates match `master`: https://percy.io/f1364dca/eBay-Skin/builds/26799373
**Issue**

fix(icons): adjusted icons used in storybook

---

dist/infotip/infotip.css
dist/textbox/textbox.css
src/less/infotip/infotip.less
src/less/textbox/textbox.less

Fixes #2055, #2050
* Fixed infotip by adding line height
* Fixed textbox by adding strong border color

fix(infotip,textbox): bugfixes on size and border

---

dist/button/button.css
docs/_includes/button.html
src/less/button/button.less
src/less/button/stories/button/dimensions.stories.js
src/less/cta-button/cta-button.less
src/less/mixins/private/button-mixins.less

Fixes #2066
* Added small height modifier to button
* Added some new stories for testing
* We had an old variable small already in the code (it was being used for regular). I deprecated that, added a regular size and a small-new size (we can rename it, but its only used in interim until next major.

feat(button): added small height

---

dist/alert-dialog/alert-dialog.css
dist/calendar/calendar.css
dist/carousel/carousel.css
dist/confirm-dialog/confirm-dialog.css
dist/drawer-dialog/drawer-dialog.css
dist/fullscreen-dialog/fullscreen-dialog.css
dist/infotip/infotip.css
dist/lightbox-dialog/lightbox-dialog.css
dist/panel-dialog/panel-dialog.css
dist/tooltip/tooltip.css
dist/tourtip/tourtip.css
dist/utility/utility.css
dist/video/video.css
src/less/calendar/calendar.less
src/less/mixins/private/bubble-mixins.less
src/less/mixins/private/dialog-mixins.less
src/less/mixins/public/utility-mixins.less
src/less/video/video.less

Fixes #2073 
This PR is to fix the pre-Safari 14.1 dialog display issues by reverting the use of `inset` (unsupported in impacted browsers) in lieu of explicit positioning.
The bug was impacting:
* alert dialog
* confirm dialog
* drawer dialog
* fullscreen dialog
* lightbox dialog
* panel dialog
Before:
After:

fix(dialog): fixed pre 14.1 Safari dialog display issues

---

dist/segmented-buttons/segmented-buttons.css
docs/_includes/segmented-buttons.html
src/less/button/button.less
src/less/mixins/private/button-mixins.less
src/less/segmented-buttons/segmented-buttons.less
src/less/segmented-buttons/stories/segmented-buttons.stories.js

Fixes #2064
* Added large size. 
* In order to have the sizes be correct based on designs, regular buttons are using 32px (small) button size and then with 4px padding top+bottom create a 40px container. The same with large, 40px (regular) button size with 4px padding top+bottom create a 48px container. I added a comment to address this.

feat(segmented-button): added large/small

---

dist/floating-label/floating-label.css
src/less/floating-label/floating-label.less

Release pull request for `16.2.2` release.

fix(floating-label): override inline transform during autofill (#2079)

---

dist/segmented-buttons/segmented-buttons.css
src/less/segmented-buttons/segmented-buttons.less

Fixes #2096 
Fixed segmented button non-current button colors on dark mode.
Before:
After:

fix(segmented-button): fixed non-current buttons on dark mode

---

dist/toast-dialog/toast-dialog.css
src/less/toast-dialog/toast-dialog.less

Fixes #2092 
Fixed the hover and active states.
I found out that `--color-state-information-hover` used for the hover background doesn't exist. When I used the tokens for accent hover/active, it looked more like what it should have looked like all along. We can remove that if it's not relevant, but it seems to resolve all of the hover state issues to what was likely originally intended. 
Before:
(see issue)
After:

fix(toast-dialog): secondary button hover issue

---

dist/textbox/textbox.css
src/less/textbox/textbox.less

Fixes #2089 
Added blue focus indicator to improve UX and `a11y` as well as focus consistency across controls.
Before:
After:

chore(textbox): add blue focus indicator

---

dist/page-notice/page-notice.css
src/less/page-notice/page-notice.less

Fixes #2082 
Fixed the focus indicator.
Before:
After:

fix(page-notice): anchor and fake link focus state

---

.stylelintrc
dist/carousel/carousel.css
dist/field/field.css
dist/page-notice/page-notice.css
dist/section-notice/section-notice.css
src/less/carousel/carousel.less
src/less/field/field.less
src/less/page-notice/page-notice.less
src/less/section-notice/section-notice.less

Fixes #2110
* Changed all end to to flex-end and start to flex-start

fix: changed start to flex-start (and end)

---

.stylelintrc
dist/global/global.css
dist/textbox/textbox.css
src/less/global/global.less
src/less/textbox/textbox.less

* We have a no-unsupported-browser-features plugin. However it was not enabled. This PR enables it
* Normally this would have been a push directly to branch change. However, I noticed we have two places where we are using unsupported browser features (on firefox). I have disabled them for this PR but I wanted to take a look to see if we can change them.

chore(styleline): added support for no-unsupported

---

package.json

Fixes #1338
Just a simple PR to get me back in the swing of things :-) Also got my signed commits working again. Woohoo.
By removing the dist folder before every build we ensure there are no stale dist files.
There was a time when we deliberately kept some stale dist files around (i.e. by stale, we mean they didn't have a corresponding src folder), but this was a bad practice and is no longer the case anyway.

build: remove dist folder before running build #1338

---

dist/page-notice/page-notice.css
src/less/page-notice/page-notice.less

Fixes #2112 
Fixed the small spacing issue on smaller screens.
Before: (see issue)
After:

fix(page-notice): spacing fix

---

dist/button/button.css
src/less/button/button.less
src/less/button/stories/destructive-button/borderless.stories.js

Fixes #1910 
Added borderless destructive red to button/fake button
Before: (see issue)
After:

fix(button): add destructive red to borderless

---

dist/listbox-button/listbox-button.css
src/less/listbox-button/listbox-button.less

Fixes #1991 
I fixed the listbox button alignment to match the options. 
Before:
After:

fix(listbox-button): alignment

---

dist/carousel/carousel.css
docs/_includes/carousel.html
src/less/carousel/carousel.less
src/less/carousel/stories/carousel.stories.js

This PR is ONLY changing the icon size. It does not move the paddle to the new position. There are some issues with `overflow: hidden` and relative positioning on the carousel__container which will take a little longer to figure out. Might as well get these simpler changes in before then.
I also added new stories that have the paddles shown (for Percy purposes) and fixed a couple of issues in the existing stories.
Before
After

style(carousel): change paddle icon from 24 to 12 (#1925)

---

dist/carousel/carousel.css
src/less/carousel/carousel.less
src/less/carousel/stories/carousel.stories.js

Fixes #1925
New paddle position which has moved from the inner edges of the container to now overlapping the container edge.
I had to remove `overflow: hidden` from the container to make this work with the current markup structure. I've tested this across browsers and not seen any behavior that is different from in production. 
This is due to overflow: hidden on the root (needs a refactor).

style(carousel): paddles overlap container edge #1925

---

dist/alert-dialog/alert-dialog.css
dist/confirm-dialog/confirm-dialog.css
dist/lightbox-dialog/lightbox-dialog.css
dist/tokens/evo-core.css
docs/_includes/lightbox-dialog.html
src/less/lightbox-dialog/lightbox-dialog.less
src/less/lightbox-dialog/stories/lightbox-dialog.stories.js
src/less/mixins/private/dialog-mixins.less
src/tokens/evo-core.css

Fixes #2086
* Added popup sheet variant to lightbox. This automatically changes based on scrensize
* Added animation class which animates both slide in from bottom and the fade in
* At the moment I added expanded support for for both. I could only add it in small screens but I left it for both for now. We can change it if needed.

feat(lightbox-dialog): added popup sheet variant

---

dist/section-notice/section-notice.css
src/less/section-notice/section-notice.less

Quick fix for #2142. Was just a simple typo.
Working now:

fix(section-notice): cta in rtl #2142

---

dist/alert-dialog/alert-dialog.css
dist/confirm-dialog/confirm-dialog.css
src/less/alert-dialog/alert-dialog.less
src/less/confirm-dialog/confirm-dialog.less

Fixes #2169
* We missed adding the large mixin for confirm and alert dialogs. Added it here

fix(confirm/alert dialog): added large window mixin

---

dist/carousel/carousel.css
dist/mixins/utility-mixins.less
dist/utility/utility.css
docs/_includes/utility.html
src/less/mixins/public/utility-mixins.less

Fixes #2068 
- I fixed image right click suppression with the method suggested in the issue.
- I also added a notes section under Utility with the first note about the performance impact of `will-change`.
Percy and Storybook are N/A above.

utility: fixed image right-click suppression

---

docs/_includes/drawer-dialog.html
docs/_includes/infotip.html
src/less/infotip/stories/infotip.stories.js

Fixes #2180
* Swapped drawer dialog to lightbox in infotip modal
* Added deprecated message to drawer dialog

docs(infotip): updated to use lightbox dialog

---

dist/combobox/combobox.css
dist/listbox-button/listbox-button.css
dist/listbox/listbox.css
dist/menu-button/menu-button.css
dist/menu/menu.css
docs/_includes/listbox-button.html
docs/_includes/listbox.html
src/less/listbox-button/listbox-button.less
src/less/listbox-button/stories/subtitle.stories.js
src/less/listbox/listbox.less
src/less/listbox/stories/listbox.stories.js
src/less/mixins/private/listbox-mixins.less
src/less/mixins/private/selection-list-mixins.less

Fixes #2179
* Added subtitle to each option
* I named it subtitle. It's kinda weird since we don't have a title, but I thought it sounded better than subvalue or subtext. 
This will require makeup changes. If you select an option currently it will fill the textbox with both title and subtitle. I want to finalize the structure and naming before doing the makeup changes. This is why this PR is up to get early feedback.
Once the naming and structure is approved I will update makeup and then upgrade makeup in this PR.

feat(listbox): added subtitle to each option

---

dist/progress-stepper/progress-stepper.css
src/less/progress-stepper/progress-stepper.less

Fixes #2176
* We were overriding the font size for small screens (my guess is this was the old design). Removed those old overrides.

fix(progress-stepper): updated font-size to be default

---

dist/combobox/combobox.css
src/less/combobox/combobox.less

Fixes #2201
* Removed outline 0 from combobox

chore(combobox): add blue focus indicator

---

dist/listbox-button/listbox-button.css
src/less/listbox-button/listbox-button.less

Fixes #2192
* Set the border color to btn--form for listbox. I did not want to change it in button becasue this is used by menu button as well. 
* We should look to refactor in future possibly.

feat(listbox-button): changed default border color

---

dist/toggle-button/toggle-button.css
docs/_includes/toggle-button.html
src/less/toggle-button/stories/gallery-layout.stories.js
src/less/toggle-button/stories/list-layout.stories.js
src/less/toggle-button/stories/minimal-layout.stories.js
src/less/toggle-button/toggle-button.less

- Fixes #2198 
- Add disabled state to toggle buttons

feat(toggle-button): add disabled state

---

dist/image-placeholder/image-placeholder.css
src/less/image-placeholder/image-placeholder.less

Adds dark mode support to image placeholder

fix(image-placeholder): dark mode color

---

dist/combobox/combobox.css
dist/select/select.css
src/less/combobox/combobox.less
src/less/select/select.less

Fixes #2175 
This issue was created as part of less to CSS variables conversion. Noticed that `select` and `combobox` components refer to non-design system token `--font-size-18` for large variants. Hence refactored the code to use the DS `--font-size-16` aka `--font-size-medium`
- Pending Percy testing to 
Combobox
Select

fix(select,combobox): updated large variant font size token

---

dist/listbox-button/listbox-button.css
src/less/listbox-button/listbox-button.less

Fixes #2228
* So when verifiying older versions of the listbox code on skin site, I noticed that overflow is set but was not doing anything in those versions. 
(In this case I simply changed the html and saw that it stretched until infinite). 
However when we changed it to be `inline-grid` from `inline-flex` the truncation was picked up and we ended up with this bug where the listbox dropdown is aligned to the size of the button.
So removing the truncation on the value solved this issue. We should probably revisit this in the future and put a limit on the container (a max width), but we need to get buy in from design. This is mostly to unblock teams that run into this issue with the last version.

fix(listbox-button): removed truncation

---

dist/breadcrumbs/breadcrumbs.css
src/less/breadcrumbs/breadcrumbs.less

Fixes #2053
Spacing adjustments with chevron on breadcrumbs.
The other components mentioned in the issue did not need spacing adjustments.
Before: 
After:

fix(breadcrumbs): chevron icon spacing

---

docs/_includes/avatar.html
src/less/avatar/stories/avatar.stories.js

Fixes #2220
PLEASE SQUASH.
Having the sign in status hardcoded in the examples was problematic as the avatars are not always used for the current user.
The custom image avatar had alt text on the nested image, it makes more sense to consolidate the alt text on the root tag to be consistent across avatars.
For the default avatar, I placed the letter inside of a span element. This gives us a little more flexibility for ARIA in future (i.e. incase we decide to move the role=img and aria-label onto the nested element).
The vertical alignment in production looks a little off. I did not try and fix that in this PR.
We'll need to make some minor changes on ebayui-core side.

feat(avatar): a11y changes (#2220)

---

dist/breadcrumbs/breadcrumbs.css
src/less/breadcrumbs/breadcrumbs.less
src/less/section-notice/stories/icon-24.stories.js

This fixes breadcrumbs overflow spacing and missing icons in docs.
Fixes #
Post-release visual regression of `17.0.0` revealed some issues. This fixes two of those issues:
1. Breadcrumbs overflow spacing
2. Missing icons in storybook
Before:
After:

fix(breadcrumbs,docs): fixed breadcrumbs spacing and missing icons in docs

---

docs/_includes/skeleton.html

Note: I have not gotten to the loading examples page yet. I will do that in a follow up PR.
This is the type of tone of voice, and concise, to-the-point documentation style we should strive for.

docs(skeleton): some cleanup and tone of voice

---

ICON-CREATION.md
docs/_includes/icon.html

Updated icon docs with missing deprecated workflow and sections for avoiding state-based icons.
It looks like we had not added information about deprecating icons in the contributing docs. 
Also, based on the recent ask for creating disabled icons from currently existing base icons, it became clear that we needed to be more explicit about using only base icons and doing all state modifications in `css`. After a discussion with Ian, it was clear that we should be more explicit about that guidance.

docs(icons): updated icon skin and contributing docs

---

dist/skeleton/skeleton.css
src/less/skeleton/skeleton.less

Fixes #2239 
This change fixes skeletons having default top margins. Instead adds spacing to block level elements after the first one.
**Before**
**After**

fix(skeletons): incorrect block margins

---

dist/eek/eek.css
src/less/eek/eek.less

Fixes #2245
* Swapped incorrect hex value

fix(eek): updated color

---

dist/icon/icon.css
dist/tokens/evo-light.css
docs/_includes/icon.html
src/less/icon/icon.less
src/tokens/evo-light.css

Fixes #2231 
This simply adds disabled support for complex icons with a suffix, `-colored`. 
1. Initially, I was planning on using the `svg.icon--disabled[class~="-colored"]` to find the icons that ended with `-colored` class and isolate complex icons, but I had not taken class ordering into consideration. I opted to use `svg.icon--disabled[class*="-colored"]` instead to find the class string anywhere in the `class` attribute instead. Since this is cascading from `.icon--disabled` the only risk of the more aggressive selector is having a simple icon that has `-colored` in its name _and_ is disabled.
2. I was initially thinking of keeping this change isolated to complex icons, but the more I think about it, I'm thinking it might simply be easier to apply this grayscale+opacity method to …

feat(icon): added disabled support for complex icons

---

dist/floating-label/floating-label.css
src/less/floating-label/floating-label.less

Fixes #2253
* Added `!important` to styles for select line height. This prevents it from being overridden by bookmarklets causing text overlap.

fix(floating-label): force select line height to prevent overrides

---

dist/signal/signal.css
src/less/signal/signal.less

Fixes #2212 
I updating the spacing to match Figma. I did not use horizontal margins as that should be an implementation-level styling since it won't work in all uses of the module.
I'm not sure this is technically a bug. The Figma was likely updated after the module was last updated which likely created this misalignment. 
**Before**
<kbd><img width="678" alt="image" src="https://github.com/eBay/skin/assets/1675667/93a1419b-c96c-43f1-952f-94b5ef383eff"></kbd>
**After**
<kbd><img width="640" alt="image" src="https://github.com/eBay/skin/assets/1675667/1f84d558-02ec-4e0e-9320-2a5b2eabfd7e"></kbd>

fix(signal): updated spacing

---

dist/combobox/combobox.css
dist/date-textbox/date-textbox.css
dist/filter-menu-button/filter-menu-button.css
dist/infotip/infotip.css
dist/listbox-button/listbox-button.css
dist/listbox/listbox.css
dist/menu-button/menu-button.css
dist/menu/menu.css
dist/tooltip/tooltip.css
dist/tourtip/tourtip.css
src/less/date-textbox/date-textbox.less
src/less/filter-menu-button/filter-menu-button.less
src/less/mixins/private/bubble-mixins.less
src/less/mixins/private/dropdown-mixins.less
src/less/mixins/private/selection-list-mixins.less
src/less/pagination/stories/overflow.stories.js

Fixes prerelease issues discovered by Percy.
Percy found a couple of issues in the prerelease:
1. Using `filter: drop:shadow()` doesn't work in Safari on elements that have overflows, which is most of our popovers. I changed shadows from using `drop-shadow` to `box-shadow`, which is a more robust solution.
2. During the application of the popovers styles, I inadvertently made changes causing menu item borders to show up. I set those back to what they were to fix menu items.
3. I also fixed a story that was missing overflow icons due to previous icon renaming.
**Before**
<hr>
**After**

fix(popovers,menus): fixed shadows in Safari and restored borders in menus

---

.changeset/tough-cougars-poke.md
docs/_includes/carousel.html
src/less/carousel/stories/carousel.stories.js

Fixes #2261 
Simply replaced the 12px chevron icon with the 16px icon in docs and storybook.
**Before**
<kbd><img width="229" alt="carousel-chevron-icon-before" src="https://github.com/eBay/skin/assets/1675667/5cf60cbf-ae8b-4506-bedd-04dde438b5b9"></kbd>
**After**
<kbd><img width="230" alt="carousel-chevron-icon-after" src="https://github.com/eBay/skin/assets/1675667/1392e1c0-e507-474c-9da6-4137b5b2ff7c"></kbd>

feat(carousel): updated chevron sizes

---

.changeset/clever-trees-trade.md
dist/education-notice/education-notice.css
docs/_includes/education-notice.html
src/less/education-notice/education-notice.less
src/less/education-notice/stories/base.stories.js

Fixes #2293
Changed the button to an icon button matching the smallest size we have to what the Figma contains.

feat(education-notice): use icon button

---

dist/listbox-button/listbox-button.css
src/less/listbox-button/listbox-button.less

Fixes #2270
Continuation of PR #2281

fix(listbox-button): border color default to attention in invalid state

---

.changeset/silly-camels-switch.md
dist/listbox-button/listbox-button.css
src/less/listbox-button/listbox-button.less

Fixes #2298
* Added border radius to listbox contaienr

fix(listbox-button): added border radius to container

---

.changeset/metal-cars-promise.md
dist/skeleton/skeleton.css
dist/tokens/evo-dark.css
dist/tokens/evo-light.css
docs/_includes/skeleton.html
src/less/skeleton/skeleton.less
src/less/skeleton/stories/composite.stories.js
src/tokens/evo-dark.css
src/tokens/evo-light.css

Fixes #2305
* Added `skeleton--on-secondary` modifier
* Updated tokens for both base skeleton colors but also for `on-secondary`
* As per design `--elevated` is deprecated. The colors in `on-secondary` should be used in `--elevated`

feat(skeletons): added on-secondary color

---

.changeset/odd-months-roll.md
dist/icon-button/icon-button.css
src/less/icon-button/icon-button.less

Fixing issue discovered post-release. Icon buttons that use link need to have the same color icons as the ones using non-visited links.
**Before**
<kbd><img width="401" alt="image" src="https://github.com/eBay/skin/assets/1675667/7aa1c4e3-409b-430d-88a9-294ccea35a30"></kbd>
**After**
<kbd><img width="422" alt="image" src="https://github.com/eBay/skin/assets/1675667/4e469eec-9a0f-47f8-a67d-639ea80f8dc3"></kbd>

fix(icon-button): fixed primary visited link icon color

---

.changeset/lemon-bobcats-collect.md
docs/_includes/date-textbox.html
src/less/date-textbox/stories/date-textbox.stories.js

Fixes #2284
Updated docs and added a story for disabled state

docs(date-textbox): added docs and story for disabled state

---

.changeset/loud-rivers-pump.md
dist/toggle-button/toggle-button.css
dist/tokens/evo-light.css
docs/_includes/toggle-button-group.html
docs/index.html
src/less/toggle-button/toggle-button.less
src/tokens/evo-light.css

Fixes #2315 
Added hover and pressed states. Per DS, the state tokens needed to be revised as well (includede).
Since hovers exposed the `rgba` transparency color and made buttons look yellow, I also removed the yellow background color from the `toggle-button-group` docs to avoid relaying misinformation to devs about its potential usage inside any container with any other background color. 
**Before**
Hover
<kbd><img width="88" alt="image" src="https://github.com/eBay/skin/assets/1675667/cf256271-6d12-4084-b363-b5aa9a3f99fa"></kbd>
Pressed
<kbd><img width="88" alt="image" src="https://github.com/eBay/skin/assets/1675667/a89fd25a-3f14-4bd7-8353-b5a919f91fcc"></kbd>
**After**
Hover
<kbd><img width="94" alt="image" src="https://github.com/eBay/skin/assets/1675667/816124a3-3fe8-4888-9dd5-8db1f …

feat(toggle-button): added hover and pressed states

---

dist/drawer-dialog/drawer-dialog.css
dist/fullscreen-dialog/fullscreen-dialog.css
dist/lightbox-dialog/lightbox-dialog.css
dist/panel-dialog/panel-dialog.css
dist/toast-dialog/toast-dialog.css
src/less/alert-dialog/stories/alert-dialog.stories.js
src/less/confirm-dialog/stories/confirm-dialog.stories.js
src/less/drawer-dialog/drawer-dialog.less
src/less/drawer-dialog/stories/drawer-dialog.stories.js
src/less/fullscreen-dialog/fullscreen-dialog.less
src/less/fullscreen-dialog/stories/fullscreen-dialog.stories.js
src/less/lightbox-dialog/lightbox-dialog.less
src/less/lightbox-dialog/stories/lightbox-dialog.stories.js
src/less/mixins/private/dialog-mixins.less
src/less/panel-dialog/panel-dialog.less
src/less/panel-dialog/stories/panel-dialog.stories.js
src/less/toast-dialog/stories/toast-dialog.stories.js
src/less/toast-dialog/toast-dialog.less

- Fixes #2333
- Wrap instead of truncating titles in dialogs.
- Ensure that any icons/buttons on the same flex row as the title align to top instead of center.

fix(dialog): wrap instead of truncating

---

.changeset/khaki-fans-pretend.md
dist/menu/menu.css
src/less/menu/menu.less
src/less/menu/stories/fake-menu.stories.js

Fixes #2208
* Added `badge` selector for `fake-menu`
* Added new story for it

fix(fake-menu): added badge support

---

.changeset/mighty-cycles-drive.md
dist/menu-button/menu-button.css
dist/menu/menu.css
src/sass/menu-button/menu-button.scss
src/sass/menu/menu.scss

https://github.com/eBay/skin/issues/2366
Fixed issue with ticks showing up on all menu buttons
Swapped out all `icon--tick-16` to be `icon--16`

fix(menu): changed icon--tick-16 to be icon--16

---

.changeset/fluffy-balloons-love.md
dist/tokens/evo-light.css
src/tokens/evo-light.css

Fixes #2388 
- Update background-attention and foreground-attention as per [playbook](https://playbook.ebaydesign.tech/design-system/tokens/color-tokens)
Write color contrast:

fix(tokens): update foreground background attention color

---

.changeset/curvy-bobcats-tie.md
dist/textbox/textbox.css
src/sass/textbox/textbox.scss

Fixes #2389 
Fixes large textbox height.
**Before**
<kbd><img width="369" alt="Screenshot 2024-07-24 at 8 44 13 AM" src="https://github.com/user-attachments/assets/93c2ee9f-502d-452d-a90a-de50e70aebcf"></kbd>
**After**
<kbd><img width="380" alt="Screenshot 2024-07-24 at 8 45 01 AM" src="https://github.com/user-attachments/assets/14d1ab70-ef08-4608-bb50-c67b8bb426a8"></kbd>

fix(textbox): fixed large textbox height

---

.changeset/curvy-bobcats-tie.md
.changeset/honest-maps-jog.md
dist/textbox/textbox.css
src/sass/textbox/textbox.scss

Fixes #2386 
Fixed the textbox input overlapping the rounded corners.
**Before**
<kbd><img width="251" alt="Screenshot 2024-07-24 at 12 12 51 PM" src="https://github.com/user-attachments/assets/78545240-cbba-4b7e-9572-c2e0d648a316"></kbd>
**After**
<kbd><img width="239" alt="Screenshot 2024-07-24 at 12 13 25 PM" src="https://github.com/user-attachments/assets/9f010ee9-349d-42a4-8617-37d29404c807"></kbd>

fix(textbox): fixed textbox overlap

---

.changeset/funny-months-fix.md
dist/progress-spinner/progress-spinner.css
docs/_includes/button.html
src/sass/button/stories/button/base.stories.js
src/sass/progress-spinner/progress-spinner.scss

Fixes #2397
* We had some styles which fixed the progress spinner wobble but they were targetting the old classes instead of the new. 
* Added story for large button with progress spinner

fix(progress-spinner): wobble

---

.changeset/beige-buttons-check.md
dist/textbox/textbox.css
src/sass/textbox/stories/textbox.stories.js
src/sass/textbox/textbox.scss

Fixes #2404 
- Added `width: 100%` for `textbox--fluid` variant on `input` element
- Updated `textbox` fluid story with new structure
Before
After

fix(textbox): use 100% width on input for fluid variant

---

.changeset/lovely-apples-watch.md
CONTRIBUTING.md
docs/index.html
scripts/develop-module_proper/code-generators/doc-generator.js

Addresses #2371
Update a few modules' Design System component name mappings to match our latest Design System canonical names, so we can accurately query for component status. Simplify this mapping by removing the optional `group` field, which our Component Status API can infer from name.
N/A

docs: update Design System name mapping for modules

---

.changeset/three-melons-decide.md
dist/toggle-button-group/toggle-button-group.css
src/sass/toggle-button-group/stories/gallery-layout-exceptions.stories.js
src/sass/toggle-button-group/stories/gallery-layout.stories.js
src/sass/toggle-button-group/stories/list-layout-exceptions.stories.js
src/sass/toggle-button-group/stories/list-layout.stories.js
src/sass/toggle-button-group/stories/minimal-layout-exceptions.stories.js
src/sass/toggle-button-group/stories/minimal-layout.stories.js
src/sass/toggle-button-group/toggle-button-group.scss

Fixes #2401 
1. I fixed the list and gallery variation minimal screen/container buttons so that any container/screen under `320px` will use the actual `css` props. The `css` props implemented initially weren't actually being used for the respective button layouts.
2. I changed the default gallery variation minimal screen/container (`< 320px`) buttons to 2 since it has since now been using that inheriting the min layout button `css` prop, to avoid breaking current implementations and since it looks better overall.
3. I added 3 minimal layout (`< 320px`) exceptions for more implementation flexibility with *any* of the layout type buttons.
4. I added a few stories, both for the missing use cases and for the new minimal container exceptions for all the button layouts.
**Before**
<kbd><img …

fix(toggle-button-group): fixed buttons per row and added min layout exceptions

---

.changeset/dull-chicken-dance.md
dist/details/details.css
docs/_includes/details.html
src/sass/details/details.scss
src/sass/details/stories/cascade.stories.js
src/sass/details/stories/details.stories.js

Fixes #2036
* Updated details visual style
* Fixed icon layout (for old icon it should still align)
* Design wants width to be fixed to item. For now, I left it as is and have the width span the whole content of the button. This is in order to prevent possible layout shift if we have things on the left/right of it
This is what it looks like if we remove width 100% (current not in this change)
With width 100%
Old icon (12px)
New Icon (16px)

feat(details): updated styling

---

.changeset/flat-carrots-kneel.md
dist/tokens/evo-dark.css
dist/tokens/evo-light.css
src/tokens/evo-dark.css
src/tokens/evo-light.css

Fixes #2370
Updated tokens to reflect new DS colors for education notice
- Pending Percy testing

feat(education-notice): updated education background color

---

.changeset/plenty-dolphins-bake.md
src/routes/+layout.style.scss

Fixes #2372 
Fixed the docs highlight class colors with tokens that support better contrast in both light and dark modes

fix(docs): styling on dark mode

---

dist/menu-button/menu-button.css
src/sass/menu-button/menu-button.scss

Fixes #2424
* Changed selector to be direct descendent.

fix(menu-button): added direct selector for icons

---

.changeset/fair-shoes-teach.md
dist/button/button.css
src/sass/button/button.scss

Fixes #2387
Updated the disabled styles to make fake button look disabled

fix(fake-button): updated disabled styles

---

.changeset/popular-bananas-rescue.md
src/modules/calendar.marko
src/modules/toggle-button-group.marko

Fixes #2432 
Fixed horizontal scroll on docs.
**Before**
<kbd><img width="438" alt="Screenshot 2024-08-30 at 9 50 17 AM" src="https://github.com/user-attachments/assets/201389b8-2980-4271-9cd2-1c010800a55f"></kbd>
**After**
<kbd><img width="437" alt="Screenshot 2024-08-30 at 9 50 50 AM" src="https://github.com/user-attachments/assets/13fb01da-d28b-417e-bfa1-4d3acba1b193"></kbd>

fix(docs): fixed horizontal scroll issues in docs

---

.changeset/stupid-candles-hang.md
dist/tourtip/tourtip.css
src/sass/tourtip/tourtip.scss

Fixes #2416
- Updated tokens to use `color-background-inverse` for background and `color-foreground-on-inverse` for foreground color.
- Fixed the spacing between fake link and CTA button
- `tourtip__index` currently inherits the color of the container but will be replaced with the `foreground-secondary-on-inverse` once DS defines it.
- An open issue where focus ring is not visible in dark mode which will be fixed with enhancement #2421

feat(tourtip): improve contrast of tip container

---

.changeset/twenty-buttons-beam.md
dist/icon-button/icon-button.css
dist/toast-dialog/toast-dialog.css
src/sass/icon-button/icon-button.scss
src/sass/toast-dialog/stories/toast-dialog.stories.js
src/sass/toast-dialog/toast-dialog.scss

Fixes #2295 
I removed focus overrides in transparent icon button, itemized where icon buttons were being used, and verified fixes to styling issues when used in other modules. That fixed issues in:
* Calendar
* Date Textbox
* Pagination
* Textbox
I also manually removed focus overrides and added styling in Toast Dialog to bring it to parity, create consistency.
**Before and After**
<kbd><img width="833" alt="transparent-button-fix-calendar-before" src="https://github.com/user-attachments/assets/f629d593-e2c9-4f4b-94e6-ab33333cb809">
<kbd><img width="260" alt="Screenshot 2024-09-16 at 1 42 35 PM" src="https://github.com/user-attachments/assets/3dedf251-fc60-4de0-89ce-4d53e74041dc">
<kbd><img width="444" alt="Screenshot 2024-09-16 at 1 49 51 PM" …

fix(icon-button): refactored and fixed focus

---

.changeset/healthy-eyes-trade.md
dist/lightbox-dialog/lightbox-dialog.css
src/sass/lightbox-dialog/lightbox-dialog.scss
src/sass/mixins/private/_dialog-mixins.scss

Fixes #2408
- Added border top to show the divider over the lightbox footer.
-  Not sure why `padding-top` was set to `0` in `dialog-footer-content-large` mixin. Removed assuming legacy code.

feat(lightbox): add divider over footer

---

.changeset/tricky-hats-bake.md
dist/button/button.css
dist/cta-button/cta-button.css
src/sass/mixins/private/_button-mixins.scss

Fixes #2075
- For `button:btn` &  `a.fake-btn:focus` added `outline` for `:focus-visible` pseudo selector 
- Outline color need to be changed consistently across all buttons and other interactive elements. #2421 
- Another issue noticed is the focus overlapping on skin docs site when multiple buttons are adjacent to each other.
Primary Button

fix(button): update focus outline and offset

---

.changeset/wise-cougars-cross.md
dist/table/table.css
src/modules/table.marko
src/sass/table/stories/table.actions.stories.js
src/sass/table/stories/table.inputs.stories.js
src/sass/table/stories/table.selection.stories.js
src/sass/table/stories/table.sortable.stories.js
src/sass/table/stories/table.stories.js
src/sass/table/table.scss

Fixes #1900
This PR is Iteration 2 of the Table module. It includes
1. Sorting
2. Cell Types
3. Actions
4. Inputs
The BEM structure was adjusted to better align with the markup structure.
<kbd><img width="1113" alt="image" src="https://github.com/user-attachments/assets/c40010e0-3715-4f26-84b8-008d83ccef60"></kbd>
<kbd><img width="1115" alt="image" src="https://github.com/user-attachments/assets/9c00d264-2cf5-4d02-815b-80d6f544fbba"></kbd>
<kbd><img width="915" alt="image" src="https://github.com/user-attachments/assets/1d812a91-727d-41fe-b846-092e56efa040"></kbd>
<kbd><img width="957" alt="image" src="https://github.com/user-attachments/assets/240d1956-a79c-42ab-92a0-ca4df394e9c8"></kbd>

feat(table): added sorting, cell types, actions, and inputs

---

.changeset/little-days-wait.md
dist/eek/eek.css
src/sass/eek/eek.scss

Fixes #2447
* Initially eek needed an icon change which was going to be a bigger change. However, I was able to resize it and it looks pretty good. 
* For the next major we should change the icon but that would be considered breaking
* The icon provided in the issue was not working (no borders), so will need a new one from design

feat(eek): updated size

---

.changeset/strong-dingos-suffer.md
dist/list/list.css
src/modules/list.marko
src/sass/bundles/skin-headless.scss
src/sass/list/list.scss
src/sass/list/stories/list.stories.js

Fixes #2453
* Added new list component.
* Im happy to change the name of the component. However, looking around to other libraries, they call this component list (material, bootstrap calls is list-group). Please provide feedback and the name you would like!
* I did not have this use grid because from what the designs look like, they do not all need to be the same size as each other. Some elements can be larger depending on the content. 
* Added both `a` and `button` type overrides for the root
* For the items before and after, used `trailing` and `leading`. Again, these were the terms used by both design and outside design libraries (material etc). Again, happy to use other terms as needed.

feat(list): new component

---

.changeset/moody-otters-wait.md
dist/table/table.css
src/modules/table.marko
src/sass/table/table.scss

Fixes #2457
* Allowed the line under `<thead>` to make the UI look better when scrolling.
* Reversed the way we're handling table height constraint.

chore(table): added thead line for scrolling, reverted table contraint

---

.changeset/flat-snakes-sell.md
dist/eek/eek.css
src/modules/eek.marko
src/sass/eek/eek.scss
src/sass/eek/stories/eek.stories.js

Fixes #2469
* Added large eek size
* As part of this, I noticed the eek arrow was too small, fixed it to be larger
* There were no stories, so I added those as well. 
* After adding storeis, I saw there were some RTL issues. Fixed RTL issues as well. 
* __note__ there is an open question to design about the regular EEK size but that can be done in a followup. The main issue is the height of the range portion is 20px, but the text range is supposed to be 8px and the icon is 6px. So 8+8+6 = 22px which is too large. But this isn't a problem in large EEK.

feat(eek): added large styles

---

.changeset/big-plums-applaud.md
dist/filter-menu/filter-menu.css
src/modules/filter-menu.marko
src/sass/filter-menu/filter-menu.scss
src/sass/filter-menu/stories/filter-menu.stories.js

Fixes #2451
Added search header for filter menu
I fixed a minor spacing issue for filter menu items for RTL.
<kbd><img width="944" alt="image" src="https://github.com/user-attachments/assets/62214fd0-e83f-4f5a-9c0f-37213a3b4141"></kbd>

feat(filter-menu): added search header

---

.changeset/light-pots-wink.md
dist/list/list.css
src/modules/list.marko
src/sass/list/list.scss
src/sass/list/stories/list.stories.js

Fixes #2477
* Added fieldset support
* Added ol support as well as automatic numbering
__Question__ for the fieldest, I added a legend. Should we hide it? I left it in but styled it as a list item. We can clip it if needed since it wasn't in the original design.

feat(list): added interactive radio fieldet and incremental list

---

.changeset/mean-goats-smile.md
dist/alert-dialog/alert-dialog.css
dist/confirm-dialog/confirm-dialog.css
src/sass/alert-dialog/alert-dialog.scss
src/sass/confirm-dialog/confirm-dialog.scss

Fixes #2489
* Changed dialogs to be left aligned except footer to be right aligned.

fix(alert/confirm-dialog): changed alignment to left and right for footer

---

.changeset/tame-monkeys-sparkle.md
src/modules/link.marko
src/sass/link/stories/link.stories.js

Fixes #2488
* Added documentation for fake-link disabled

docs(link): added disabled fake-link

---

.changeset/green-falcons-thank.md
dist/floating-label/floating-label.css
src/sass/floating-label/floating-label.scss

Fixes #2503
* Updated color for floating label based on new design spec
Also verified color contrast should be passing as per design.

feat(floating-label): updated unselected color of label

---

.changeset/twenty-berries-eat.md
dist/svg/icon/icon-stepper-upcoming-24.svg
dist/svg/icons.svg
src/components/master-icons.marko
src/routes/static/icon/icon-stepper-upcoming-24.svg
src/routes/static/icons.svg
src/svg/icon/icon-stepper-upcoming-24.svg
src/svg/icons.svg

Fixes #2494
- Updated the icon color to `--color-stroke-default` from `--color-background-disabled` in icons.svg file for `icon-stepper-upcoming-24` to meet contrast.
**Before**
**After**

fix(progress-stepper): updated upcoming color to meet contrast

---

CONTRIBUTING.md

Fixes # 2511
- Fix typos and punctuation errors for better readability.
- Replace the dead link with a legacy archived version to retain the original content: [archived version](https://web.archive.org/web/20161029110643/https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Writing_efficient_CSS)

fix(docs): fix dead link & typos in CONTRIBUTING.md (#2511)

---

dist/chips-combobox/chips-combobox.css
dist/combobox/combobox.css
dist/filter-menu-button/filter-menu-button.css
dist/listbox-button/listbox-button.css
dist/menu-button/menu-button.css
package-lock.json
package.json
src/routes/main.js
src/sass/chips-combobox/chips-combobox.scss
src/sass/chips-combobox/stories/chips-combobox.stories.js
src/sass/combobox/stories/combobox.stories.js
src/sass/filter-menu-button/filter-menu-button.scss
src/sass/filter-menu-button/stories/filter-menu-button.stories.js
src/sass/listbox-button/stories/base.stories.js
src/sass/listbox-button/stories/cascade.stories.js
src/sass/listbox-button/stories/dimensions.stories.js
src/sass/listbox-button/stories/error/error.base.stories.js
src/sass/listbox-button/stories/error/error.cascade.stories.js
src/sass/listbox-button/stories/error/error.dimensions.stories.js
src/sass/listbox-button/stories/error/error.form.stories.js
src/sass/listbox-button/stories/form.stories.js
src/sass/listbox-button/stories/subtitle.stories.js
src/sass/menu-button/stories/base.stories.js
src/sass/menu-button/stories/cascade.stories.js
src/sass/menu-button/stories/dimensions.stories.js
src/sass/menu-button/stories/fake-menu-button.stories.js
src/sass/mixins/private/_dropdown-mixins.scss
src/sass/phone-input/stories/phone-input.stories.js

Fixes #
* In order to support floating ui, we needed to add some default styles. We have these as the default. I kept around the old behavior of the dropdown as `menu-button__menu--set-position` in case we need it (I do not think its necessary, but others might; menu buttons should only be toggled with javascript, so having a no-js option isn't really feasible).
* For the width: I added it as fit-content. I also make sure it resizes appropriately. When I did max-content, there were some issues with overflowing menu items which would cause it to span across the whole page.

feat(floating-ui): added support for floating-ui in dropdowns

---

.changeset/rich-peas-clap.md
src/routes/_index/component/table/+page.marko
src/sass/table/stories/table.loading.stories.js
src/sass/table/stories/table.sortable.stories.js

Fixes #2484
- Removed `aria-pressed` references in the docs code as the attribute is inappropriate to denote multiple states of sort.

fix(table): remove aria-pressed from table headings

---

.changeset/smart-bugs-turn.md
dist/date-textbox/date-textbox.css
src/routes/_index/component/date-textbox/+page.marko
src/routes/main.js
src/sass/date-textbox/date-textbox.scss

Fixes #2514
* Did not update date-textbox styles to support floating ui in my initial PR, updated here

feat(date-textbox): added floating-ui support

---

src/components/site-footer.marko
src/components/site-header.marko
src/routes/_index/+layout.style.scss
src/routes/_index/sitemap+page.marko

Fixes #2411
This change adds a sitemap page to Skin docs for easier crawling and indexing by DocSearch and for SEO benefits. 
* The left rail is a bit redundant on larger screens. For now, instead of creating another layout with the left rail missing, I chose to simply hide it on the sitemap page. We can reassess this decision in the future, if needed.
* In the future, we should also move the site links into a JSON and use it from various parts of the site. ATM, they are static and duplication is necessary.

chore(docs): added sitemap to docs

---

.changeset/twelve-llamas-flash.md
src/routes/_index/component/chips-combobox/+page.marko
src/routes/_index/component/combobox/+page.marko
src/sass/chips-combobox/stories/chips-combobox.stories.js
src/sass/chips-combobox/stories/rtl-chips-combobox.stories.js
src/sass/combobox/stories/combobox.stories.js

Fixes #
- Removes chevron from examples for `combobox` and `chips-combobox` to reduce confusion on it being an input and not a dropdown

feat(combobox): remove chevron from combobox

---

src/components/about.marko

A gradual step in tone away from tight coupling to the eBay brand, towards how we *want* to also support non-branded experiences (even though our CSS variables aren't *quite* fully there yet)

Docs: updates to about section

---

.changeset/lemon-falcons-live.md
dist/list/list.css
src/sass/list/list.scss

Fixes #2515 
Changed list-style to be marker for list.css

fix(list): swapped to use marker

---

.changeset/kind-flies-turn.md
dist/badge/badge.css
dist/tokens/evo-dark.css
dist/tokens/evo-light.css
src/components/section-header.marko
src/sass/badge/badge.scss
src/tokens/evo-dark.css
src/tokens/evo-light.css

Fixes #2549 
* Added new stroke tokens.
* Added new badge border.
* Fixed a minor responsive display issue on the Skin site.

feat(badge): added new border

---

.changeset/giant-snails-jump.md
dist/tooltip/tooltip.css
src/sass/tooltip/tooltip.scss

Fixes #2524 
Updated tooltip colors.
**Before**
<kbd><img width="347" alt="image" src="https://github.com/user-attachments/assets/9628a07b-54f0-4824-bc0d-36269bffd2cd" /></kbd>
**After**
<kbd><img width="348" alt="image" src="https://github.com/user-attachments/assets/38aaa8c8-9ad4-437c-a08a-52a4e980c8fd" /></kbd>

feat(tooltip): updated colors

---

.changeset/shaggy-donuts-visit.md
src/routes/_index/component/button/+page.marko
src/routes/_index/component/calendar/+page.marko
src/routes/_index/component/chart-legend/+page.marko
src/routes/_index/component/combobox/+page.marko
src/routes/_index/component/confirm-dialog/+page.marko
src/routes/_index/component/cta-button/+page.marko
src/routes/_index/component/field/+page.marko
src/routes/_index/component/file-input/+page.marko
src/routes/_index/component/file-preview-card-group/+page.marko
src/routes/_index/component/file-preview-card/+page.marko
src/routes/_index/component/floating-label/+page.marko
src/routes/_index/component/inline-notice/+page.marko
src/routes/_index/component/lightbox-dialog/+page.marko
src/routes/_index/component/page-notice/+page.marko
src/routes/_index/component/section-notice/+page.marko
src/routes/_index/component/select/+page.marko
src/routes/_index/component/textbox/+page.marko

Fixes #2486 
Update the Design System canonical name mappings for some Skin modules, so that they map to the appropriate [Evo Design System components](https://playbook.ebay.com/design-system/components/)
This PR is only for some name mapping changes. The original ticket also mentioned version numbers, but I'd like to wait and do that in another PR after we've buttoned up some version tidying on the design system side.
This PR does not fix #2561.
N/A

chore: update DS name mappings

---

.changeset/happy-turkeys-hang.md
dist/avatar/avatar.css
dist/mixins/_utility-mixins.scss
src/routes/_index/component/avatar/+page.marko
src/sass/avatar/avatar.scss
src/sass/avatar/stories/avatar.stories.js
src/sass/mixins/public/_utility-mixins.scss

Fixes #2539
* Added a default `image-treatment` to avatar (this changes the default color, but is still usable)
* Added a `avatar--fit` modifier to allow the image to fit the contents. For making the behavior happen automatically, we can look into adding this into coreui to detect the image aspect ratio
* Added a note about using the image with colors so that the aspect ratio wont be applied.

feat(avatar): added fit modifier

---

.changeset/three-trees-change.md
dist/layout-grid/layout-grid.css
src/components/data/site.json
src/routes/_index/component/layout-grid/+meta.json
src/routes/_index/component/layout-grid/+page.marko
src/sass/bundles/skin-headless.scss
src/sass/layout-grid/layout-grid.scss
src/sass/layout-grid/stories/layout-grid.stories.js

Fixes #2466 
Created a new generic and component-agnostic layout grid component that allows for the easy implementation of responsive layouts with multiple components or elements inside.
This component will remove redundancy and `CSS` duplication across all similar grouped components, such as `toggle-button-group`.
**Unbalanced Layouts (previously)**
<kbd><img width="506" alt="image" src="https://github.com/user-attachments/assets/8691c1e3-8ffe-4934-9201-753c06282178" /></kbd>
**Balanced Layouts (new with this component)**
<kbd><img width="506" alt="image" src="https://github.com/user-attachments/assets/16fa321d-2c96-4ea3-8b54-a889d8d682c2" /></kbd>

feat(layout-grid): added new component

---

.changeset/tough-games-work.md
dist/global/global.css
dist/link/link.css
dist/tokens/evo-dark.css
dist/tokens/evo-light.css
src/routes/_index/component/link/+page.marko
src/sass/global/global.scss
src/sass/link/link.scss
src/sass/link/stories/link.stories.js
src/tokens/evo-dark.css
src/tokens/evo-light.css

Fixes #2564
* Added new legal link token
* Added new `legal-link` class to links
* Updated links to use link tokens (which were not being used or in the code)

feat(link): added legal link

---

.changeset/fuzzy-badgers-fix.md
dist/button/button.css
src/sass/button/button.scss
src/sass/mixins/private/_button-mixins.scss

Fixes #2554
* Added animation to buttons. 
* As per design, we are using motion-duration-short-3 since we can't differentiate between when it becomes pressed and when the button is released (plus the difference is 80ms so even so, its such a subtle difference)
* Added transition all, since all the transitions have the same values (and that way it affects both `filter` changes as well as `color` and `background`.

feat(button): added animation to buttons

---

.changeset/heavy-webs-try.md
dist/eek/eek.css
src/routes/_index/component/eek/+page.marko
src/sass/eek/eek.scss

Fixes #2580
* ~~Added option to flip EEK. I called it `eek--direction-start` (so that we use `start` instead of `left`). Happy to swap the option to another name if there are any suggestions.~~
* Changed default EEK to be flipped to the left.

feat(eek): flipped EEK direction

---

.changeset/curvy-mangos-send.md
dist/accordion/accordion.css
src/routes/_index/component/accordion/+page.marko
src/sass/accordion/accordion.scss
src/sass/accordion/stories/accordion.stories.js
src/sass/accordion/stories/cascade.stories.js
src/sass/accordion/stories/deprecated.stories.js

Fixes #2579
- Deprecated old icon(+/-) to reflect details chevron
- Added fill color to  `--color-foreground-secondary` for accordion
**Before**
**After**

feat(accordion): update expansion icon

---

dist/drawer-dialog/drawer-dialog.css
dist/panel-dialog/panel-dialog.css
src/sass/drawer-dialog/drawer-dialog.scss
src/sass/panel-dialog/panel-dialog.scss

Fixes #2601
This PR fixes an issue with panel and drawer dialogs. When Those dialogs open they create un needed scrollbar.
https://github.com/user-attachments/assets/cdb4aa2b-6d48-469e-a4f4-49e87a121efc
The original overflow is not needed in both of this cases as both of those dialogs have scrollable content with overflow auto.

fix(dialogs): remove dialogs scroll on entry

---

.changeset/moody-pumas-wear.md
dist/item-tile-group/item-tile-group.css
src/routes/_index/component/item-tile-group/+page.marko
src/sass/item-tile-group/item-tile-group.scss
src/sass/item-tile-group/stories/item-tile-group.stories.js

* Added defaults for column sizes for item-tile-group. This allows us to build the item tile without specifying any data-columns
* I added `.layout-grid.item-tile-group` as the main selector. I think we could have reordered the class to get it to work, but I prefer to make sure styles are applied no matter what order the classes are specified. If there's a better way, please let me know!

feat(item-tile-group): add default layouts inside item-tile-group
