eBay/skin

dist/less/ds6/mixins.less, dist/typography/ds6/typography.css, docs/_includes/ds6/less.html, docs/_includes/ds6/typography.html, docs/static/ds6/skin.css, src/less/less/ds6/mixins.less, src/less/typography/ds6/typography-base.less
=> Typography: add support for bold and secondary variants #57

CONTRIBUTING.md
Updating documentation for releases.
=> Updated release docs

gh.browser.json
Adding missing imports, which caused errors otherwise.
Reported by @CestDiego.
=> Fixing missing imports;

dist/breadcrumb/ds6/breadcrumb.css, docs/_includes/ds6/breadcrumb.html, docs/static/ds6/skin.css, src/less/breadcrumb/ds6/breadcrumb-base.less
Removing class:current and refactored the styling
=> removing class=current

dist/breadcrumb/ds6/breadcrumb.css, docs/_includes/ds6/breadcrumb.html, docs/static/ds6/skin.css, src/less/breadcrumb/ds6/breadcrumb-base.less
Refactored styling with span[aria-current]
=>  Removing class=current

dist/pagination/ds6/pagination.css, docs/_includes/ds6/pagination.html, docs/static/ds6/skin.css, src/less/pagination/ds6/pagination-base.less
Removing the class `.pagination__item__container` as it's a breaking change in the version.
Will prevent an unnecessary major version upgrade
=> Removed the version breaking class from pagination

dist/button/ds6/button.css, dist/combobox/ds6/combobox.css, dist/dropdown/ds6/dropdown.css, docs/static/ds6/skin.css, src/less/button/ds6/button-base.less, src/less/combobox/ds6/combobox-base.less
- fix secondary button color, hover state, and active states
- fix for primary button hover state
- fix for small button font size
- webkit-specific fix for the raw button
- separate some styles from the expand button, which does not share the same colors
Closes #127 
Closes #106 
Closes #100
=> Fixes to align to DSL

dist/button/ds4/button.css, dist/less/variables-common.less, dist/menu/ds4/menu.css, dist/notice/ds6/notice.css, dist/utility/ds4/utility.css, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/button/ds4/button-base.less, src/less/less/variables-common.less, src/less/marketsans/marketsans.less, src/less/menu/ds4/menu-base.less, src/less/menu/ds4/menu-mixins.less, src/less/menu/ds4/menu.less, src/less/notice/ds6/notice-base.less, src/less/utility/ds4/utility.less
Removed a bunch of deprecated classes, mixins and variables.
Pay attention to the src file comments rather than the dist files to understand what was already deprecated.
Major version update is a chance to clear out some dead wood.
=> Remove deprecated classes, mixins and variables

dist/button/ds6/button.css, dist/combobox/ds6/combobox.css, dist/dropdown/ds6/dropdown.css, dist/select/ds6/select.css, docs/static/ds6/skin.css, src/less/button/ds6/button-base.less, src/less/combobox/ds6/combobox-base.less, src/less/dropdown/ds6/dropdown-base.less, src/less/select/ds6/select-base.less
To align with DS6 design, we need to use a slightly bolder version of the carets.
Closes #79 
**Before**
**After**
=> Bolder icons for menu, combobox, and select

dist/breadcrumb/ds6/breadcrumb.css, docs/static/ds6/skin.css, src/less/breadcrumb/ds6/breadcrumb-base.less
Closes issue #133 
The flex box property was having no effect on the nav element (which has one flex item, the ul element), so I removed it.
=> Breadcrumbs: remove redundant flexbox

docs/_includes/ds6/install.html, docs/_includes/ds6/less.html, docs/_includes/install.html, docs/ds6/index.html
=> Website: add CDN and Lasso info

gh.browser.json, src/less/radio/ds6/radio-mixin.less
Each component should have a corresponding mixin file.
Global header needs to be able to use each component with a scoped class.
Closes #189
=> Radio mixin

checkbox.browser.json, dist/checkbox/ds6/checkbox.css, dist/less/ds6/variables.less, dist/radio/ds6/radio.css, docs/_includes/ds6/checkbox.html, docs/_layouts/ds6/default.html, docs/ds6/index.html, docs/static/ds6/skin.css, gh.browser.json, src/less/bundles/skin/ds6/skin.less, src/less/checkbox/ds6/checkbox-base.less, src/less/checkbox/ds6/checkbox-mixin.less, src/less/checkbox/ds6/checkbox.less, src/less/less/ds6/variables.less, src/less/radio/ds6/radio-base.less
Issue #140 
This applied DS6 styles to checkboxes, along with making use of new icons.
=> Checkbox: new DS6 styles

dist/checkbox/ds6/checkbox.css, dist/radio/ds6/radio.css, docs/static/ds6/skin.css, src/less/checkbox/ds6/checkbox-base.less, src/less/radio/ds6/radio-base.less
=> Revert "reset default browser styles for radio & checkbox"

dist/label/ds6/label.css, docs/static/ds6/skin.css, src/less/label/ds6/label-base.less
Closes #245 (maybe...)
Looks a little better, but we may need to adjust the timing function. Have a look:
https://files.slack.com/files-pri/T3U2DUYG4-FBGNPUUGJ/download/screen_recording.mov
=> Label: fix animation jank in Safari (#245)

gh.browser.json
=> Fix for label component mixin path;

dist/dropdown/ds6/dropdown.css
Artifact was left over from a recent PR.
Related to #287.
=> Fixing an artifact from a previous PR;

dist/actionable/ds4/actionable.css, dist/combobox/ds4/combobox.css, dist/combobox/ds6/combobox.css, dist/dialog/ds4/dialog.css, dist/dialog/ds6/dialog.css, dist/dropdown/ds4/dropdown.css, dist/dropdown/ds6/dropdown.css, dist/notice/ds4/notice.css, dist/notice/ds6/notice.css, dist/switch/ds4/switch.css, dist/switch/ds6/switch.css, dist/tab/ds4/tab.css, dist/utility/ds4/utility.css, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/actionable/ds4/actionable-base.less, src/less/dialog/ds4/dialog-base.less, src/less/dialog/ds6/dialog-base.less, src/less/dropdown/base/dropdown.less, src/less/notice/ds4/notice-base.less, src/less/notice/ds6/notice-base.less, src/less/switch/base/switch.less, src/less/tab/ds4/tab-base.less, src/less/utility/ds4/utility.less
See #238 for details.
@seangates I left one instance of `cursor: pointer` in menu in order to avoid a conflict with your work. Please remove it in your PR:
https://github.com/eBay/skin/blob/6.0.0/src/less/menu/ds4/menu-base.less#L76
Fixes #238
=> Remove cursor pointer for all non-links #238

dist/less/ds6/variables.less, dist/typography/ds6/typography.css, docs/static/ds6/skin.css, src/less/less/ds6/variables.less
Change font size 30 for DS6 to 1.875rem
Fix for https://github.com/eBay/skin/issues/298
=> bugfix for 298: Fix font size 30 for DS6

dist/notice/ds4/notice.css, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, package.json, yarn.lock
- upgrades `gulp-less` to v4
- fixes a couple of compilation errors (which were always there!)
Fixes #163
=> Upgrading to gulp-less v4;

dist/pagination/ds4/pagination.css, dist/pagination/ds6/pagination.css, docs/_includes/common/pagination.html, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/pagination/base/pagination.less, src/less/pagination/ds6/pagination.less
Updates the pagination styles to allow for button elements to be pagination items.
Fixes #293
=> Pagination: Support button items.

dist/textbox/ds6/textbox.css, docs/static/ds6/skin.css, src/less/textbox/ds6/textbox-mixins.less
Update color variable
meets design specs
Fixes https://github.com/eBay/skin/issues/303
=> update ds6 placeholder text color

dist/breadcrumb/ds4/breadcrumb.css, dist/breadcrumb/ds6/breadcrumb.css, dist/combobox/ds4/combobox.css, dist/combobox/ds6/combobox.css, dist/dropdown/ds4/dropdown.css, dist/dropdown/ds6/dropdown.css, dist/menu/ds4/menu.css, dist/menu/ds6/menu.css, dist/notice/ds4/notice.css, docs/_includes/common/breadcrumb.html, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/breadcrumb/base/breadcrumb.less, src/less/breadcrumb/ds4/breadcrumb.less, src/less/breadcrumb/ds6/breadcrumb.less, src/less/dropdown/base/dropdown.less
Updates the breadcrumb styles to allow for button elements to be breadcrumb items.
Fixes #348
=> Breadcrumbs: Support buttons

dist/combobox/ds6/combobox.css, dist/dropdown/ds6/dropdown.css, dist/menu/ds6/menu.css, docs/static/ds6/skin.css, src/less/dropdown/ds6/dropdown.less
Changed overflow:scroll to overflow:auto for dropdowns
Fixes https://github.com/eBay/skin/issues/364
=> changed dropdown overflow-y to auto

dist/pagination/ds4/pagination.css, dist/pagination/ds6/pagination.css, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/pagination/base/pagination.less, src/less/pagination/ds4/pagination.less, src/less/pagination/ds6/pagination.less
small pagination fix to make fluid and non fluid work in ds6 with ebayui-core
a max of 8 items where showing up with the default usage.  and responsive sizes where not hiding the correct items.
fix to go along with changes to ebayui-core for 1.0.0 release.
=> Update to pagination for ds6 to work with ebayui-core

dist/pagination/ds4/pagination.css, dist/pagination/ds6/pagination.css, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/pagination/base/pagination.less, src/less/pagination/ds4/pagination.less, src/less/pagination/ds6/pagination.less
Follow up to https://github.com/eBay/skin/pull/363 to fix a text zoom issue.
A11y support
https://github.com/eBay/ebayui-core/issues/374
=> Pagination pr placeholder

docs/test/misc/ds4/alignment-controls-grid.html
Updated HTML on test to match new skin requirements
Fixes https://github.com/eBay/skin/issues/285
Skin updated
=> fix ds4 alignment test

dist/breadcrumb/ds4/breadcrumb.css, dist/breadcrumb/ds6/breadcrumb.css, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, src/less/breadcrumb/base/breadcrumb.less, src/less/breadcrumb/ds6/breadcrumb.less
- fixes the breadcrumb chevron which was too wide and stretched in DS6
Fixes #392 
**Before**
**After**
=> Fix breadcrumb chevron;

docs/_includes/ds4/cdn.html, docs/_includes/ds4/grid.html, docs/_includes/ds6/install.html
- updated URL to the CDN in docs
It was pointing to old versions.
=> Updating CDN URL in docs;

dist/combobox/ds6/combobox.css, docs/static/ds6/skin.css, src/less/combobox/ds6/combobox.less
- fix for icon in the combobox stretching
**Before**
**After**
=> Fix for combobox icon stretching

less.browser.json
Minor optimization - Load the appropriate less files as per the lasso flags.
=> add lasso flags to less.browser.json

color.browser.json, dist/color/ds4/color.css, src/less/color/ds4/color-base.less, src/less/color/ds4/color.less
- adds color module for DS4
- color choices were used that match how DS6 will behave
Closes #228
=> Adding color module for DS4

dist/notice/ds4/notice.css, dist/notice/ds6/notice.css, dist/tooltip/ds4/tooltip.css, dist/tooltip/ds6/tooltip.css, docs/_includes/common/tooltip.html, docs/static/ds4/skin-full.css, docs/static/ds4/skin.css, docs/static/ds6/skin.css, docs/test/tooltip/ds6/index.html, src/less/mixins/bubble/base/bubble.less, src/less/mixins/bubble/ds4/bubble.less, src/less/mixins/bubble/ds6/bubble.less, src/less/tooltip/base/tooltip.less, src/less/tooltip/ds6/tooltip.less
- fixes the alignment of the pointer
- adds missing pointers for DS6 (left top, left bottom, right top, right bottom)
- fixes z-index issue with pointer (z-index for the overlay)
- fixes close button alignment
Minor issues were uncovered when implementing the Tooltip component.
https://github.com/eBay/skin/pull/467#issuecomment-442650174
=> Minor tooltip fixes

gh.browser.json, src/less/icon/common/ds6/icon-mixin.less, src/less/icon/icon-mixin.less
This PR should only contain changes related to the `gh.browser.json` fix.
=> Merge 6.3.1 into master prior to release

src/less/gh/ds6/gh-mixins.less
Fixes #564 
Fixes #565 
Also adds two new mixins:
* `icon-background-mixin`
* `icon-foreground-mixin`
=> GH: fixed path resolution (#564, #565)

CONTRIBUTING.md, README.md
This PR is intended to go straight into master branch.
I don't intend this to be an exhaustive list or set of definitions, but I think it puts in some good foundations that we can add to in future if necessary.
Please let me know if there are any errors or glaring omissions.
=> Docs: defined semantic versioning for Skin #3

docs/_includes/common/intro.html
=> Fixed spelling

package.json, yarn.lock
Updated devDeps. No impact to css.
=> Devdeps: upgraded lasso-autoprefixer and stylelint

listbox-button.browser.json, listbox-button.less, listbox-button[skin-ds6].less, menu-button.browser.json, menu-button.less, menu-button[skin-ds6].less
Changed browser json for listbox and menu to look up expanded button since it was refactored. 
ebay/ebayui-core/#733
=> Fixed listbox and menu to load expand-button

src/less/variables/ds6/icon-variables.less
Added "less" extension to the import statement for the variables.  Issue caught when building ebayUI-core.
=> Fix variables import

scripts/generate-images.js
Changed icon build script to rerun build after the files are written
Change it so the build runs after all the files are written.
=> Icon script automatate build

docs/_includes/common/badge.html, docs/_includes/common/breadcrumb.html, docs/_includes/common/button.html, docs/_includes/common/carousel.html, docs/_includes/common/checkbox.html, docs/_includes/common/color.html, docs/_includes/common/cta-button.html, docs/_includes/common/expand-button.html, docs/_includes/common/filter-button.html, docs/_includes/common/filter-menu-button.html, docs/_includes/common/filter-menu.html, docs/_includes/common/icon.html, docs/_includes/common/link.html, docs/_includes/common/menu.html, docs/_includes/common/notice.html, docs/_includes/common/pagination.html, docs/_includes/common/radio.html, docs/_includes/common/section-title.html, docs/_includes/common/switch.html, docs/_includes/common/tooltip.html, docs/_includes/common/typography.html
Fixed #841 
I have just copied over the version numbers verbatim, formatting and all, from the playbook. In a few cases, where the exact number wasn't clear, I have made a best guess.
I also sneaked in a change to remove a bunch of commented code from `notice.html`.
=> Website: updated DS6 version numbers under each section #841

dist/expand-button/ds4/expand-button.css, dist/expand-button/ds6/expand-button.css, src/less/expand-button/base/expand-button.less
=> Added disabled class to base expand button without secondary or primary

dist/mixins/bubble/ds4/bubble-mixins.less, dist/mixins/bubble/ds6/bubble-mixins.less, dist/tooltip/ds4/tooltip.css, dist/tooltip/ds6/tooltip.css, src/less/mixins/bubble/ds4/bubble-mixins.less, src/less/mixins/bubble/ds6/bubble-mixins.less, src/less/tooltip/ds6/tooltip.less
Fixes #1011
Removes colour from the mixin. This mixin should be for layout only, not colour, as different bubbles have different background colours.
=> Tooltip: close button hover color #1011

dist/combobox/ds4/combobox.css, dist/combobox/ds6/combobox.css, src/less/combobox/base/combobox.less, src/less/combobox/ds4/combobox.less, src/less/combobox/ds6/combobox.less
Added disabled color for combobox since it was missing
eBay/ebayui-core#1051
=> Added color disabled for combobox

dist/mixins/typography/base/typography-mixins.less, src/less/mixins/typography/base/typography-mixins.less
Use the correct typography variable name
Fixes #1031
=> use the correct variable name for the mixin

dist/spinner/ds4/spinner.css, dist/spinner/ds6/spinner.css, gh.browser.json, src/less/gh/ds6/gh-mixins.less, src/less/spinner/ds4/spinner.less, src/less/spinner/ds6/spinner.less
Two commits:
* Fix Spinner path (#1036)
* Fix GH Less paths
DO NOT SQUASH.
=> Fix spinner path & GH Less paths

dist/combobox/ds4/combobox.css, dist/combobox/ds6/combobox.css, docs/_includes/common/combobox.html, src/less/combobox/base/combobox.less, src/less/combobox/combobox.stories.js
=> feat: combobox with actionable icon

dist/label/ds6/label.css, src/less/label/ds6/label.less
Fixes #1055
Changes floating label from grey4 to grey5.
=> Label: fix color contrast ratio #1055

browser.json, wizard-stepper.browser.json
Quick patch release to add these missing entries for Wizard Stepper. @raveenakothapally is going to look into the generator script to ensure these entries are added in future (thanks Raveena!).
=> Wizard Stepper: add missing entries for Lasso

browser.json, toast.browser.json
Toast browser.jsons were not there, added them here
In case you already have another PR with it Ian, feel free to close this or whatnot.
=> Toast browser.json

dist/dialog/ds4/dialog.css, dist/dialog/ds6/dialog.css, dist/drawer/ds4/drawer.css, dist/drawer/ds6/drawer.css, dist/mixins/dialog/base/dialog-mixins.less, src/less/drawer/base/drawer.less, src/less/mixins/dialog/base/dialog-mixins.less
* When doing `flex: 1 0 auto` this failed when the body overflowed. I changed it to `flex: 1 1 auto` which fixes that issue
* ~~Added `position: absolute` and `top: -5000px` to hide the close button. Removed those attributes when `expanded` class is added~~
=> Fixed drawer scroll

dist/breadcrumbs/ds4/breadcrumbs.css, dist/breadcrumbs/ds6/breadcrumbs.css, dist/mixins/utility/utility-mixins.less, dist/variables/ds6/color-variables.less, src/less/breadcrumbs/base/breadcrumbs.less, src/less/breadcrumbs/ds4/breadcrumbs.less, src/less/breadcrumbs/ds6/breadcrumbs.less, src/less/mixins/utility/utility-mixins.less, src/less/variables/ds6/color-variables.less
PLEASE SQUASH
Added CSS to Breadcrumbs so dark mode can be enabled.
=> Added CSS to Dark Mode to Breadcrumbs

dist/toast/ds4/toast.css, dist/toast/ds6/toast.css, src/less/toast/base/toast.less
Simply upped the `z-index` to 2 for toast
#1119 
Before
After
=> Changed z-index to 2 to it doesn't bleed through with other items

CONTRIBUTING.md
PLEASE SQUASH.
This PR adds some documentation for our system of variables. We can refine this as we go, and add information for custom properties too, but this feels like a good starting point.
=> Document variables usage #1072

dist/stepper/ds4/stepper.css, dist/stepper/ds6/stepper.css, dist/wizard-stepper/ds4/wizard-stepper.css, dist/wizard-stepper/ds6/wizard-stepper.css, src/less/stepper/base/stepper.less, src/less/wizard-stepper/base/wizard-stepper.less
Added transition for upcoming
Fixes: #1138
=> Added transition for upcoming

dist/select/ds4/select.css, dist/select/ds6/select.css, dist/variables/ds4/select-variables.less, dist/variables/ds6/select-variables.less, docs/_includes/common/select.html, docs/_includes/common/textbox.html, docs/_includes/tests/select.html, src/less/select/base/select.less, src/less/variables/ds4/select-variables.less, src/less/variables/ds6/select-variables.less
Adding support for the bottom only border select component
https://github.com/eBay/skin/issues/1132
=> Support for Bottom only border Select

dist/dialog/ds4/dialog.css, dist/dialog/ds6/dialog.css, dist/drawer/ds4/drawer.css, dist/drawer/ds6/drawer.css, dist/mixins/dialog/base/dialog-mixins.less, docs/_includes/common/dialog.html, src/less/mixins/dialog/base/dialog-mixins.less
Fixed dialog footer to have position relative.
=> Dialog footer fix

dist/menu-button/ds4/menu-button.css, dist/menu-button/ds6/menu-button.css, dist/menu/ds4/menu.css, dist/menu/ds6/menu.css, dist/variables/ds4/menu-button-variables.less, dist/variables/ds4/menu-variables.less, dist/variables/ds6/menu-button-variables.less, dist/variables/ds6/menu-variables.less, docs/_includes/common/menu-button.html, docs/_includes/common/menu.html, src/less/menu-button/base/menu-button.less, src/less/menu-button/fake-menu-button.stories.js, src/less/menu-button/menu-button.stories.js, src/less/menu/base/menu.less, src/less/menu/fake-menu.stories.js, src/less/menu/menu.stories.js, src/less/stepper/stepper.stories.js, src/less/variables/ds4/menu-button-variables.less, src/less/variables/ds4/menu-variables.less, src/less/variables/ds6/menu-button-variables.less, src/less/variables/ds6/menu-variables.less
Fixes #1154
* Adds new variables for disabled menu items
* Adds selectors and styles for disabled states
* A few updates to menu documentation
* Split menu storybook stories into menu and menu-fake
=> Menu: add style for disabled menu items #1154

docs/_includes/tests/button.html, src/less/actionable/actionable.stories.js, src/less/breadcrumbs/breadcrumbs.stories.js, src/less/button/button.stories.js, src/less/button/fake-button.stories.js
Aligns examples in tests and storybook for actionable, breadcrumbs, button & fake button
https://github.com/eBay/skin/issues/996
=> Align examples in tests and storybook for actionable, breadcrumbs, button & fake button

docs/storybook/custom-styles.html
Adds missing custom styles file
=> Add custom styles file

docs/custom-styles.html, scripts/storybook/copy-custom-styles.js
Moved the custom styles in docs directory so it doesn't get removed by storybook build. Also updated scripts to target new path
=> Added custom styles storybook file again

dist/link/ds4/link.css, dist/link/ds6/link.css, dist/variables/ds4/link-variables.less, dist/variables/ds6/link-variables.less, src/less/link/base/link.less, src/less/variables/ds4/link-variables.less, src/less/variables/ds6/link-variables.less
Fixes #1187 
Sets fake-link (a button element) font-size to inherit.
=> Fake-Link: set font-size to inherit #1187

dist/dialog/ds4/dialog.css, src/less/dialog/ds4/dialog.less
Removed extra padding on dialog for DS4
ebay/ebayui-core#1183
=> Removing extra padding on DS4

dist/button/ds4/button.css, dist/button/ds6/button.css, index.browser.json, index.js, src/less/button/base/button.less
* Fixed stepper references
* Fixed fake  button to not have a variable anymore
#1201
eBay/ebayui-core#1192
=> Fixed references for stepper and visited fake button

dist/stepper/ds4/stepper.css, dist/stepper/ds6/stepper.css, src/less/stepper/base/stepper.less
Added stepper confirmation transition
It is required for the ebayui fix when confirmation is after current. 
ebay/ebayui-core#1189
=> Added confirmation transition

dist/checkbox/ds4/checkbox.css, dist/checkbox/ds6/checkbox.css, dist/radio/ds4/radio.css, dist/radio/ds6/radio.css, src/less/checkbox/base/checkbox.less, src/less/radio/base/radio.less
Input is positioon aboslute. Need to make parent relative so it doesn't shift. 
#1219 
Before
After
=> Added position relative to checkbox and radio to not allow input to shift

dist/fullscreen-dialog/ds4/fullscreen-dialog.css, dist/fullscreen-dialog/ds6/fullscreen-dialog.css, src/less/fullscreen-dialog/base/fullscreen-dialog.less
Added width 100% so it will wrap correctly and not continue to infinite
=> Added width 100% for fullscreen dialog

dist/menu/ds4/menu.css, dist/menu/ds6/menu.css, src/less/menu/base/menu.less
Added direct selector to menu-icon. This way if there needs to be a custom icon, it just needs to be wrapped in a span. 
#1034
=> Added direct child selector for menu icon

dist/page-notice/ds6/page-notice.css, dist/section-notice/ds6/section-notice.css, dist/variables/ds4/window-notice-variables.less, dist/variables/ds6/window-notice-variables.less, dist/window-notice/ds4/window-notice.css, dist/window-notice/ds6/window-notice.css, docs/_includes/common/section-notice.html, src/less/properties/base/window-notice-properties.less, src/less/properties/ds6/page-notice-properties.less, src/less/properties/ds6/section-notice-properties.less, src/less/properties/ds6/window-notice-properties.less, src/less/variables/ds4/window-notice-variables.less, src/less/variables/ds6/window-notice-variables.less, src/less/window-notice/base/window-notice.less
=> Dark mode updates for notices #1157

dist/icon/ds6/icon.css, dist/variables/ds6/icon-variables.less, src/less/icon/ds6/icon.less, src/less/variables/ds6/icon-variables.less
We have three extra small icons with no styles associated with them. Added the styles
#1243
=> Added missing styles for extra small icons

dist/combobox/ds6/combobox.css, dist/textbox/ds4/textbox.css, dist/textbox/ds6/textbox.css, dist/variables/ds6/border-radius-variables.less, src/less/properties/ds6/combobox-properties.less, src/less/properties/ds6/textbox-properties.less, src/less/textbox/base/textbox.less, src/less/variables/ds6/border-radius-variables.less
Updated border radius for combobox and textbox
=> Updated inputs border radius

dist/expand-button/ds4/expand-button.css, dist/expand-button/ds6/expand-button.css, src/less/expand-button/base/expand-button.less
Added primary hover color of white to expand button
https://github.com/eBay/ebayui-core/issues/1253
=> Added color to primary expand button hover (ebay/ebayui-core#1253)

dist/page-notice/ds4/page-notice.css, dist/page-notice/ds6/page-notice.css, src/less/page-notice/base/page-notice.less
Added `flex-wrap: wrap` for mweb and fixed styles to allow the button to take up full space. 
https://github.com/eBay/ebayui-core/issues/1261
=> Added support for mweb page notice with button

dist/section-notice/ds4/section-notice.css, dist/section-notice/ds6/section-notice.css, src/less/section-notice/base/section-notice.less
Same as https://github.com/eBay/skin/pull/1276 but for section-notice
https://github.com/eBay/ebayui-core/issues/1261
=> Added support for mweb section notice with button

dist/infotip/ds4/infotip.css, dist/infotip/ds6/infotip.css, docs/_includes/common/lightbox-dialog.html, src/less/infotip/base/infotip.less
=> Fixed Infotip close button outline 

dist/carousel/ds4/carousel.css, dist/carousel/ds6/carousel.css, dist/marketsans/marketsans.css, dist/mixins/carousel/base/carousel-mixins.less, dist/mixins/carousel/ds4/carousel-mixins.less, dist/mixins/carousel/ds6/carousel-mixins.less, dist/mixins/dialog/ds4/dialog-mixins.less, dist/mixins/dialog/ds6/dialog-mixins.less, dist/mixins/dropdown/ds4/dropdown-mixins.less, dist/mixins/dropdown/ds6/dropdown-mixins.less, dist/mixins/icon/ds4/icon-mixins.less, dist/mixins/icon/ds6/icon-mixins.less, dist/stepper/ds4/stepper.css, dist/stepper/ds6/stepper.css, dist/variables/ds4/border-radius-variables.less, dist/variables/ds4/bubble-variables.less, dist/variables/ds6/bubble-variables.less
This PR has some formatting changes that resulted when running `npm run build` on 12.2.0
Made this PR to reduce file changes for other PRs
=> dist files from npm run build

docs/_includes/common/fullscreen-dialog.html
=> Fix typo in class

src/selectors-api/selectors-api.json
As we have created more modules in Skin, some hadn't been added. This PR adds them into skin. 
Please let me know if I have overlooked any. 
closes #1397 
(No visual changes)
=> 1397 Update Selectors API

scripts/generate-imports/index.js
Part two of [PR](https://github.com/eBay/skin/pull/1410). This fixes the svg file extension for css files. 
closes #1394
=> Fix svg extension for .css file

src/less/infotip/stories/infotip.stories.js, src/less/tooltip/stories/pointer.stories.js, src/less/tooltip/stories/tooltip.stories.js, src/less/tourtip/stories/tourtip.stories.js
=> Added stories for infotip, tooltip, and tourtip

dist/video/ds4/video.css, dist/video/ds6/video.css, src/less/video/base/video.less, src/less/video/ds4/video.less, src/less/video/ds6/video.less
Added CSS which will be used by ebayui for video
=> feat(video): added new component

scripts/generate-bundle.js
Fixed generate-bundle script. 
Couple of changes
* This script was calling autoprefixer. However, this was calling autoprefixer on the already compiled css file. I had tried to correctly call this on an uncompiled less file, however the autoprefixer was messing up the comments with the wrapped content (moving the /*!Y*/ to the root selector). So I left it as is, but made it so the autoprefixer will not be called. This fixed one issue
* The other issue was the minifying process. I noticed that even in our minified code that the /*!Y*/ was being pulled out of the `supports` and moved in front. However, since these bundles are going to go through lasso, I added a `no-minify` option which will ignore the minifcation process. I renamed the css file from `skin.min.css` to `skin.css` in that …
=> fix(generate-bundle): fixed removing of comments

dist/textbox/ds4/textbox.css, dist/textbox/ds6/textbox.css, src/less/textbox/base/textbox.less
=> Font Family Consistent for input.textbox__control across browsers

dist/floating-label/ds4/floating-label.css, dist/floating-label/ds6/floating-label.css, src/less/floating-label/base/floating-label.less
=> Revert "fix(floating-label): dropped margin"

dist/floating-label/ds4/floating-label.css, dist/floating-label/ds6/floating-label.css, src/less/floating-label/base/floating-label.less
=> Revert "Revert "fix(floating-label): dropped margin"" - take out top margin

dist/page-notice/ds4/page-notice.css, dist/page-notice/ds6/page-notice.css, dist/section-notice/ds4/section-notice.css, dist/section-notice/ds6/section-notice.css, docs/_includes/common/page-notice.html, docs/_includes/common/section-notice.html, src/less/page-notice/base/page-notice.less, src/less/page-notice/page-notice.stories.js, src/less/page-notice/test.stories.js, src/less/section-notice/base/section-notice.less, src/less/section-notice/section-notice.stories.js, src/less/section-notice/test.stories.js
Clarifies use of headings. @agliga will this require any changes on the coreui side?
p.s I will update stories also if we are good with this.
=> feat(notice): rework headings

dist/video/ds4/video.css, dist/video/ds6/video.css, src/less/video/base/video.less
This PR removes the `shaka-scrim-container` which applied the gradient to thumbnail images, by adding `display: none;`. 
Ian let me know if there's a better way to do this - I just figured we had no need for the `shaka-scrim-container` class.
Will close coreui [1458](https://github.com/eBay/ebayui-core/issues/1458) when coreui is patched with this code.
=> fix(video): remove thumbnail gradient

dist/video/ds4/video.css, dist/video/ds6/video.css, src/less/video/base/video.less
adds a report-button class to the report button in ebay-video.
The view item team decided they wanted to have the report text in the control bar.
=> feat(video): added margin for the report button

dist/dark-mode/ds4/dark-mode.css, dist/dark-mode/ds6/dark-mode.css, dist/mixins/icon/base/icon-mixins.less, dist/tokens/base/tokens.less, docs/static/common/icons.svg, src/less/dark-mode/base/dark-mode.less, src/svg/icons.svg
Removed hardcoded fill and added css variables for icon
https://github.com/eBay/skin/issues/1633
=> feat(icon): removed hardcoded variables and added css variables for icon

scripts/generate-imports/config.json
Added dark-mode to config ignore Index
https://github.com/eBay/skin/issues/1653
=> fix(generate-imports): removed dark mode from index

src/less/bundles/skin/ds4/skin.less, src/less/bundles/skin/ds6/skin.less
Removed dark mode from bundle file
https://github.com/eBay/skin/issues/1653
=> fix: removed dark mode from CDN bundle

dist/drawer-dialog/ds4/drawer-dialog.css, dist/drawer-dialog/ds6/drawer-dialog.css, src/less/drawer-dialog/base/drawer-dialog.less, src/less/drawer-dialog/stories/drawer-dialog.stories.js
* added footer to drawer-dialog again
* Change look to look like new evo style
[#1639](https://github.com/eBay/skin/issues/1639)
=> fix(drawer-dialog): added footer back

dist/floating-label/ds4/floating-label.css, dist/floating-label/ds6/floating-label.css, src/less/floating-label/base/floating-label.less, src/less/floating-label/stories/floating-label.stories.js
* Reduced margin on select so that floating label doesn't cover chevron.
* Added stories for select
https://github.com/eBay/skin/issues/1670
=> fix(floating-label): added negative margin on select

dist/select/ds4/select.css, dist/select/ds6/select.css, src/less/select/base/select.less, src/less/select/stories/default.stories.js
* Fixed border-color to be attention color
* Fixed icon as well to be attention color
https://github.com/eBay/skin/issues/1674
=> fix(select): fixed border and icon color for invalid

scripts/generate-imports/config.json, scripts/generate-imports/index.js, scripts/generate-imports/module-builder.js
* Updated token module to have an index of core and light mode. This is the default import when doing `@ebay/skin/tokens`.
This relys on https://github.com/eBay/skin/pull/1767
=> feat: updated token imports to include index

package.json, scripts/generate-imports/index.js, scripts/generate-imports/module-builder.js, scripts/index.js, scripts/util.js, scripts/verify-build.js
Since we were talking about it, added a build verify script, which verifies the following:
* Runs build
* Runs postpublish
* Checks if any files have been changed or do not match what is checkedin to git
* Fails if that happens. 
This can be added as part of github actions and we can remove the "verify the build is non broken and regenerated all files checkboxes"
Cleaned up postpublish which would fail if no files were found
=> feat: added build verify script

scripts/generate-imports/config.json, scripts/generate-imports/index.js, scripts/generate-imports/module-builder.js
* Fixed tokens index.browser.json to be just browser.json
* Fixed top level index imports to have all files present except for tokens (we can see if we want to have an index and an index-legacy, but I left it open for teams for now).
=> fix: index top level imports

dist/legacy-tokens/ds4-light.css, dist/tokens/evo-dark.css, dist/tokens/evo-light.css, docs/static/evo-dark.css, docs/static/evo-light.css, src/tokens/evo-dark.css, src/tokens/evo-light.css
Added missing `--color-stroke-subtle` and fixed split button left border colors.
=> fix(tokens): added/fixed missing colors

src/less/gh/gh-mixins.less
Updated global header mixins to accommodate for file restructuring.
=> Updated Global Header Mixins

src/less/gh/gh-mixins.less
Fixes #
1. The paths in src/less/gh are not correct.
2. dist/color/color.css has been removed already
=> fix: paths fix for less/gh

dist/button/button.css, src/less/button/button.less
Fixes #1754 
- Updated tertiary button styles to match the design system
=> feat: updated tertiary button styles

dist/snackbar-dialog/snackbar-dialog.css, dist/tokens/evo-dark.css, src/less/snackbar-dialog/snackbar-dialog.less, src/tokens/evo-dark.css
- Fixes #1727
- Fixes ebay/ebayui-core#1737
- Inverted colors
- Moved to center (horizontally)
- Modified width
=> feat: updated snackbar dialog to match design system

dist/combobox/combobox.css, dist/filter-menu-button/filter-menu-button.css, dist/filter-menu/filter-menu.css, dist/listbox-button/listbox-button.css, dist/listbox/listbox.css, dist/menu/menu.css, docs/_includes/filter-menu.html, src/less/filter-menu/filter-menu.less, src/less/filter-menu/stories/filter-menu.stories.js, src/less/menu/menu.less, src/less/mixins/private/filter-menu-mixins.less, src/less/mixins/private/listbox-mixins.less
- Fixes git changes from #1870 
Let me know if there was a better way to do this, but Arthur and I weren't able to figure out how to move the other PR into this new (cleaned) branch. Only the feature changes should be present now, targeting 15.1.0.
=> feat(filter-menu): allow items to be disabled

dist/legacy-tokens/ds4-light.css, dist/tokens/evo-dark.css, dist/tokens/evo-light.css, src/tokens/evo-dark.css, src/tokens/evo-light.css
Added data viz color tokens.
This should help unblock ebay ui Highcharts implementation.
=> feat(data-viz): added data-viz color tokens

dist/button/button.css, dist/legacy-tokens/ds4-light.css, dist/tokens/evo-dark.css, dist/tokens/evo-light.css, src/less/button/button.less, src/tokens/evo-dark.css, src/tokens/evo-light.css
Fixes #1983 
* Added a new color change for tokens (for button secondary hover). It should change the border and color
I think we need to do something similar to tertiary but we need the colors from design
=> fix(button): added hover color and border color to secondary button

ICON-CREATION.md
Fixes #2017
Updated icon creation to cover the way to import new icons.
=> docs: updated icon creation guide

dist/field/field.css, src/less/field/field.less
Fixes #
Suggested fix unblocks compile time errors
=> fix: use flex-end

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/NEW-FEATURE-REQUEST.yml
Issue forms for bug report and new features
It's a bit difficult to conceptualize this and impossible to preview. Once approved, we can merge this and give it a run. If certain things need tweaking, we can follow it up with another PR to fix them. 
If this solution works well, we'll close the other PR with issue templates.
=> chore: created issue forms for bug report and new features

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/NEW-FEATURE-REQUEST.yml
Modifications based on additional feedback.
=> Issue forms: redux

.changeset/shaggy-yaks-guess.md, .storybook/main.js, dist/icon-button/icon-button.css, docs/_includes/icon-button.html, src/less/icon-button/icon-button.less, src/less/icon-button/stories/buttons.stories.js, src/less/icon-button/stories/links.stories.js
Fixes #2148 
Added priorities.
I turned off autodocs for storybook since we're not making use of it.
=> feat(icon-button): added priorities

.changeset/gold-radios-reply.md, dist/tokens/evo-dark.css, dist/tokens/evo-light.css, src/tokens/evo-dark.css, src/tokens/evo-light.css
Fixes #2340
* Removed code that is deprecated
=> chore: removed deprecations

.changeset/forty-schools-relate.md, dist/variables/variables.less, src/sass/variables/variables.less
https://github.com/eBay/skin/issues/2360
Added variables.less which were removed in a merge conflict
elete lists that are not applicable -->
=> chore: added variable.less file

.changeset/great-chicken-tan.md, dist/star-rating/star-rating.css, src/sass/star-rating/star-rating.scss
* Updated star rating to properly parse variable
=> fix(star-rating): fixed variable to compile

.changeset/dirty-melons-flow.md
I left one out of the `remove-source-maps` PR 😬
=> chore: add changeset

.changeset/tiny-berries-divide.md, src/components/token-system.marko, src/modules/tokens.marko
Fixes #2383
- Updated docs with disclaimer to refrain using primitive tokens.
- Moved semantic tokens above the primitive tokens. 
- Also wrapped the primitive tokens inside a details element.
=> docs(tokens): add primitive token disclaimer

.changeset/fluffy-tables-search.md, dist/gh/_gh-mixins.scss, dist/gh/gh-mixins.less, gh.browser.json, package.json
* gh.browser.json was using old paths, updated them to use non src paths.
=> fix(ghbrowser): fixed paths to point to dist

.changeset/selfish-flowers-kneel.md, dist/table/table.css, src/modules/table.marko, src/sass/table/stories/table.loading.stories.js, src/sass/table/table.scss
Fixes #2470 
* Added loading state
<kbd><img width="975" alt="image" src="https://github.com/user-attachments/assets/18a72b64-2220-43f9-930c-8c491962c6cf"></kbd>
=> feat(table): added loading state

.changeset/wicked-taxis-relate.md, dist/filter-menu/filter-menu.css, src/sass/filter-menu/filter-menu.scss
Fixed filter menu search cascade issue.
=> fix(filter-menu): fixed cascade

src/sass/button/button.scss, src/sass/carousel/carousel.scss, src/sass/cta-button/cta-button.scss, src/sass/filter-menu/filter-menu.scss, src/sass/mixins/private/_button-mixins.scss, src/sass/mixins/private/_menu-mixins.scss
Fixes #2485
* Updated some structuring for fixing deprecated messages. See https://sass-lang.com/documentation/breaking-changes/mixed-decls/
I was going to run percy to verify the changes don't break, however this change did not cause any dist file changes, so no percy run is needed.
=> chore(deprecations): restructed sass code to fix deprecation messages

.changeset/tricky-years-wait.md, dist/tokens/evo-light.css, src/tokens/evo-light.css
Fixes #2545 
Updated token to match DS specs.
=> feat(tokens): updated attention stroke token

.changeset/giant-comics-admire.md, dist/accordion/accordion.css, dist/tokens/evo-light.css, src/sass/accordion/accordion.scss, src/tokens/evo-light.css
Fixes #2530 
* Added new motion tokens with functions
* Replaced the raw values in accordion with new tokens
=> feat(tokens): added new motion tokens

.github/PULL_REQUEST_TEMPLATE.md
To avoid MIND patterns from falling through the cracks...
=> chore(PRs): Updated PR template to include MIND patterns for markup

.changeset/cyan-spiders-turn.md, dist/tokens/evo-core.css, dist/tokens/evo-dark.css, dist/tokens/evo-light.css, src/tokens/evo-core.css, src/tokens/evo-dark.css, src/tokens/evo-light.css
Fixes #2609 
Updated legal link colors per DS.
=> feat(link): updated legal link colors

.changeset/tough-jobs-melt.md, src/routes/_index/component/table/+page.marko, src/sass/table/stories/table.loading.stories.js
A11y adjustments to table loading state per internal discussions.
=> fix(table): a11y fixes for table loading state
